//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS.AIL.NLP.Inter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MARS.AIL.NLP.Inter.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t understand you (the direct object) ,Please try to use different way.
        /// </summary>
        internal static string ERROR_NLP_CANNT_UNDERSTAND_DOBJ {
            get {
                return ResourceManager.GetString("ERROR_NLP_CANNT_UNDERSTAND_DOBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t understand you ,Please try to use different way.
        /// </summary>
        internal static string ERROR_NLP_CANNT_UNDERSTAND_POBJ {
            get {
                return ResourceManager.GetString("ERROR_NLP_CANNT_UNDERSTAND_POBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS can&apos;t related object part for clause..
        /// </summary>
        internal static string ERROR_NLP_CANT_FIND_THAT_RELATED_OBJ {
            get {
                return ResourceManager.GetString("ERROR_NLP_CANT_FIND_THAT_RELATED_OBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word has more one meanings, can you clearify it?.
        /// </summary>
        internal static string ERROR_NLP_CONFUSION_OBJECT {
            get {
                return ResourceManager.GetString("ERROR_NLP_CONFUSION_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI come across unexpected error, please try later.
        /// </summary>
        internal static string ERROR_NLP_EXCEPTION_WHEN_GEN_STEP {
            get {
                return ResourceManager.GetString("ERROR_NLP_EXCEPTION_WHEN_GEN_STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI internal Error|Error code:ERROR_NLP_FIND_SPECIAL_TOKEN_NULL_PARA.
        /// </summary>
        internal static string ERROR_NLP_FIND_SPECIAL_TOKEN_NULL_PARA {
            get {
                return ResourceManager.GetString("ERROR_NLP_FIND_SPECIAL_TOKEN_NULL_PARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI internal Error| Error code:ERROR_NLP_FIND_THAT_RELATED_OBJ_NULL_PARA.
        /// </summary>
        internal static string ERROR_NLP_FIND_THAT_RELATED_OBJ_NULL_PARA {
            get {
                return ResourceManager.GetString("ERROR_NLP_FIND_THAT_RELATED_OBJ_NULL_PARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI come across an internal Error with Error code:ERROR_NLP_INTERNAL_IDX_NOT_SET.
        /// </summary>
        internal static string ERROR_NLP_INTERNAL_IDX_NOT_SET {
            get {
                return ResourceManager.GetString("ERROR_NLP_INTERNAL_IDX_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error, prediction token is null when tracing conjunction sub sentence..
        /// </summary>
        internal static string ERROR_NLP_INTERNAL_NO_PREDICTION_TOKEN {
            get {
                return ResourceManager.GetString("ERROR_NLP_INTERNAL_NO_PREDICTION_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error, sub sentence is null, Error Code:ERROR_NLP_INTERNAL_NO_SUBSENTENCE_PREVIEW.
        /// </summary>
        internal static string ERROR_NLP_INTERNAL_NO_SUBSENTENCE_PREVIEW {
            get {
                return ResourceManager.GetString("ERROR_NLP_INTERNAL_NO_SUBSENTENCE_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI come across an Internal Error with Error code:ERROR_NLP_INTERNAL_QUERY_ID_NOT_EXISTS.
        /// </summary>
        internal static string ERROR_NLP_INTERNAL_QUERY_ID_NOT_EXISTS {
            get {
                return ResourceManager.GetString("ERROR_NLP_INTERNAL_QUERY_ID_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI come across an Internal Error with Error code:ERROR_NLP_INTERNAL_QUERY_ID_NOT_NUMBER.
        /// </summary>
        internal static string ERROR_NLP_INTERNAL_QUERY_ID_NOT_NUMBER {
            get {
                return ResourceManager.GetString("ERROR_NLP_INTERNAL_QUERY_ID_NOT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI SVC currently has problem, can you try later? Please notify us if this error continues. Error code 001.
        /// </summary>
        internal static string ERROR_NLP_NO_MARS_OBJ {
            get {
                return ResourceManager.GetString("ERROR_NLP_NO_MARS_OBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No morpheme(verb) in the semantic block. .
        /// </summary>
        internal static string ERROR_NLP_NO_MORPHEME_IN_SEMANTIC_PREDICT {
            get {
                return ResourceManager.GetString("ERROR_NLP_NO_MORPHEME_IN_SEMANTIC_PREDICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI can&apos;t find object from the sentence. Please Train it..
        /// </summary>
        internal static string ERROR_NLP_NO_OBJ_FOR_IS_ARE {
            get {
                return ResourceManager.GetString("ERROR_NLP_NO_OBJ_FOR_IS_ARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No semantic data is passed..
        /// </summary>
        internal static string ERROR_NLP_NO_PARAMETER_FOR_CHECK_SUBJ_ITSELF {
            get {
                return ResourceManager.GetString("ERROR_NLP_NO_PARAMETER_FOR_CHECK_SUBJ_ITSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI can&apos;t find subject from the sentence. Please Train it..
        /// </summary>
        internal static string ERROR_NLP_NO_SUBJECT_FOR_IS_ARE {
            get {
                return ResourceManager.GetString("ERROR_NLP_NO_SUBJECT_FOR_IS_ARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS can understand you, but MARS can&apos;t find the object information from our dictionary, can you add it?.
        /// </summary>
        internal static string ERROR_NLP_UNKNOW_OBJECT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_NLP_UNKNOW_OBJECT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error, no Semantic block is generated.
        /// </summary>
        internal static string ERROR_NO_SEMANTIC_BLOCK {
            get {
                return ResourceManager.GetString("ERROR_NO_SEMANTIC_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No similar prediction part is found after traced parents semantics block..
        /// </summary>
        internal static string MESSAGE_NLP_NO_FIND_PREDICTION {
            get {
                return ResourceManager.GetString("MESSAGE_NLP_NO_FIND_PREDICTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS can&apos;t find object, please reinput..
        /// </summary>
        internal static string NLP_NO_OBJECT {
            get {
                return ResourceManager.GetString("NLP_NO_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No paired bracket exist in the sentence, Please change your text and try again..
        /// </summary>
        internal static string NLP_NO_PAIRED_BRACKETS {
            get {
                return ResourceManager.GetString("NLP_NO_PAIRED_BRACKETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI needs more trainning to understand the word..
        /// </summary>
        internal static string NLP_NO_SUCH_ITEM_IN_DICTIONARY {
            get {
                return ResourceManager.GetString("NLP_NO_SUCH_ITEM_IN_DICTIONARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI needs more infomation to understand the word..
        /// </summary>
        internal static string NLP_NO_WORD_DESCRIPTION {
            get {
                return ResourceManager.GetString("NLP_NO_WORD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI misses dictionary data, please contact to MARS support..
        /// </summary>
        internal static string NLP_NO_WORD_DITIONARY_DATA {
            get {
                return ResourceManager.GetString("NLP_NO_WORD_DITIONARY_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI is still learning, your feeds will make MARS AI stronger. Please wait for next version..
        /// </summary>
        internal static string NLP_UNKNOW_PATTERN {
            get {
                return ResourceManager.GetString("NLP_UNKNOW_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error, &quot;Get last object function&quot; gens Exception|{0}.
        /// </summary>
        internal static string SYS_EXCEPTION_FROM_GETLASTOFROMSTACK {
            get {
                return ResourceManager.GetString("SYS_EXCEPTION_FROM_GETLASTOFROMSTACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System internal Error, when try to find sub token list for conjunction. .
        /// </summary>
        internal static string SYS_EXCEPTION_INTERNAL_CANT_GET_CONJUCTION_SUBLIST {
            get {
                return ResourceManager.GetString("SYS_EXCEPTION_INTERNAL_CANT_GET_CONJUCTION_SUBLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System internal Error, when try to navigate or find sub token list for conjunction..
        /// </summary>
        internal static string SYS_EXCEPTION_INTERNAL_GET_CONJUCTION {
            get {
                return ResourceManager.GetString("SYS_EXCEPTION_INTERNAL_GET_CONJUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error, MARS can&apos;t generate Test steps for semantics block. Error code:SYS_EXCEPTION_WHEN_GEN_STEPS_BASED_ON_SEMANTICS_BLOCK.
        /// </summary>
        internal static string SYS_EXCEPTION_WHEN_GEN_STEPS_BASED_ON_SEMANTICS_BLOCK {
            get {
                return ResourceManager.GetString("SYS_EXCEPTION_WHEN_GEN_STEPS_BASED_ON_SEMANTICS_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARS AI can&apos;t find verb from NLP engine.
        /// </summary>
        internal static string SYS_NLP_VO_MODE_NO_VERB {
            get {
                return ResourceManager.GetString("SYS_NLP_VO_MODE_NO_VERB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error, morpheme is NULL.
        /// </summary>
        internal static string SYS_PARA_MORPHEMEM_IS_NULL {
            get {
                return ResourceManager.GetString("SYS_PARA_MORPHEMEM_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System internal Error,when try to build semantics block, Error Code:SYS_PARA_TOKENS_IS_NULL.
        /// </summary>
        internal static string SYS_PARA_TOKENS_IS_NULL {
            get {
                return ResourceManager.GetString("SYS_PARA_TOKENS_IS_NULL", resourceCulture);
            }
        }
    }
}
