//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BASELINE_DATA_DETAIL
    {
        public long DETAIL_ID { get; set; }
        public Nullable<long> DATA_BASE_OBJ_ID { get; set; }
        public Nullable<short> LOOP_ID { get; set; }
        public string DATA_VALUE { get; set; }
    }
}
