//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BASE_LINEDATA
    {
        public short DATA_SUMMARY_ID { get; set; }
        public string OBJECT_HAPPY_NAME { get; set; }
        public short LOOP_ID { get; set; }
        public string DATA_VALUE { get; set; }
    }
}
