//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="REL_TEST_SUIT_PROJECT"/> and <see cref="REL_TEST_SUIT_PROJECTDTO"/>.
    /// </summary>
    public static partial class REL_TEST_SUIT_PROJECTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="REL_TEST_SUIT_PROJECTDTO"/> converted from <see cref="REL_TEST_SUIT_PROJECT"/>.</param>
        static partial void OnDTO(this REL_TEST_SUIT_PROJECT entity, REL_TEST_SUIT_PROJECTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="REL_TEST_SUIT_PROJECT"/> converted from <see cref="REL_TEST_SUIT_PROJECTDTO"/>.</param>
        static partial void OnEntity(this REL_TEST_SUIT_PROJECTDTO dto, REL_TEST_SUIT_PROJECT entity);

        /// <summary>
        /// Converts this instance of <see cref="REL_TEST_SUIT_PROJECTDTO"/> to an instance of <see cref="REL_TEST_SUIT_PROJECT"/>.
        /// </summary>
        /// <param name="dto"><see cref="REL_TEST_SUIT_PROJECTDTO"/> to convert.</param>
        public static REL_TEST_SUIT_PROJECT ToEntity(this REL_TEST_SUIT_PROJECTDTO dto)
        {
            if (dto == null) return null;

            var entity = new REL_TEST_SUIT_PROJECT();

            entity.RELATIONSHIP_ID = dto.RELATIONSHIP_ID;
            entity.TEST_SUITE_ID = dto.TEST_SUITE_ID;
            entity.PROJECT_ID = dto.PROJECT_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="REL_TEST_SUIT_PROJECT"/> to an instance of <see cref="REL_TEST_SUIT_PROJECTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="REL_TEST_SUIT_PROJECT"/> to convert.</param>
        public static REL_TEST_SUIT_PROJECTDTO ToDTO(this REL_TEST_SUIT_PROJECT entity)
        {
            if (entity == null) return null;

            var dto = new REL_TEST_SUIT_PROJECTDTO();

            dto.RELATIONSHIP_ID = entity.RELATIONSHIP_ID;
            dto.TEST_SUITE_ID = entity.TEST_SUITE_ID;
            dto.PROJECT_ID = entity.PROJECT_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="REL_TEST_SUIT_PROJECTDTO"/> to an instance of <see cref="REL_TEST_SUIT_PROJECT"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<REL_TEST_SUIT_PROJECT> ToEntities(this IEnumerable<REL_TEST_SUIT_PROJECTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="REL_TEST_SUIT_PROJECT"/> to an instance of <see cref="REL_TEST_SUIT_PROJECTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<REL_TEST_SUIT_PROJECTDTO> ToDTOs(this IEnumerable<REL_TEST_SUIT_PROJECT> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
