//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="REL_TC_DATA_SUMMARY"/> and <see cref="REL_TC_DATA_SUMMARYDTO"/>.
    /// </summary>
    public static partial class REL_TC_DATA_SUMMARYAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="REL_TC_DATA_SUMMARYDTO"/> converted from <see cref="REL_TC_DATA_SUMMARY"/>.</param>
        static partial void OnDTO(this REL_TC_DATA_SUMMARY entity, REL_TC_DATA_SUMMARYDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="REL_TC_DATA_SUMMARY"/> converted from <see cref="REL_TC_DATA_SUMMARYDTO"/>.</param>
        static partial void OnEntity(this REL_TC_DATA_SUMMARYDTO dto, REL_TC_DATA_SUMMARY entity);

        /// <summary>
        /// Converts this instance of <see cref="REL_TC_DATA_SUMMARYDTO"/> to an instance of <see cref="REL_TC_DATA_SUMMARY"/>.
        /// </summary>
        /// <param name="dto"><see cref="REL_TC_DATA_SUMMARYDTO"/> to convert.</param>
        public static REL_TC_DATA_SUMMARY ToEntity(this REL_TC_DATA_SUMMARYDTO dto)
        {
            if (dto == null) return null;

            var entity = new REL_TC_DATA_SUMMARY();

            entity.ID = dto.ID;
            entity.DATA_SUMMARY_ID = dto.DATA_SUMMARY_ID;
            entity.TEST_CASE_ID = dto.TEST_CASE_ID;
            entity.CREATE_TIME = dto.CREATE_TIME;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="REL_TC_DATA_SUMMARY"/> to an instance of <see cref="REL_TC_DATA_SUMMARYDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="REL_TC_DATA_SUMMARY"/> to convert.</param>
        public static REL_TC_DATA_SUMMARYDTO ToDTO(this REL_TC_DATA_SUMMARY entity)
        {
            if (entity == null) return null;

            var dto = new REL_TC_DATA_SUMMARYDTO();

            dto.ID = entity.ID;
            dto.DATA_SUMMARY_ID = entity.DATA_SUMMARY_ID;
            dto.TEST_CASE_ID = entity.TEST_CASE_ID;
            dto.CREATE_TIME = entity.CREATE_TIME;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="REL_TC_DATA_SUMMARYDTO"/> to an instance of <see cref="REL_TC_DATA_SUMMARY"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<REL_TC_DATA_SUMMARY> ToEntities(this IEnumerable<REL_TC_DATA_SUMMARYDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="REL_TC_DATA_SUMMARY"/> to an instance of <see cref="REL_TC_DATA_SUMMARYDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<REL_TC_DATA_SUMMARYDTO> ToDTOs(this IEnumerable<REL_TC_DATA_SUMMARY> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
