//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class REL_APP_PROJDTO
    {
        [DataMember()]
        public Int64 RELATIONSHIP_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> APPLICATION_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> PROJECT_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_PROJECT_PROJECT_ID { get; set; }

        public REL_APP_PROJDTO()
        {
        }

        public REL_APP_PROJDTO(Int64 rELATIONSHIP_ID, Nullable<Int64> aPPLICATION_ID, Nullable<Int64> pROJECT_ID, Int64 t_TEST_PROJECT_PROJECT_ID)
        {
			this.RELATIONSHIP_ID = rELATIONSHIP_ID;
			this.APPLICATION_ID = aPPLICATION_ID;
			this.PROJECT_ID = pROJECT_ID;
			this.T_TEST_PROJECT_PROJECT_ID = t_TEST_PROJECT_PROJECT_ID;
        }
    }
}
