//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:37
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class REL_TEST_SUIT_PROJECTDTO
    {
        [DataMember()]
        public Int64 RELATIONSHIP_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> TEST_SUITE_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> PROJECT_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_PROJECT_PROJECT_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_SUITE_TEST_SUITE_ID { get; set; }

        public REL_TEST_SUIT_PROJECTDTO()
        {
        }

        public REL_TEST_SUIT_PROJECTDTO(Int64 rELATIONSHIP_ID, Nullable<Int64> tEST_SUITE_ID, Nullable<Int64> pROJECT_ID, Int64 t_TEST_PROJECT_PROJECT_ID, Int64 t_TEST_SUITE_TEST_SUITE_ID)
        {
			this.RELATIONSHIP_ID = rELATIONSHIP_ID;
			this.TEST_SUITE_ID = tEST_SUITE_ID;
			this.PROJECT_ID = pROJECT_ID;
			this.T_TEST_PROJECT_PROJECT_ID = t_TEST_PROJECT_PROJECT_ID;
			this.T_TEST_SUITE_TEST_SUITE_ID = t_TEST_SUITE_TEST_SUITE_ID;
        }
    }
}
