//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="REL_TEST_CASE_TEST_SUITE"/> and <see cref="REL_TEST_CASE_TEST_SUITEDTO"/>.
    /// </summary>
    public static partial class REL_TEST_CASE_TEST_SUITEAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="REL_TEST_CASE_TEST_SUITEDTO"/> converted from <see cref="REL_TEST_CASE_TEST_SUITE"/>.</param>
        static partial void OnDTO(this REL_TEST_CASE_TEST_SUITE entity, REL_TEST_CASE_TEST_SUITEDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="REL_TEST_CASE_TEST_SUITE"/> converted from <see cref="REL_TEST_CASE_TEST_SUITEDTO"/>.</param>
        static partial void OnEntity(this REL_TEST_CASE_TEST_SUITEDTO dto, REL_TEST_CASE_TEST_SUITE entity);

        /// <summary>
        /// Converts this instance of <see cref="REL_TEST_CASE_TEST_SUITEDTO"/> to an instance of <see cref="REL_TEST_CASE_TEST_SUITE"/>.
        /// </summary>
        /// <param name="dto"><see cref="REL_TEST_CASE_TEST_SUITEDTO"/> to convert.</param>
        public static REL_TEST_CASE_TEST_SUITE ToEntity(this REL_TEST_CASE_TEST_SUITEDTO dto)
        {
            if (dto == null) return null;

            var entity = new REL_TEST_CASE_TEST_SUITE();

            entity.RELATIONSHIP_ID = dto.RELATIONSHIP_ID;
            entity.TEST_CASE_ID = dto.TEST_CASE_ID;
            entity.TEST_SUITE_ID = dto.TEST_SUITE_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="REL_TEST_CASE_TEST_SUITE"/> to an instance of <see cref="REL_TEST_CASE_TEST_SUITEDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="REL_TEST_CASE_TEST_SUITE"/> to convert.</param>
        public static REL_TEST_CASE_TEST_SUITEDTO ToDTO(this REL_TEST_CASE_TEST_SUITE entity)
        {
            if (entity == null) return null;

            var dto = new REL_TEST_CASE_TEST_SUITEDTO();

            dto.RELATIONSHIP_ID = entity.RELATIONSHIP_ID;
            dto.TEST_CASE_ID = entity.TEST_CASE_ID;
            dto.TEST_SUITE_ID = entity.TEST_SUITE_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="REL_TEST_CASE_TEST_SUITEDTO"/> to an instance of <see cref="REL_TEST_CASE_TEST_SUITE"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<REL_TEST_CASE_TEST_SUITE> ToEntities(this IEnumerable<REL_TEST_CASE_TEST_SUITEDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="REL_TEST_CASE_TEST_SUITE"/> to an instance of <see cref="REL_TEST_CASE_TEST_SUITEDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<REL_TEST_CASE_TEST_SUITEDTO> ToDTOs(this IEnumerable<REL_TEST_CASE_TEST_SUITE> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
