//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:58
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_BASELINE_DATA_DETAIL"/> and <see cref="T_BASELINE_DATA_DETAILDTO"/>.
    /// </summary>
    public static partial class T_BASELINE_DATA_DETAILAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_BASELINE_DATA_DETAILDTO"/> converted from <see cref="T_BASELINE_DATA_DETAIL"/>.</param>
        static partial void OnDTO(this T_BASELINE_DATA_DETAIL entity, T_BASELINE_DATA_DETAILDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_BASELINE_DATA_DETAIL"/> converted from <see cref="T_BASELINE_DATA_DETAILDTO"/>.</param>
        static partial void OnEntity(this T_BASELINE_DATA_DETAILDTO dto, T_BASELINE_DATA_DETAIL entity);

        /// <summary>
        /// Converts this instance of <see cref="T_BASELINE_DATA_DETAILDTO"/> to an instance of <see cref="T_BASELINE_DATA_DETAIL"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_BASELINE_DATA_DETAILDTO"/> to convert.</param>
        public static T_BASELINE_DATA_DETAIL ToEntity(this T_BASELINE_DATA_DETAILDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_BASELINE_DATA_DETAIL();

            entity.DETAIL_ID = dto.DETAIL_ID;
            entity.DATA_BASE_OBJ_ID = dto.DATA_BASE_OBJ_ID;
            entity.LOOP_ID = dto.LOOP_ID;
            entity.DATA_VALUE = dto.DATA_VALUE;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_BASELINE_DATA_DETAIL"/> to an instance of <see cref="T_BASELINE_DATA_DETAILDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_BASELINE_DATA_DETAIL"/> to convert.</param>
        public static T_BASELINE_DATA_DETAILDTO ToDTO(this T_BASELINE_DATA_DETAIL entity)
        {
            if (entity == null) return null;

            var dto = new T_BASELINE_DATA_DETAILDTO();

            dto.DETAIL_ID = entity.DETAIL_ID;
            dto.DATA_BASE_OBJ_ID = entity.DATA_BASE_OBJ_ID;
            dto.LOOP_ID = entity.LOOP_ID;
            dto.DATA_VALUE = entity.DATA_VALUE;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_BASELINE_DATA_DETAILDTO"/> to an instance of <see cref="T_BASELINE_DATA_DETAIL"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_BASELINE_DATA_DETAIL> ToEntities(this IEnumerable<T_BASELINE_DATA_DETAILDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_BASELINE_DATA_DETAIL"/> to an instance of <see cref="T_BASELINE_DATA_DETAILDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_BASELINE_DATA_DETAILDTO> ToDTOs(this IEnumerable<T_BASELINE_DATA_DETAIL> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
