//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:59
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_BASELINE_DATA_SUMMARY"/> and <see cref="T_BASELINE_DATA_SUMMARYDTO"/>.
    /// </summary>
    public static partial class T_BASELINE_DATA_SUMMARYAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_BASELINE_DATA_SUMMARYDTO"/> converted from <see cref="T_BASELINE_DATA_SUMMARY"/>.</param>
        static partial void OnDTO(this T_BASELINE_DATA_SUMMARY entity, T_BASELINE_DATA_SUMMARYDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_BASELINE_DATA_SUMMARY"/> converted from <see cref="T_BASELINE_DATA_SUMMARYDTO"/>.</param>
        static partial void OnEntity(this T_BASELINE_DATA_SUMMARYDTO dto, T_BASELINE_DATA_SUMMARY entity);

        /// <summary>
        /// Converts this instance of <see cref="T_BASELINE_DATA_SUMMARYDTO"/> to an instance of <see cref="T_BASELINE_DATA_SUMMARY"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_BASELINE_DATA_SUMMARYDTO"/> to convert.</param>
        public static T_BASELINE_DATA_SUMMARY ToEntity(this T_BASELINE_DATA_SUMMARYDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_BASELINE_DATA_SUMMARY();

            entity.DATA_BASE_OBJ_ID = dto.DATA_BASE_OBJ_ID;
            entity.DATA_SUMMARY_ID = dto.DATA_SUMMARY_ID;
            entity.DATA_BASE_OBJ_PARENT_ID = dto.DATA_BASE_OBJ_PARENT_ID;
            entity.OBJECT_HAPPY_NAME = dto.OBJECT_HAPPY_NAME;
            entity.ORDER_ID = dto.ORDER_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_BASELINE_DATA_SUMMARY"/> to an instance of <see cref="T_BASELINE_DATA_SUMMARYDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_BASELINE_DATA_SUMMARY"/> to convert.</param>
        public static T_BASELINE_DATA_SUMMARYDTO ToDTO(this T_BASELINE_DATA_SUMMARY entity)
        {
            if (entity == null) return null;

            var dto = new T_BASELINE_DATA_SUMMARYDTO();

            dto.DATA_BASE_OBJ_ID = entity.DATA_BASE_OBJ_ID;
            dto.DATA_SUMMARY_ID = entity.DATA_SUMMARY_ID;
            dto.DATA_BASE_OBJ_PARENT_ID = entity.DATA_BASE_OBJ_PARENT_ID;
            dto.OBJECT_HAPPY_NAME = entity.OBJECT_HAPPY_NAME;
            dto.ORDER_ID = entity.ORDER_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_BASELINE_DATA_SUMMARYDTO"/> to an instance of <see cref="T_BASELINE_DATA_SUMMARY"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_BASELINE_DATA_SUMMARY> ToEntities(this IEnumerable<T_BASELINE_DATA_SUMMARYDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_BASELINE_DATA_SUMMARY"/> to an instance of <see cref="T_BASELINE_DATA_SUMMARYDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_BASELINE_DATA_SUMMARYDTO> ToDTOs(this IEnumerable<T_BASELINE_DATA_SUMMARY> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
