//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:40
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class T_DATA_SOURCEDTO
    {
        [DataMember()]
        public Int64 DATA_SOURCE_ID { get; set; }

        [DataMember()]
        public String DATA_SOURCE_NAME { get; set; }

        [DataMember()]
        public Nullable<Int16> DATA_SOURCE_TYPE { get; set; }

        [DataMember()]
        public String DETAILS { get; set; }

        [DataMember()]
        public String DB_CONNECTION { get; set; }

        [DataMember()]
        public Nullable<Int16> DB_TYPE { get; set; }

        [DataMember()]
        public String TEST_CONNECTION { get; set; }

        [DataMember()]
        public List<Int64> T_PROJECT_DATA_SOURCE_PRO_DBS_ID { get; set; }

        public T_DATA_SOURCEDTO()
        {
        }

        public T_DATA_SOURCEDTO(Int64 dATA_SOURCE_ID, String dATA_SOURCE_NAME, Nullable<Int16> dATA_SOURCE_TYPE, String dETAILS, String dB_CONNECTION, Nullable<Int16> dB_TYPE, String tEST_CONNECTION, List<Int64> t_PROJECT_DATA_SOURCE_PRO_DBS_ID)
        {
			this.DATA_SOURCE_ID = dATA_SOURCE_ID;
			this.DATA_SOURCE_NAME = dATA_SOURCE_NAME;
			this.DATA_SOURCE_TYPE = dATA_SOURCE_TYPE;
			this.DETAILS = dETAILS;
			this.DB_CONNECTION = dB_CONNECTION;
			this.DB_TYPE = dB_TYPE;
			this.TEST_CONNECTION = tEST_CONNECTION;
			this.T_PROJECT_DATA_SOURCE_PRO_DBS_ID = t_PROJECT_DATA_SOURCE_PRO_DBS_ID;
        }
    }
}
