//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class T_MARS_COMPANYDTO
    {
        [DataMember()]
        public Decimal COMPANY_ID { get; set; }

        [DataMember()]
        public String COMPANY_NAME { get; set; }

        [DataMember()]
        public String COMPANY_DESC { get; set; }

        [DataMember()]
        public String COMPANY_NUMBER { get; set; }

        [DataMember()]
        public String COMPANY_ADDRESS { get; set; }

        [DataMember()]
        public String CREATE_USERNAME { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_TIME { get; set; }

        [DataMember()]
        public Nullable<Decimal> AVAILABLE_MARK { get; set; }

        [DataMember()]
        public List<Decimal> T_TESTER_INFO_TESTER_ID { get; set; }

        public T_MARS_COMPANYDTO()
        {
        }

        public T_MARS_COMPANYDTO(Decimal cOMPANY_ID, String cOMPANY_NAME, String cOMPANY_DESC, String cOMPANY_NUMBER, String cOMPANY_ADDRESS, String cREATE_USERNAME, Nullable<DateTime> cREATE_TIME, Nullable<Decimal> aVAILABLE_MARK, List<Decimal> t_TESTER_INFO_TESTER_ID)
        {
			this.COMPANY_ID = cOMPANY_ID;
			this.COMPANY_NAME = cOMPANY_NAME;
			this.COMPANY_DESC = cOMPANY_DESC;
			this.COMPANY_NUMBER = cOMPANY_NUMBER;
			this.COMPANY_ADDRESS = cOMPANY_ADDRESS;
			this.CREATE_USERNAME = cREATE_USERNAME;
			this.CREATE_TIME = cREATE_TIME;
			this.AVAILABLE_MARK = aVAILABLE_MARK;
			this.T_TESTER_INFO_TESTER_ID = t_TESTER_INFO_TESTER_ID;
        }
    }
}
