//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_OBJECT_NAMEINFO"/> and <see cref="T_OBJECT_NAMEINFODTO"/>.
    /// </summary>
    public static partial class T_OBJECT_NAMEINFOAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_OBJECT_NAMEINFODTO"/> converted from <see cref="T_OBJECT_NAMEINFO"/>.</param>
        static partial void OnDTO(this T_OBJECT_NAMEINFO entity, T_OBJECT_NAMEINFODTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_OBJECT_NAMEINFO"/> converted from <see cref="T_OBJECT_NAMEINFODTO"/>.</param>
        static partial void OnEntity(this T_OBJECT_NAMEINFODTO dto, T_OBJECT_NAMEINFO entity);

        /// <summary>
        /// Converts this instance of <see cref="T_OBJECT_NAMEINFODTO"/> to an instance of <see cref="T_OBJECT_NAMEINFO"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_OBJECT_NAMEINFODTO"/> to convert.</param>
        public static T_OBJECT_NAMEINFO ToEntity(this T_OBJECT_NAMEINFODTO dto)
        {
            if (dto == null) return null;

            var entity = new T_OBJECT_NAMEINFO();

            entity.OBJECT_NAME_ID = dto.OBJECT_NAME_ID;
            entity.OBJECT_HAPPY_NAME = dto.OBJECT_HAPPY_NAME;
            entity.PEGWINDOW_MARK = dto.PEGWINDOW_MARK;
            entity.OBJNAME_DESCRIPTION = dto.OBJNAME_DESCRIPTION;
            entity.EXT_ID = dto.EXT_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_OBJECT_NAMEINFO"/> to an instance of <see cref="T_OBJECT_NAMEINFODTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_OBJECT_NAMEINFO"/> to convert.</param>
        public static T_OBJECT_NAMEINFODTO ToDTO(this T_OBJECT_NAMEINFO entity)
        {
            if (entity == null) return null;

            var dto = new T_OBJECT_NAMEINFODTO();

            dto.OBJECT_NAME_ID = entity.OBJECT_NAME_ID;
            dto.OBJECT_HAPPY_NAME = entity.OBJECT_HAPPY_NAME;
            dto.PEGWINDOW_MARK = entity.PEGWINDOW_MARK;
            dto.OBJNAME_DESCRIPTION = entity.OBJNAME_DESCRIPTION;
            dto.EXT_ID = entity.EXT_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_OBJECT_NAMEINFODTO"/> to an instance of <see cref="T_OBJECT_NAMEINFO"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_OBJECT_NAMEINFO> ToEntities(this IEnumerable<T_OBJECT_NAMEINFODTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_OBJECT_NAMEINFO"/> to an instance of <see cref="T_OBJECT_NAMEINFODTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_OBJECT_NAMEINFODTO> ToDTOs(this IEnumerable<T_OBJECT_NAMEINFO> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
