//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:45
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class T_OBJECT_NAMEINFODTO
    {
        [DataMember()]
        public Int64 OBJECT_NAME_ID { get; set; }

        [DataMember()]
        public String OBJECT_HAPPY_NAME { get; set; }

        [DataMember()]
        public Nullable<Int16> PEGWINDOW_MARK { get; set; }

        [DataMember()]
        public String OBJNAME_DESCRIPTION { get; set; }

        [DataMember()]
        public Nullable<Int64> EXT_ID { get; set; }

        public T_OBJECT_NAMEINFODTO()
        {
        }

        public T_OBJECT_NAMEINFODTO(Int64 oBJECT_NAME_ID, String oBJECT_HAPPY_NAME, Nullable<Int16> pEGWINDOW_MARK, String oBJNAME_DESCRIPTION, Nullable<Int64> eXT_ID)
        {
			this.OBJECT_NAME_ID = oBJECT_NAME_ID;
			this.OBJECT_HAPPY_NAME = oBJECT_HAPPY_NAME;
			this.PEGWINDOW_MARK = pEGWINDOW_MARK;
			this.OBJNAME_DESCRIPTION = oBJNAME_DESCRIPTION;
			this.EXT_ID = eXT_ID;
        }
    }
}
