//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:03
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_REGISTERED_APPS"/> and <see cref="T_REGISTERED_APPSDTO"/>.
    /// </summary>
    public static partial class T_REGISTERED_APPSAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_REGISTERED_APPSDTO"/> converted from <see cref="T_REGISTERED_APPS"/>.</param>
        static partial void OnDTO(this T_REGISTERED_APPS entity, T_REGISTERED_APPSDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_REGISTERED_APPS"/> converted from <see cref="T_REGISTERED_APPSDTO"/>.</param>
        static partial void OnEntity(this T_REGISTERED_APPSDTO dto, T_REGISTERED_APPS entity);

        /// <summary>
        /// Converts this instance of <see cref="T_REGISTERED_APPSDTO"/> to an instance of <see cref="T_REGISTERED_APPS"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_REGISTERED_APPSDTO"/> to convert.</param>
        public static T_REGISTERED_APPS ToEntity(this T_REGISTERED_APPSDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_REGISTERED_APPS();

            entity.APPLICATION_ID = dto.APPLICATION_ID;
            entity.APP_SHORT_NAME = dto.APP_SHORT_NAME;
            entity.PROCESS_IDENTIFIER = dto.PROCESS_IDENTIFIER;
            entity.STARTER_PATH = dto.STARTER_PATH;
            entity.STARTER_COMMAND = dto.STARTER_COMMAND;
            entity.VERSION = dto.VERSION;
            entity.COMMENT = dto.COMMENT;
            entity.APPLICATION_TYPE_ID = dto.APPLICATION_TYPE_ID;
            entity.RECORD_CREATE_PERSON = dto.RECORD_CREATE_PERSON;
            entity.RECORD_CREATE_DATE = dto.RECORD_CREATE_DATE;
            entity.EXTRAREQUIREMENT = dto.EXTRAREQUIREMENT;
            entity.EXTRAPOPUPMENU = dto.EXTRAPOPUPMENU;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_REGISTERED_APPS"/> to an instance of <see cref="T_REGISTERED_APPSDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_REGISTERED_APPS"/> to convert.</param>
        public static T_REGISTERED_APPSDTO ToDTO(this T_REGISTERED_APPS entity)
        {
            if (entity == null) return null;

            var dto = new T_REGISTERED_APPSDTO();

            dto.APPLICATION_ID = entity.APPLICATION_ID;
            dto.APP_SHORT_NAME = entity.APP_SHORT_NAME;
            dto.PROCESS_IDENTIFIER = entity.PROCESS_IDENTIFIER;
            dto.STARTER_PATH = entity.STARTER_PATH;
            dto.STARTER_COMMAND = entity.STARTER_COMMAND;
            dto.VERSION = entity.VERSION;
            dto.COMMENT = entity.COMMENT;
            dto.APPLICATION_TYPE_ID = entity.APPLICATION_TYPE_ID;
            dto.RECORD_CREATE_PERSON = entity.RECORD_CREATE_PERSON;
            dto.RECORD_CREATE_DATE = entity.RECORD_CREATE_DATE;
            dto.EXTRAREQUIREMENT = entity.EXTRAREQUIREMENT;
            dto.EXTRAPOPUPMENU = entity.EXTRAPOPUPMENU;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_REGISTERED_APPSDTO"/> to an instance of <see cref="T_REGISTERED_APPS"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_REGISTERED_APPS> ToEntities(this IEnumerable<T_REGISTERED_APPSDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_REGISTERED_APPS"/> to an instance of <see cref="T_REGISTERED_APPSDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_REGISTERED_APPSDTO> ToDTOs(this IEnumerable<T_REGISTERED_APPS> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
