//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:47
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class T_REGISTED_OBJECTDTO
    {
        [DataMember()]
        public virtual Int64 OBJECT_ID { get; set; }

        [DataMember()]
        public virtual Nullable<Int64> APPLICATION_ID { get; set; }

        [DataMember()]
        public virtual Nullable<Int64> TYPE_ID { get; set; }

        [DataMember()]
        public virtual String QUICK_ACCESS { get; set; }

        [DataMember()]
        public virtual String OBJECT_TYPE { get; set; }

        [DataMember()]
        public virtual String COMMENT { get; set; }

        [DataMember()]
        public virtual String ENUM_TYPE { get; set; }

        [DataMember()]
        public virtual Nullable<Int64> OBJECT_NAME_ID { get; set; }

        [DataMember()]
        public virtual Byte[] OBJ_DATA_SRC { get; set; }

        [DataMember()]
        public virtual Nullable<Int16> IS_CHECKERROR_OBJ { get; set; }

        [DataMember()]
        public Int64 T_GUI_COMPONENT_TYPE_DIC_TYPE_ID { get; set; }

        [DataMember()]
        public List<Int64> T_TEST_STEPS_STEPS_ID { get; set; }

        public T_REGISTED_OBJECTDTO()
        {
        }

        public T_REGISTED_OBJECTDTO(Int64 oBJECT_ID, Nullable<Int64> aPPLICATION_ID, Nullable<Int64> tYPE_ID, String qUICK_ACCESS, String oBJECT_TYPE, String cOMMENT, String eNUM_TYPE, Nullable<Int64> oBJECT_NAME_ID, Byte[] oBJ_DATA_SRC, Nullable<Int16> iS_CHECKERROR_OBJ, Int64 t_GUI_COMPONENT_TYPE_DIC_TYPE_ID, List<Int64> t_TEST_STEPS_STEPS_ID)
        {
			this.OBJECT_ID = oBJECT_ID;
			this.APPLICATION_ID = aPPLICATION_ID;
			this.TYPE_ID = tYPE_ID;
			this.QUICK_ACCESS = qUICK_ACCESS;
			this.OBJECT_TYPE = oBJECT_TYPE;
			this.COMMENT = cOMMENT;
			this.ENUM_TYPE = eNUM_TYPE;
			this.OBJECT_NAME_ID = oBJECT_NAME_ID;
			this.OBJ_DATA_SRC = oBJ_DATA_SRC;
			this.IS_CHECKERROR_OBJ = iS_CHECKERROR_OBJ;
			this.T_GUI_COMPONENT_TYPE_DIC_TYPE_ID = t_GUI_COMPONENT_TYPE_DIC_TYPE_ID;
			this.T_TEST_STEPS_STEPS_ID = t_TEST_STEPS_STEPS_ID;
        }
    }
}
