//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:03
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_REGISTED_OBJECT"/> and <see cref="T_REGISTED_OBJECTDTO"/>.
    /// </summary>
    public static partial class T_REGISTED_OBJECTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_REGISTED_OBJECTDTO"/> converted from <see cref="T_REGISTED_OBJECT"/>.</param>
        static partial void OnDTO(this T_REGISTED_OBJECT entity, T_REGISTED_OBJECTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_REGISTED_OBJECT"/> converted from <see cref="T_REGISTED_OBJECTDTO"/>.</param>
        static partial void OnEntity(this T_REGISTED_OBJECTDTO dto, T_REGISTED_OBJECT entity);

        /// <summary>
        /// Converts this instance of <see cref="T_REGISTED_OBJECTDTO"/> to an instance of <see cref="T_REGISTED_OBJECT"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_REGISTED_OBJECTDTO"/> to convert.</param>
        public static T_REGISTED_OBJECT ToEntity(this T_REGISTED_OBJECTDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_REGISTED_OBJECT();

            entity.OBJECT_ID = dto.OBJECT_ID;
            entity.APPLICATION_ID = dto.APPLICATION_ID;
            entity.TYPE_ID = dto.TYPE_ID;
            entity.QUICK_ACCESS = dto.QUICK_ACCESS;
            entity.OBJECT_TYPE = dto.OBJECT_TYPE;
            entity.COMMENT = dto.COMMENT;
            entity.ENUM_TYPE = dto.ENUM_TYPE;
            entity.OBJECT_NAME_ID = dto.OBJECT_NAME_ID;
            entity.OBJ_DATA_SRC = dto.OBJ_DATA_SRC;
            entity.IS_CHECKERROR_OBJ = dto.IS_CHECKERROR_OBJ;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_REGISTED_OBJECT"/> to an instance of <see cref="T_REGISTED_OBJECTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_REGISTED_OBJECT"/> to convert.</param>
        public static T_REGISTED_OBJECTDTO ToDTO(this T_REGISTED_OBJECT entity)
        {
            if (entity == null) return null;

            var dto = new T_REGISTED_OBJECTDTO();

            dto.OBJECT_ID = entity.OBJECT_ID;
            dto.APPLICATION_ID = entity.APPLICATION_ID;
            dto.TYPE_ID = entity.TYPE_ID;
            dto.QUICK_ACCESS = entity.QUICK_ACCESS;
            dto.OBJECT_TYPE = entity.OBJECT_TYPE;
            dto.COMMENT = entity.COMMENT;
            dto.ENUM_TYPE = entity.ENUM_TYPE;
            dto.OBJECT_NAME_ID = entity.OBJECT_NAME_ID;
            dto.OBJ_DATA_SRC = entity.OBJ_DATA_SRC;
            dto.IS_CHECKERROR_OBJ = entity.IS_CHECKERROR_OBJ;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_REGISTED_OBJECTDTO"/> to an instance of <see cref="T_REGISTED_OBJECT"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_REGISTED_OBJECT> ToEntities(this IEnumerable<T_REGISTED_OBJECTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_REGISTED_OBJECT"/> to an instance of <see cref="T_REGISTED_OBJECTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_REGISTED_OBJECTDTO> ToDTOs(this IEnumerable<T_REGISTED_OBJECT> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
