//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class T_SHARED_OBJECT_POOLDTO
    {
        [DataMember()]
        public Int64 OBJECT_POOL_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> DATA_SUMMARY_ID { get; set; }

        [DataMember()]
        public String OBJECT_NAME { get; set; }

        [DataMember()]
        public Nullable<Int64> OBJECT_ORDER { get; set; }

        [DataMember()]
        public Nullable<Int64> LOOP_ID { get; set; }

        [DataMember()]
        public String DATA_VALUE { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_TIME { get; set; }

        [DataMember()]
        public Nullable<Int64> VERSION { get; set; }

        [DataMember()]
        public Int64 T_TEST_DATA_SUMMARY_DATA_SUMMARY_ID { get; set; }

        public T_SHARED_OBJECT_POOLDTO()
        {
        }

        public T_SHARED_OBJECT_POOLDTO(Int64 oBJECT_POOL_ID, Nullable<Int64> dATA_SUMMARY_ID, String oBJECT_NAME, Nullable<Int64> oBJECT_ORDER, Nullable<Int64> lOOP_ID, String dATA_VALUE, Nullable<DateTime> cREATE_TIME, Nullable<Int64> vERSION, Int64 t_TEST_DATA_SUMMARY_DATA_SUMMARY_ID)
        {
			this.OBJECT_POOL_ID = oBJECT_POOL_ID;
			this.DATA_SUMMARY_ID = dATA_SUMMARY_ID;
			this.OBJECT_NAME = oBJECT_NAME;
			this.OBJECT_ORDER = oBJECT_ORDER;
			this.LOOP_ID = lOOP_ID;
			this.DATA_VALUE = dATA_VALUE;
			this.CREATE_TIME = cREATE_TIME;
			this.VERSION = vERSION;
			this.T_TEST_DATA_SUMMARY_DATA_SUMMARY_ID = t_TEST_DATA_SUMMARY_DATA_SUMMARY_ID;
        }
    }
}
