//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:14
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_STORYBOARD_HISTORY"/> and <see cref="T_STORYBOARD_HISTORYDTO"/>.
    /// </summary>
    public static partial class T_STORYBOARD_HISTORYAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_STORYBOARD_HISTORYDTO"/> converted from <see cref="T_STORYBOARD_HISTORY"/>.</param>
        static partial void OnDTO(this T_STORYBOARD_HISTORY entity, T_STORYBOARD_HISTORYDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_STORYBOARD_HISTORY"/> converted from <see cref="T_STORYBOARD_HISTORYDTO"/>.</param>
        static partial void OnEntity(this T_STORYBOARD_HISTORYDTO dto, T_STORYBOARD_HISTORY entity);

        /// <summary>
        /// Converts this instance of <see cref="T_STORYBOARD_HISTORYDTO"/> to an instance of <see cref="T_STORYBOARD_HISTORY"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_STORYBOARD_HISTORYDTO"/> to convert.</param>
        public static T_STORYBOARD_HISTORY ToEntity(this T_STORYBOARD_HISTORYDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_STORYBOARD_HISTORY();

            entity.DASHBOARD_HIST_ID = dto.DASHBOARD_HIST_ID;
            entity.STORYBOARD_ID = dto.STORYBOARD_ID;
            entity.VERION = dto.VERION;
            entity.CREATE_TIME = dto.CREATE_TIME;
            entity.CREATOR = dto.CREATOR;
            entity.STORYBOARD_NAME = dto.STORYBOARD_NAME;
            entity.ASSIGNED_PROJECT_ID = dto.ASSIGNED_PROJECT_ID;
            entity.DESCRIPTION = dto.DESCRIPTION;
            entity.HISTORY_CREATE_TIME = dto.HISTORY_CREATE_TIME;
            entity.REASON = dto.REASON;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_STORYBOARD_HISTORY"/> to an instance of <see cref="T_STORYBOARD_HISTORYDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_STORYBOARD_HISTORY"/> to convert.</param>
        public static T_STORYBOARD_HISTORYDTO ToDTO(this T_STORYBOARD_HISTORY entity)
        {
            if (entity == null) return null;

            var dto = new T_STORYBOARD_HISTORYDTO();

            dto.DASHBOARD_HIST_ID = entity.DASHBOARD_HIST_ID;
            dto.STORYBOARD_ID = entity.STORYBOARD_ID;
            dto.VERION = entity.VERION;
            dto.CREATE_TIME = entity.CREATE_TIME;
            dto.CREATOR = entity.CREATOR;
            dto.STORYBOARD_NAME = entity.STORYBOARD_NAME;
            dto.ASSIGNED_PROJECT_ID = entity.ASSIGNED_PROJECT_ID;
            dto.DESCRIPTION = entity.DESCRIPTION;
            dto.HISTORY_CREATE_TIME = entity.HISTORY_CREATE_TIME;
            dto.REASON = entity.REASON;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_STORYBOARD_HISTORYDTO"/> to an instance of <see cref="T_STORYBOARD_HISTORY"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_STORYBOARD_HISTORY> ToEntities(this IEnumerable<T_STORYBOARD_HISTORYDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_STORYBOARD_HISTORY"/> to an instance of <see cref="T_STORYBOARD_HISTORYDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_STORYBOARD_HISTORYDTO> ToDTOs(this IEnumerable<T_STORYBOARD_HISTORY> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
