//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class T_STORYBOARD_SUMMARYDTO
    {
        [DataMember()]
        public virtual Int64 STORYBOARD_ID { get; set; }

        [DataMember()]
        public virtual Nullable<DateTime> CREATE_TIME { get; set; }

        [DataMember()]
        public virtual Nullable<Decimal> LATEST_VERISON { get; set; }

        [DataMember()]
        public virtual String DESCRIPTION { get; set; }

        [DataMember()]
        public virtual Nullable<Int64> CREATER { get; set; }

        [DataMember()]
        public virtual Nullable<Int64> ASSIGNED_PROJECT_ID { get; set; }

        [DataMember()]
        public virtual String STORYBOARD_NAME { get; set; }

        [DataMember()]
        public List<Int64> T_PROJ_TC_MGR_STORYBOARD_DETAIL_ID { get; set; }

        [DataMember()]
        public List<Int64> T_STORYBOARD_HISTORY_DASHBOARD_HIST_ID { get; set; }

        public T_STORYBOARD_SUMMARYDTO()
        {
        }

        public T_STORYBOARD_SUMMARYDTO(Int64 sTORYBOARD_ID, Nullable<DateTime> cREATE_TIME, Nullable<Decimal> lATEST_VERISON, String dESCRIPTION, Nullable<Int64> cREATER, Nullable<Int64> aSSIGNED_PROJECT_ID, String sTORYBOARD_NAME, List<Int64> t_PROJ_TC_MGR_STORYBOARD_DETAIL_ID, List<Int64> t_STORYBOARD_HISTORY_DASHBOARD_HIST_ID)
        {
			this.STORYBOARD_ID = sTORYBOARD_ID;
			this.CREATE_TIME = cREATE_TIME;
			this.LATEST_VERISON = lATEST_VERISON;
			this.DESCRIPTION = dESCRIPTION;
			this.CREATER = cREATER;
			this.ASSIGNED_PROJECT_ID = aSSIGNED_PROJECT_ID;
			this.STORYBOARD_NAME = sTORYBOARD_NAME;
			this.T_PROJ_TC_MGR_STORYBOARD_DETAIL_ID = t_PROJ_TC_MGR_STORYBOARD_DETAIL_ID;
			this.T_STORYBOARD_HISTORY_DASHBOARD_HIST_ID = t_STORYBOARD_HISTORY_DASHBOARD_HIST_ID;
        }
    }
}
