//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:14
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_STORYBOARD_SUMMARY"/> and <see cref="T_STORYBOARD_SUMMARYDTO"/>.
    /// </summary>
    public static partial class T_STORYBOARD_SUMMARYAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_STORYBOARD_SUMMARYDTO"/> converted from <see cref="T_STORYBOARD_SUMMARY"/>.</param>
        static partial void OnDTO(this T_STORYBOARD_SUMMARY entity, T_STORYBOARD_SUMMARYDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_STORYBOARD_SUMMARY"/> converted from <see cref="T_STORYBOARD_SUMMARYDTO"/>.</param>
        static partial void OnEntity(this T_STORYBOARD_SUMMARYDTO dto, T_STORYBOARD_SUMMARY entity);

        /// <summary>
        /// Converts this instance of <see cref="T_STORYBOARD_SUMMARYDTO"/> to an instance of <see cref="T_STORYBOARD_SUMMARY"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_STORYBOARD_SUMMARYDTO"/> to convert.</param>
        public static T_STORYBOARD_SUMMARY ToEntity(this T_STORYBOARD_SUMMARYDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_STORYBOARD_SUMMARY();

            entity.STORYBOARD_ID = dto.STORYBOARD_ID;
            entity.CREATE_TIME = dto.CREATE_TIME;
            entity.LATEST_VERISON = dto.LATEST_VERISON;
            entity.DESCRIPTION = dto.DESCRIPTION;
            entity.CREATER = dto.CREATER;
            entity.ASSIGNED_PROJECT_ID = dto.ASSIGNED_PROJECT_ID;
            entity.STORYBOARD_NAME = dto.STORYBOARD_NAME;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_STORYBOARD_SUMMARY"/> to an instance of <see cref="T_STORYBOARD_SUMMARYDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_STORYBOARD_SUMMARY"/> to convert.</param>
        public static T_STORYBOARD_SUMMARYDTO ToDTO(this T_STORYBOARD_SUMMARY entity)
        {
            if (entity == null) return null;

            var dto = new T_STORYBOARD_SUMMARYDTO();

            dto.STORYBOARD_ID = entity.STORYBOARD_ID;
            dto.CREATE_TIME = entity.CREATE_TIME;
            dto.LATEST_VERISON = entity.LATEST_VERISON;
            dto.DESCRIPTION = entity.DESCRIPTION;
            dto.CREATER = entity.CREATER;
            dto.ASSIGNED_PROJECT_ID = entity.ASSIGNED_PROJECT_ID;
            dto.STORYBOARD_NAME = entity.STORYBOARD_NAME;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_STORYBOARD_SUMMARYDTO"/> to an instance of <see cref="T_STORYBOARD_SUMMARY"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_STORYBOARD_SUMMARY> ToEntities(this IEnumerable<T_STORYBOARD_SUMMARYDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_STORYBOARD_SUMMARY"/> to an instance of <see cref="T_STORYBOARD_SUMMARYDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_STORYBOARD_SUMMARYDTO> ToDTOs(this IEnumerable<T_STORYBOARD_SUMMARY> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
