//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class T_STORYBOARD_HISTORYDTO
    {
        [DataMember()]
        public Int64 DASHBOARD_HIST_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> STORYBOARD_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> VERION { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_TIME { get; set; }

        [DataMember()]
        public Nullable<Int64> CREATOR { get; set; }

        [DataMember()]
        public String STORYBOARD_NAME { get; set; }

        [DataMember()]
        public Nullable<Int64> ASSIGNED_PROJECT_ID { get; set; }

        [DataMember()]
        public String DESCRIPTION { get; set; }

        [DataMember()]
        public Nullable<DateTime> HISTORY_CREATE_TIME { get; set; }

        [DataMember()]
        public String REASON { get; set; }

        [DataMember()]
        public Int64 T_STORYBOARD_SUMMARY_STORYBOARD_ID { get; set; }

        public T_STORYBOARD_HISTORYDTO()
        {
        }

        public T_STORYBOARD_HISTORYDTO(Int64 dASHBOARD_HIST_ID, Nullable<Int64> sTORYBOARD_ID, Nullable<Int64> vERION, Nullable<DateTime> cREATE_TIME, Nullable<Int64> cREATOR, String sTORYBOARD_NAME, Nullable<Int64> aSSIGNED_PROJECT_ID, String dESCRIPTION, Nullable<DateTime> hISTORY_CREATE_TIME, String rEASON, Int64 t_STORYBOARD_SUMMARY_STORYBOARD_ID)
        {
			this.DASHBOARD_HIST_ID = dASHBOARD_HIST_ID;
			this.STORYBOARD_ID = sTORYBOARD_ID;
			this.VERION = vERION;
			this.CREATE_TIME = cREATE_TIME;
			this.CREATOR = cREATOR;
			this.STORYBOARD_NAME = sTORYBOARD_NAME;
			this.ASSIGNED_PROJECT_ID = aSSIGNED_PROJECT_ID;
			this.DESCRIPTION = dESCRIPTION;
			this.HISTORY_CREATE_TIME = hISTORY_CREATE_TIME;
			this.REASON = rEASON;
			this.T_STORYBOARD_SUMMARY_STORYBOARD_ID = t_STORYBOARD_SUMMARY_STORYBOARD_ID;
        }
    }
}
