//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class T_TEST_REPORTDTO
    {
        [DataMember()]
        public Int64 TEST_REPORT_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> TEST_CASE_ID { get; set; }

        [DataMember()]
        public Nullable<Decimal> LOOP_ID { get; set; }

        [DataMember()]
        public Nullable<DateTime> BEGIN_TIME { get; set; }

        [DataMember()]
        public Nullable<DateTime> END_TIME { get; set; }

        [DataMember()]
        public Nullable<Int16> RUNNING_RESULT { get; set; }

        [DataMember()]
        public String RETURN_VALUES { get; set; }

        [DataMember()]
        public String RUNNING_RESULT_INFO { get; set; }

        [DataMember()]
        public Nullable<Int64> HIST_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> APPLICATION_ID { get; set; }

        [DataMember()]
        public Nullable<Int16> TEST_MODE { get; set; }

        [DataMember()]
        public Int64 T_TEST_CASE_SUMMARY_TEST_CASE_ID { get; set; }

        [DataMember()]
        public List<Int64> T_TEST_REPORT_STEPS_TEST_REPORT_STEP_ID { get; set; }

        public T_TEST_REPORTDTO()
        {
        }

        public T_TEST_REPORTDTO(Int64 tEST_REPORT_ID, Nullable<Int64> tEST_CASE_ID, Nullable<Decimal> lOOP_ID, Nullable<DateTime> bEGIN_TIME, Nullable<DateTime> eND_TIME, Nullable<Int16> rUNNING_RESULT, String rETURN_VALUES, String rUNNING_RESULT_INFO, Nullable<Int64> hIST_ID, Nullable<Int64> aPPLICATION_ID, Nullable<Int16> tEST_MODE, Int64 t_TEST_CASE_SUMMARY_TEST_CASE_ID, List<Int64> t_TEST_REPORT_STEPS_TEST_REPORT_STEP_ID)
        {
			this.TEST_REPORT_ID = tEST_REPORT_ID;
			this.TEST_CASE_ID = tEST_CASE_ID;
			this.LOOP_ID = lOOP_ID;
			this.BEGIN_TIME = bEGIN_TIME;
			this.END_TIME = eND_TIME;
			this.RUNNING_RESULT = rUNNING_RESULT;
			this.RETURN_VALUES = rETURN_VALUES;
			this.RUNNING_RESULT_INFO = rUNNING_RESULT_INFO;
			this.HIST_ID = hIST_ID;
			this.APPLICATION_ID = aPPLICATION_ID;
			this.TEST_MODE = tEST_MODE;
			this.T_TEST_CASE_SUMMARY_TEST_CASE_ID = t_TEST_CASE_SUMMARY_TEST_CASE_ID;
			this.T_TEST_REPORT_STEPS_TEST_REPORT_STEP_ID = t_TEST_REPORT_STEPS_TEST_REPORT_STEP_ID;
        }
    }
}
