//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class T_TEST_CASE_VERSIONDTO
    {
        [DataMember()]
        public Int64 TC_VERSOIN_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> TEST_CASE_ID { get; set; }

        [DataMember()]
        public String VERSION_NAME { get; set; }

        [DataMember()]
        public String VERSION_DESC { get; set; }

        [DataMember()]
        public Nullable<Int64> VERSION_NUMBER { get; set; }

        [DataMember()]
        public Nullable<Int16> AVAILABLE_MARK { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_TIME { get; set; }

        [DataMember()]
        public Nullable<Int64> CREATOR_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_CASE_SUMMARY_TEST_CASE_ID { get; set; }

        public T_TEST_CASE_VERSIONDTO()
        {
        }

        public T_TEST_CASE_VERSIONDTO(Int64 tC_VERSOIN_ID, Nullable<Int64> tEST_CASE_ID, String vERSION_NAME, String vERSION_DESC, Nullable<Int64> vERSION_NUMBER, Nullable<Int16> aVAILABLE_MARK, Nullable<DateTime> cREATE_TIME, Nullable<Int64> cREATOR_ID, Int64 t_TEST_CASE_SUMMARY_TEST_CASE_ID)
        {
			this.TC_VERSOIN_ID = tC_VERSOIN_ID;
			this.TEST_CASE_ID = tEST_CASE_ID;
			this.VERSION_NAME = vERSION_NAME;
			this.VERSION_DESC = vERSION_DESC;
			this.VERSION_NUMBER = vERSION_NUMBER;
			this.AVAILABLE_MARK = aVAILABLE_MARK;
			this.CREATE_TIME = cREATE_TIME;
			this.CREATOR_ID = cREATOR_ID;
			this.T_TEST_CASE_SUMMARY_TEST_CASE_ID = t_TEST_CASE_SUMMARY_TEST_CASE_ID;
        }
    }
}
