//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class T_TEST_BATCH_DETAILDTO
    {
        [DataMember()]
        public virtual Int64 BAT_DTL_ID { get; set; }

        [DataMember()]
        public virtual Int64 BAT_ID { get; set; }

        [DataMember()]
        public virtual Int64 STORYOBARD_ID { get; set; }

        [DataMember()]
        public virtual String DTL_DESC { get; set; }

        [DataMember()]
        public virtual Int64 RUN_ORDER { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_TIME { get; set; }

        [DataMember()]
        public List<Int64> T_BAT_RESULT_DETAIL_BAT_RESULT_DTL_ID { get; set; }

        [DataMember()]
        public virtual Int64 T_TEST_BATCH_BAT_ID { get; set; }

        public T_TEST_BATCH_DETAILDTO()
        {
        }

        public T_TEST_BATCH_DETAILDTO(Int64 bAT_DTL_ID, Int64 bAT_ID, Int64 sTORYOBARD_ID, String dTL_DESC, Int64 rUN_ORDER, Nullable<DateTime> cREATE_TIME, List<Int64> t_BAT_RESULT_DETAIL_BAT_RESULT_DTL_ID, Int64 t_TEST_BATCH_BAT_ID)
        {
			this.BAT_DTL_ID = bAT_DTL_ID;
			this.BAT_ID = bAT_ID;
			this.STORYOBARD_ID = sTORYOBARD_ID;
			this.DTL_DESC = dTL_DESC;
			this.RUN_ORDER = rUN_ORDER;
			this.CREATE_TIME = cREATE_TIME;
			this.T_BAT_RESULT_DETAIL_BAT_RESULT_DTL_ID = t_BAT_RESULT_DETAIL_BAT_RESULT_DTL_ID;
			this.T_TEST_BATCH_BAT_ID = t_TEST_BATCH_BAT_ID;
        }
    }
}
