//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_TEST_PROJECT"/> and <see cref="T_TEST_PROJECTDTO"/>.
    /// </summary>
    public static partial class T_TEST_PROJECTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_PROJECTDTO"/> converted from <see cref="T_TEST_PROJECT"/>.</param>
        static partial void OnDTO(this T_TEST_PROJECT entity, T_TEST_PROJECTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_PROJECT"/> converted from <see cref="T_TEST_PROJECTDTO"/>.</param>
        static partial void OnEntity(this T_TEST_PROJECTDTO dto, T_TEST_PROJECT entity);

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_PROJECTDTO"/> to an instance of <see cref="T_TEST_PROJECT"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_PROJECTDTO"/> to convert.</param>
        public static T_TEST_PROJECT ToEntity(this T_TEST_PROJECTDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_TEST_PROJECT();

            entity.PROJECT_ID = dto.PROJECT_ID;
            entity.PROJECT_NAME = dto.PROJECT_NAME;
            entity.PROJECT_DESCRIPTION = dto.PROJECT_DESCRIPTION;
            entity.CREATOR = dto.CREATOR;
            entity.CREATE_DATE = dto.CREATE_DATE;
            entity.STATUS = dto.STATUS;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_PROJECT"/> to an instance of <see cref="T_TEST_PROJECTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_PROJECT"/> to convert.</param>
        public static T_TEST_PROJECTDTO ToDTO(this T_TEST_PROJECT entity)
        {
            if (entity == null) return null;

            var dto = new T_TEST_PROJECTDTO();

            dto.PROJECT_ID = entity.PROJECT_ID;
            dto.PROJECT_NAME = entity.PROJECT_NAME;
            dto.PROJECT_DESCRIPTION = entity.PROJECT_DESCRIPTION;
            dto.CREATOR = entity.CREATOR;
            dto.CREATE_DATE = entity.CREATE_DATE;
            dto.STATUS = entity.STATUS;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_PROJECTDTO"/> to an instance of <see cref="T_TEST_PROJECT"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_TEST_PROJECT> ToEntities(this IEnumerable<T_TEST_PROJECTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_PROJECT"/> to an instance of <see cref="T_TEST_PROJECTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_TEST_PROJECTDTO> ToDTOs(this IEnumerable<T_TEST_PROJECT> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
