//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:15
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_TEST_CASE_VERSION"/> and <see cref="T_TEST_CASE_VERSIONDTO"/>.
    /// </summary>
    public static partial class T_TEST_CASE_VERSIONAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_CASE_VERSIONDTO"/> converted from <see cref="T_TEST_CASE_VERSION"/>.</param>
        static partial void OnDTO(this T_TEST_CASE_VERSION entity, T_TEST_CASE_VERSIONDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_CASE_VERSION"/> converted from <see cref="T_TEST_CASE_VERSIONDTO"/>.</param>
        static partial void OnEntity(this T_TEST_CASE_VERSIONDTO dto, T_TEST_CASE_VERSION entity);

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_CASE_VERSIONDTO"/> to an instance of <see cref="T_TEST_CASE_VERSION"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_CASE_VERSIONDTO"/> to convert.</param>
        public static T_TEST_CASE_VERSION ToEntity(this T_TEST_CASE_VERSIONDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_TEST_CASE_VERSION();

            entity.TC_VERSOIN_ID = dto.TC_VERSOIN_ID;
            entity.TEST_CASE_ID = dto.TEST_CASE_ID;
            entity.VERSION_NAME = dto.VERSION_NAME;
            entity.VERSION_DESC = dto.VERSION_DESC;
            entity.VERSION_NUMBER = dto.VERSION_NUMBER;
            entity.AVAILABLE_MARK = dto.AVAILABLE_MARK;
            entity.CREATE_TIME = dto.CREATE_TIME;
            entity.CREATOR_ID = dto.CREATOR_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_CASE_VERSION"/> to an instance of <see cref="T_TEST_CASE_VERSIONDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_CASE_VERSION"/> to convert.</param>
        public static T_TEST_CASE_VERSIONDTO ToDTO(this T_TEST_CASE_VERSION entity)
        {
            if (entity == null) return null;

            var dto = new T_TEST_CASE_VERSIONDTO();

            dto.TC_VERSOIN_ID = entity.TC_VERSOIN_ID;
            dto.TEST_CASE_ID = entity.TEST_CASE_ID;
            dto.VERSION_NAME = entity.VERSION_NAME;
            dto.VERSION_DESC = entity.VERSION_DESC;
            dto.VERSION_NUMBER = entity.VERSION_NUMBER;
            dto.AVAILABLE_MARK = entity.AVAILABLE_MARK;
            dto.CREATE_TIME = entity.CREATE_TIME;
            dto.CREATOR_ID = entity.CREATOR_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_CASE_VERSIONDTO"/> to an instance of <see cref="T_TEST_CASE_VERSION"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_TEST_CASE_VERSION> ToEntities(this IEnumerable<T_TEST_CASE_VERSIONDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_CASE_VERSION"/> to an instance of <see cref="T_TEST_CASE_VERSIONDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_TEST_CASE_VERSIONDTO> ToDTOs(this IEnumerable<T_TEST_CASE_VERSION> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
