//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_TEST_STEPS"/> and <see cref="T_TEST_STEPSDTO"/>.
    /// </summary>
    public static partial class T_TEST_STEPSAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_STEPSDTO"/> converted from <see cref="T_TEST_STEPS"/>.</param>
        static partial void OnDTO(this T_TEST_STEPS entity, T_TEST_STEPSDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_STEPS"/> converted from <see cref="T_TEST_STEPSDTO"/>.</param>
        static partial void OnEntity(this T_TEST_STEPSDTO dto, T_TEST_STEPS entity);

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_STEPSDTO"/> to an instance of <see cref="T_TEST_STEPS"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_STEPSDTO"/> to convert.</param>
        public static T_TEST_STEPS ToEntity(this T_TEST_STEPSDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_TEST_STEPS();

            entity.STEPS_ID = dto.STEPS_ID;
            entity.RUN_ORDER = dto.RUN_ORDER;
            entity.KEY_WORD_ID = dto.KEY_WORD_ID;
            entity.TEST_CASE_ID = dto.TEST_CASE_ID;
            entity.OBJECT_ID = dto.OBJECT_ID;
            entity.COLUMN_ROW_SETTING = dto.COLUMN_ROW_SETTING;
            entity.VALUE_SETTING = dto.VALUE_SETTING;
            entity.COMMENT = dto.COMMENT;
            entity.IS_RUNNABLE = dto.IS_RUNNABLE;
            entity.OBJECT_NAME_ID = dto.OBJECT_NAME_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_STEPS"/> to an instance of <see cref="T_TEST_STEPSDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_STEPS"/> to convert.</param>
        public static T_TEST_STEPSDTO ToDTO(this T_TEST_STEPS entity)
        {
            if (entity == null) return null;

            var dto = new T_TEST_STEPSDTO();

            dto.STEPS_ID = entity.STEPS_ID;
            dto.RUN_ORDER = entity.RUN_ORDER;
            dto.KEY_WORD_ID = entity.KEY_WORD_ID;
            dto.TEST_CASE_ID = entity.TEST_CASE_ID;
            dto.OBJECT_ID = entity.OBJECT_ID;
            dto.COLUMN_ROW_SETTING = entity.COLUMN_ROW_SETTING;
            dto.VALUE_SETTING = entity.VALUE_SETTING;
            dto.COMMENT = entity.COMMENT;
            dto.IS_RUNNABLE = entity.IS_RUNNABLE;
            dto.OBJECT_NAME_ID = entity.OBJECT_NAME_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_STEPSDTO"/> to an instance of <see cref="T_TEST_STEPS"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_TEST_STEPS> ToEntities(this IEnumerable<T_TEST_STEPSDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_STEPS"/> to an instance of <see cref="T_TEST_STEPSDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_TEST_STEPSDTO> ToDTOs(this IEnumerable<T_TEST_STEPS> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
