//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [Serializable]
    [DataContract()]
    public partial class T_TEST_REPORT_STEPSDTO
    {
        [DataMember()]
        public Int64 TEST_REPORT_STEP_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> TEST_REPORT_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> STEPS_ID { get; set; }

        [DataMember()]
        public Nullable<DateTime> BEGIN_TIME { get; set; }

        [DataMember()]
        public Nullable<DateTime> END_TIME { get; set; }

        [DataMember()]
        public Nullable<Int16> RUNNING_RESULT { get; set; }

        [DataMember()]
        public String RETURN_VALUES { get; set; }

        [DataMember()]
        public String RUNNING_RESULT_INFO { get; set; }

        [DataMember()]
        public Nullable<Int64> DATA_SUMMARY_ID { get; set; }

        [DataMember()]
        public String INPUT_VALUE_SETTING { get; set; }

        [DataMember()]
        public String ACTUAL_INPUT_DATA { get; set; }

        [DataMember()]
        public Nullable<Int64> DATA_ORDER { get; set; }

        [DataMember()]
        public Byte[] INFO_PIC { get; set; }
        [DataMember]
        public string ADVICE { get; set; }
        [DataMember]
        public string STACKINFO { get; set; }

        [DataMember()]
        public Int64 T_TEST_REPORT_TEST_REPORT_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_STEPS_STEPS_ID { get; set; }

        public T_TEST_REPORT_STEPSDTO()
        {
        }

        public T_TEST_REPORT_STEPSDTO(Int64 tEST_REPORT_STEP_ID, Nullable<Int64> tEST_REPORT_ID, Nullable<Int64> sTEPS_ID, Nullable<DateTime> bEGIN_TIME, 
            Nullable<DateTime> eND_TIME, Nullable<Int16> rUNNING_RESULT, String rETURN_VALUES, String rUNNING_RESULT_INFO, Nullable<Int64> dATA_SUMMARY_ID,
            String iNPUT_VALUE_SETTING, String aCTUAL_INPUT_DATA, Nullable<Int64> dATA_ORDER, Byte[] iNFO_PIC, Int64 t_TEST_REPORT_TEST_REPORT_ID, Int64 t_TEST_STEPS_STEPS_ID,
            string aDVICE, string sTACKINFO)
        {
			this.TEST_REPORT_STEP_ID = tEST_REPORT_STEP_ID;
			this.TEST_REPORT_ID = tEST_REPORT_ID;
			this.STEPS_ID = sTEPS_ID;
			this.BEGIN_TIME = bEGIN_TIME;
			this.END_TIME = eND_TIME;
			this.RUNNING_RESULT = rUNNING_RESULT;
			this.RETURN_VALUES = rETURN_VALUES;
			this.RUNNING_RESULT_INFO = rUNNING_RESULT_INFO;
			this.DATA_SUMMARY_ID = dATA_SUMMARY_ID;
			this.INPUT_VALUE_SETTING = iNPUT_VALUE_SETTING;
			this.ACTUAL_INPUT_DATA = aCTUAL_INPUT_DATA;
			this.DATA_ORDER = dATA_ORDER;
			this.INFO_PIC = iNFO_PIC;
			this.T_TEST_REPORT_TEST_REPORT_ID = t_TEST_REPORT_TEST_REPORT_ID;
			this.T_TEST_STEPS_STEPS_ID = t_TEST_STEPS_STEPS_ID;
            this.ADVICE = aDVICE;
            this.STACKINFO = sTACKINFO;
        }
    }
}
