//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:47
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class T_TESTER_INFODTO
    {
        [DataMember()]
        public Decimal TESTER_ID { get; set; }

        [DataMember()]
        public String TESTER_NAME_LAST { get; set; }

        [DataMember()]
        public String TESTER_NAME_M { get; set; }

        [DataMember()]
        public String TESTER_NAME_F { get; set; }

        [DataMember()]
        public String TESTER_LOGIN_NAME { get; set; }

        [DataMember()]
        public String TESTER_PWD { get; set; }

        [DataMember()]
        public Nullable<Decimal> AVAILABLE_MARK { get; set; }

        [DataMember()]
        public String TESTER_MAIL { get; set; }

        [DataMember()]
        public String TESTER_NUMBER { get; set; }

        [DataMember()]
        public Decimal COMPANY_ID { get; set; }

        [DataMember()]
        public String CREATOR_NAME { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_TIME { get; set; }

        [DataMember()]
        public String TESTER_DESC { get; set; }

        [DataMember()]
        public Decimal T_MARS_COMPANY_COMPANY_ID { get; set; }

        public T_TESTER_INFODTO()
        {
        }

        public T_TESTER_INFODTO(Decimal tESTER_ID, String tESTER_NAME_LAST, String tESTER_NAME_M, String tESTER_NAME_F, String tESTER_LOGIN_NAME, String tESTER_PWD, Nullable<Decimal> aVAILABLE_MARK, String tESTER_MAIL, String tESTER_NUMBER, Decimal cOMPANY_ID, String cREATOR_NAME, Nullable<DateTime> cREATE_TIME, String tESTER_DESC, Decimal t_MARS_COMPANY_COMPANY_ID)
        {
			this.TESTER_ID = tESTER_ID;
			this.TESTER_NAME_LAST = tESTER_NAME_LAST;
			this.TESTER_NAME_M = tESTER_NAME_M;
			this.TESTER_NAME_F = tESTER_NAME_F;
			this.TESTER_LOGIN_NAME = tESTER_LOGIN_NAME;
			this.TESTER_PWD = tESTER_PWD;
			this.AVAILABLE_MARK = aVAILABLE_MARK;
			this.TESTER_MAIL = tESTER_MAIL;
			this.TESTER_NUMBER = tESTER_NUMBER;
			this.COMPANY_ID = cOMPANY_ID;
			this.CREATOR_NAME = cREATOR_NAME;
			this.CREATE_TIME = cREATE_TIME;
			this.TESTER_DESC = tESTER_DESC;
			this.T_MARS_COMPANY_COMPANY_ID = t_MARS_COMPANY_COMPANY_ID;
        }
    }
}
