//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:07
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="TEST_DATA_SETTING"/> and <see cref="TEST_DATA_SETTINGDTO"/>.
    /// </summary>
    public static partial class TEST_DATA_SETTINGAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="TEST_DATA_SETTINGDTO"/> converted from <see cref="TEST_DATA_SETTING"/>.</param>
        static partial void OnDTO(this TEST_DATA_SETTING entity, TEST_DATA_SETTINGDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="TEST_DATA_SETTING"/> converted from <see cref="TEST_DATA_SETTINGDTO"/>.</param>
        static partial void OnEntity(this TEST_DATA_SETTINGDTO dto, TEST_DATA_SETTING entity);

        /// <summary>
        /// Converts this instance of <see cref="TEST_DATA_SETTINGDTO"/> to an instance of <see cref="TEST_DATA_SETTING"/>.
        /// </summary>
        /// <param name="dto"><see cref="TEST_DATA_SETTINGDTO"/> to convert.</param>
        public static TEST_DATA_SETTING ToEntity(this TEST_DATA_SETTINGDTO dto)
        {
            if (dto == null) return null;

            var entity = new TEST_DATA_SETTING();

            entity.DATA_SETTING_ID = dto.DATA_SETTING_ID;
            entity.STEPS_ID = dto.STEPS_ID;
            entity.LOOP_ID = dto.LOOP_ID;
            entity.DATA_VALUE = dto.DATA_VALUE;
            entity.VALUE_OR_OBJECT = dto.VALUE_OR_OBJECT;
            entity.DESCRIPTION = dto.DESCRIPTION;
            entity.DATA_SUMMARY_ID = dto.DATA_SUMMARY_ID;
            entity.DATA_DIRECTION = dto.DATA_DIRECTION;
            entity.VERSION = dto.VERSION;
            entity.CREATE_TIME = dto.CREATE_TIME;
            entity.POOL_ID = dto.POOL_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="TEST_DATA_SETTING"/> to an instance of <see cref="TEST_DATA_SETTINGDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="TEST_DATA_SETTING"/> to convert.</param>
        public static TEST_DATA_SETTINGDTO ToDTO(this TEST_DATA_SETTING entity)
        {
            if (entity == null) return null;

            var dto = new TEST_DATA_SETTINGDTO();

            dto.DATA_SETTING_ID = entity.DATA_SETTING_ID;
            dto.STEPS_ID = entity.STEPS_ID;
            dto.LOOP_ID = entity.LOOP_ID;
            dto.DATA_VALUE = entity.DATA_VALUE;
            dto.VALUE_OR_OBJECT = entity.VALUE_OR_OBJECT;
            dto.DESCRIPTION = entity.DESCRIPTION;
            dto.DATA_SUMMARY_ID = entity.DATA_SUMMARY_ID;
            dto.DATA_DIRECTION = entity.DATA_DIRECTION;
            dto.VERSION = entity.VERSION;
            dto.CREATE_TIME = entity.CREATE_TIME;
            dto.POOL_ID = entity.POOL_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="TEST_DATA_SETTINGDTO"/> to an instance of <see cref="TEST_DATA_SETTING"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<TEST_DATA_SETTING> ToEntities(this IEnumerable<TEST_DATA_SETTINGDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="TEST_DATA_SETTING"/> to an instance of <see cref="TEST_DATA_SETTINGDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<TEST_DATA_SETTINGDTO> ToDTOs(this IEnumerable<TEST_DATA_SETTING> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
