//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:03
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class TEST_DATA_SETTINGDTO
    {
        [DataMember()]
        public Int64 DATA_SETTING_ID { get; set; }

        [DataMember()]
        public Int64 STEPS_ID { get; set; }

        [DataMember()]
        public Nullable<Decimal> LOOP_ID { get; set; }

        [DataMember()]
        public String DATA_VALUE { get; set; }

        [DataMember()]
        public Nullable<Int16> VALUE_OR_OBJECT { get; set; }

        [DataMember()]
        public String DESCRIPTION { get; set; }

        [DataMember()]
        public Nullable<Int64> DATA_SUMMARY_ID { get; set; }

        [DataMember()]
        public Nullable<Int16> DATA_DIRECTION { get; set; }

        [DataMember()]
        public Nullable<Int64> VERSION { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_TIME { get; set; }

        [DataMember()]
        public Nullable<Int64> POOL_ID { get; set; }

        [DataMember()]
        public string? API_RUNTIME_CONFIG { get; set; }

        [DataMember()]
        public Int64 T_TEST_STEPS_STEPS_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_DATA_SUMMARY_DATA_SUMMARY_ID { get; set; }

        public TEST_DATA_SETTINGDTO()
        {
        }

        public TEST_DATA_SETTINGDTO(Int64 dATA_SETTING_ID, Int64 sTEPS_ID, Nullable<Decimal> lOOP_ID, String dATA_VALUE, Nullable<Int16> vALUE_OR_OBJECT, String dESCRIPTION, Nullable<Int64> dATA_SUMMARY_ID, Nullable<Int16> dATA_DIRECTION, Nullable<Int64> vERSION, Nullable<DateTime> cREATE_TIME, Nullable<Int64> pOOL_ID, Int64 t_TEST_STEPS_STEPS_ID, Int64 t_TEST_DATA_SUMMARY_DATA_SUMMARY_ID)
        {
			this.DATA_SETTING_ID = dATA_SETTING_ID;
			this.STEPS_ID = sTEPS_ID;
			this.LOOP_ID = lOOP_ID;
			this.DATA_VALUE = dATA_VALUE;
			this.VALUE_OR_OBJECT = vALUE_OR_OBJECT;
			this.DESCRIPTION = dESCRIPTION;
			this.DATA_SUMMARY_ID = dATA_SUMMARY_ID;
			this.DATA_DIRECTION = dATA_DIRECTION;
			this.VERSION = vERSION;
			this.CREATE_TIME = cREATE_TIME;
			this.POOL_ID = pOOL_ID;
			this.T_TEST_STEPS_STEPS_ID = t_TEST_STEPS_STEPS_ID;
			this.T_TEST_DATA_SUMMARY_DATA_SUMMARY_ID = t_TEST_DATA_SUMMARY_DATA_SUMMARY_ID;
        }
    }
}
