//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:16
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="V_BASE_LINEDATA"/> and <see cref="V_BASE_LINEDATADTO"/>.
    /// </summary>
    public static partial class V_BASE_LINEDATAAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="V_BASE_LINEDATADTO"/> converted from <see cref="V_BASE_LINEDATA"/>.</param>
        static partial void OnDTO(this V_BASE_LINEDATA entity, V_BASE_LINEDATADTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="V_BASE_LINEDATA"/> converted from <see cref="V_BASE_LINEDATADTO"/>.</param>
        static partial void OnEntity(this V_BASE_LINEDATADTO dto, V_BASE_LINEDATA entity);

        /// <summary>
        /// Converts this instance of <see cref="V_BASE_LINEDATADTO"/> to an instance of <see cref="V_BASE_LINEDATA"/>.
        /// </summary>
        /// <param name="dto"><see cref="V_BASE_LINEDATADTO"/> to convert.</param>
        public static V_BASE_LINEDATA ToEntity(this V_BASE_LINEDATADTO dto)
        {
            if (dto == null) return null;

            var entity = new V_BASE_LINEDATA();

            entity.DATA_SUMMARY_ID = dto.DATA_SUMMARY_ID;
            entity.OBJECT_HAPPY_NAME = dto.OBJECT_HAPPY_NAME;
            entity.LOOP_ID = dto.LOOP_ID;
            entity.DATA_VALUE = dto.DATA_VALUE;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="V_BASE_LINEDATA"/> to an instance of <see cref="V_BASE_LINEDATADTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="V_BASE_LINEDATA"/> to convert.</param>
        public static V_BASE_LINEDATADTO ToDTO(this V_BASE_LINEDATA entity)
        {
            if (entity == null) return null;

            var dto = new V_BASE_LINEDATADTO();

            dto.DATA_SUMMARY_ID = entity.DATA_SUMMARY_ID;
            dto.OBJECT_HAPPY_NAME = entity.OBJECT_HAPPY_NAME;
            dto.LOOP_ID = entity.LOOP_ID;
            dto.DATA_VALUE = entity.DATA_VALUE;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="V_BASE_LINEDATADTO"/> to an instance of <see cref="V_BASE_LINEDATA"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<V_BASE_LINEDATA> ToEntities(this IEnumerable<V_BASE_LINEDATADTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="V_BASE_LINEDATA"/> to an instance of <see cref="V_BASE_LINEDATADTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<V_BASE_LINEDATADTO> ToDTOs(this IEnumerable<V_BASE_LINEDATA> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
