//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:36
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class V_BASE_LINEDATADTO
    {
        [DataMember()]
        public Int16 DATA_SUMMARY_ID { get; set; }

        [DataMember()]
        public String OBJECT_HAPPY_NAME { get; set; }

        [DataMember()]
        public Int16 LOOP_ID { get; set; }

        [DataMember()]
        public String DATA_VALUE { get; set; }

        public V_BASE_LINEDATADTO()
        {
        }

        public V_BASE_LINEDATADTO(Int16 dATA_SUMMARY_ID, String oBJECT_HAPPY_NAME, Int16 lOOP_ID, String dATA_VALUE)
        {
			this.DATA_SUMMARY_ID = dATA_SUMMARY_ID;
			this.OBJECT_HAPPY_NAME = oBJECT_HAPPY_NAME;
			this.LOOP_ID = lOOP_ID;
			this.DATA_VALUE = dATA_VALUE;
        }
    }
}
