//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:17
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="V_OBJECT_APPS"/> and <see cref="V_OBJECT_APPSDTO"/>.
    /// </summary>
    public static partial class V_OBJECT_APPSAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="V_OBJECT_APPSDTO"/> converted from <see cref="V_OBJECT_APPS"/>.</param>
        static partial void OnDTO(this V_OBJECT_APPS entity, V_OBJECT_APPSDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="V_OBJECT_APPS"/> converted from <see cref="V_OBJECT_APPSDTO"/>.</param>
        static partial void OnEntity(this V_OBJECT_APPSDTO dto, V_OBJECT_APPS entity);

        /// <summary>
        /// Converts this instance of <see cref="V_OBJECT_APPSDTO"/> to an instance of <see cref="V_OBJECT_APPS"/>.
        /// </summary>
        /// <param name="dto"><see cref="V_OBJECT_APPSDTO"/> to convert.</param>
        public static V_OBJECT_APPS ToEntity(this V_OBJECT_APPSDTO dto)
        {
            if (dto == null) return null;

            var entity = new V_OBJECT_APPS();

            entity.APPLICATION_ID = dto.APPLICATION_ID;
            entity.OBJECT_ID = dto.OBJECT_ID;
            entity.COMMENT = dto.COMMENT;
            entity.ENUM_TYPE = dto.ENUM_TYPE;
            entity.OBJECT_HAPPY_NAME = dto.OBJECT_HAPPY_NAME;
            entity.OBJECT_TYPE = dto.OBJECT_TYPE;
            entity.QUICK_ACCESS = dto.QUICK_ACCESS;
            entity.TYPE_ID = dto.TYPE_ID;
            entity.APP_APPLICATION_ID = dto.APP_APPLICATION_ID;
            entity.APP_SHORT_NAME = dto.APP_SHORT_NAME;
            entity.APPLICATION_TYPE_ID = dto.APPLICATION_TYPE_ID;
            entity.COMMENT_APP = dto.COMMENT_APP;
            entity.EXTRAPOPUPMENU = dto.EXTRAPOPUPMENU;
            entity.EXTRAREQUIREMENT = dto.EXTRAREQUIREMENT;
            entity.PROCESS_IDENTIFIER = dto.PROCESS_IDENTIFIER;
            entity.STARTER_COMMAND = dto.STARTER_COMMAND;
            entity.STARTER_PATH = dto.STARTER_PATH;
            entity.VERSION = dto.VERSION;
            entity.TYPE_APPLICATION_TYPE_ID = dto.TYPE_APPLICATION_TYPE_ID;
            entity.TYPE_DESCRPTION = dto.TYPE_DESCRPTION;
            entity.TYP_TYPE_ID = dto.TYP_TYPE_ID;
            entity.TYPE_NAME = dto.TYPE_NAME;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="V_OBJECT_APPS"/> to an instance of <see cref="V_OBJECT_APPSDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="V_OBJECT_APPS"/> to convert.</param>
        public static V_OBJECT_APPSDTO ToDTO(this V_OBJECT_APPS entity)
        {
            if (entity == null) return null;

            var dto = new V_OBJECT_APPSDTO();

            dto.APPLICATION_ID = entity.APPLICATION_ID;
            dto.OBJECT_ID = entity.OBJECT_ID;
            dto.COMMENT = entity.COMMENT;
            dto.ENUM_TYPE = entity.ENUM_TYPE;
            dto.OBJECT_HAPPY_NAME = entity.OBJECT_HAPPY_NAME;
            dto.OBJECT_TYPE = entity.OBJECT_TYPE;
            dto.QUICK_ACCESS = entity.QUICK_ACCESS;
            dto.TYPE_ID = entity.TYPE_ID;
            dto.APP_APPLICATION_ID = entity.APP_APPLICATION_ID;
            dto.APP_SHORT_NAME = entity.APP_SHORT_NAME;
            dto.APPLICATION_TYPE_ID = entity.APPLICATION_TYPE_ID;
            dto.COMMENT_APP = entity.COMMENT_APP;
            dto.EXTRAPOPUPMENU = entity.EXTRAPOPUPMENU;
            dto.EXTRAREQUIREMENT = entity.EXTRAREQUIREMENT;
            dto.PROCESS_IDENTIFIER = entity.PROCESS_IDENTIFIER;
            dto.STARTER_COMMAND = entity.STARTER_COMMAND;
            dto.STARTER_PATH = entity.STARTER_PATH;
            dto.VERSION = entity.VERSION;
            dto.TYPE_APPLICATION_TYPE_ID = entity.TYPE_APPLICATION_TYPE_ID;
            dto.TYPE_DESCRPTION = entity.TYPE_DESCRPTION;
            dto.TYP_TYPE_ID = entity.TYP_TYPE_ID;
            dto.TYPE_NAME = entity.TYPE_NAME;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="V_OBJECT_APPSDTO"/> to an instance of <see cref="V_OBJECT_APPS"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<V_OBJECT_APPS> ToEntities(this IEnumerable<V_OBJECT_APPSDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="V_OBJECT_APPS"/> to an instance of <see cref="V_OBJECT_APPSDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<V_OBJECT_APPSDTO> ToDTOs(this IEnumerable<V_OBJECT_APPS> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
