//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:17
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="V_OBJECT_SNAPSHOT"/> and <see cref="V_OBJECT_SNAPSHOTDTO"/>.
    /// </summary>
    public static partial class V_OBJECT_SNAPSHOTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="V_OBJECT_SNAPSHOTDTO"/> converted from <see cref="V_OBJECT_SNAPSHOT"/>.</param>
        static partial void OnDTO(this V_OBJECT_SNAPSHOT entity, V_OBJECT_SNAPSHOTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="V_OBJECT_SNAPSHOT"/> converted from <see cref="V_OBJECT_SNAPSHOTDTO"/>.</param>
        static partial void OnEntity(this V_OBJECT_SNAPSHOTDTO dto, V_OBJECT_SNAPSHOT entity);

        /// <summary>
        /// Converts this instance of <see cref="V_OBJECT_SNAPSHOTDTO"/> to an instance of <see cref="V_OBJECT_SNAPSHOT"/>.
        /// </summary>
        /// <param name="dto"><see cref="V_OBJECT_SNAPSHOTDTO"/> to convert.</param>
        public static V_OBJECT_SNAPSHOT ToEntity(this V_OBJECT_SNAPSHOTDTO dto)
        {
            if (dto == null) return null;

            var entity = new V_OBJECT_SNAPSHOT();

            entity.OBJECT_NAME_ID = dto.OBJECT_NAME_ID;
            entity.OBJECT_HAPPY_NAME = dto.OBJECT_HAPPY_NAME;
            entity.COMMENT = dto.COMMENT;
            entity.APPLICATION_ID = dto.APPLICATION_ID;
            entity.ENUM_TYPE = dto.ENUM_TYPE;
            entity.OBJECT_ID = dto.OBJECT_ID;
            entity.OBJECT_TYPE = dto.OBJECT_TYPE;
            entity.QUICK_ACCESS = dto.QUICK_ACCESS;
            entity.TYPE_ID = dto.TYPE_ID;
            entity.TYPE_NAME = dto.TYPE_NAME;
            entity.PEG_NAME = dto.PEG_NAME;
            entity.PEG_QUICK_ACCESS = dto.PEG_QUICK_ACCESS;
            entity.PEG_ID = dto.PEG_ID;
            entity.IS_CHECKERROR_OBJ = dto.IS_CHECKERROR_OBJ;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="V_OBJECT_SNAPSHOT"/> to an instance of <see cref="V_OBJECT_SNAPSHOTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="V_OBJECT_SNAPSHOT"/> to convert.</param>
        public static V_OBJECT_SNAPSHOTDTO ToDTO(this V_OBJECT_SNAPSHOT entity)
        {
            if (entity == null) return null;

            var dto = new V_OBJECT_SNAPSHOTDTO();

            dto.OBJECT_NAME_ID = entity.OBJECT_NAME_ID;
            dto.OBJECT_HAPPY_NAME = entity.OBJECT_HAPPY_NAME;
            dto.COMMENT = entity.COMMENT;
            dto.APPLICATION_ID = entity.APPLICATION_ID;
            dto.ENUM_TYPE = entity.ENUM_TYPE;
            dto.OBJECT_ID = entity.OBJECT_ID;
            dto.OBJECT_TYPE = entity.OBJECT_TYPE;
            dto.QUICK_ACCESS = entity.QUICK_ACCESS;
            dto.TYPE_ID = entity.TYPE_ID;
            dto.TYPE_NAME = entity.TYPE_NAME;
            dto.PEG_NAME = entity.PEG_NAME;
            dto.PEG_QUICK_ACCESS = entity.PEG_QUICK_ACCESS;
            dto.PEG_ID = entity.PEG_ID;
            dto.IS_CHECKERROR_OBJ = entity.IS_CHECKERROR_OBJ;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="V_OBJECT_SNAPSHOTDTO"/> to an instance of <see cref="V_OBJECT_SNAPSHOT"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<V_OBJECT_SNAPSHOT> ToEntities(this IEnumerable<V_OBJECT_SNAPSHOTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="V_OBJECT_SNAPSHOT"/> to an instance of <see cref="V_OBJECT_SNAPSHOTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<V_OBJECT_SNAPSHOTDTO> ToDTOs(this IEnumerable<V_OBJECT_SNAPSHOT> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
