//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:37
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class V_OBJECT_APPSDTO
    {
        [DataMember()]
        public Nullable<Int64> APPLICATION_ID { get; set; }

        [DataMember()]
        public Int64 OBJECT_ID { get; set; }

        [DataMember()]
        public String COMMENT { get; set; }

        [DataMember()]
        public String ENUM_TYPE { get; set; }

        [DataMember()]
        public String OBJECT_HAPPY_NAME { get; set; }

        [DataMember()]
        public String OBJECT_TYPE { get; set; }

        [DataMember()]
        public String QUICK_ACCESS { get; set; }

        [DataMember()]
        public Nullable<Int64> TYPE_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> APP_APPLICATION_ID { get; set; }

        [DataMember()]
        public String APP_SHORT_NAME { get; set; }

        [DataMember()]
        public Nullable<Int16> APPLICATION_TYPE_ID { get; set; }

        [DataMember()]
        public String COMMENT_APP { get; set; }

        [DataMember()]
        public String EXTRAPOPUPMENU { get; set; }

        [DataMember()]
        public String EXTRAREQUIREMENT { get; set; }

        [DataMember()]
        public String PROCESS_IDENTIFIER { get; set; }

        [DataMember()]
        public String STARTER_COMMAND { get; set; }

        [DataMember()]
        public String STARTER_PATH { get; set; }

        [DataMember()]
        public String VERSION { get; set; }

        [DataMember()]
        public Nullable<Int16> TYPE_APPLICATION_TYPE_ID { get; set; }

        [DataMember()]
        public String TYPE_DESCRPTION { get; set; }

        [DataMember()]
        public Nullable<Int64> TYP_TYPE_ID { get; set; }

        [DataMember()]
        public String TYPE_NAME { get; set; }

        public V_OBJECT_APPSDTO()
        {
        }

        public V_OBJECT_APPSDTO(Nullable<Int64> aPPLICATION_ID, Int64 oBJECT_ID, String cOMMENT, String eNUM_TYPE, String oBJECT_HAPPY_NAME, String oBJECT_TYPE, String qUICK_ACCESS, Nullable<Int64> tYPE_ID, Nullable<Int64> aPP_APPLICATION_ID, String aPP_SHORT_NAME, Nullable<Int16> aPPLICATION_TYPE_ID, String cOMMENT_APP, String eXTRAPOPUPMENU, String eXTRAREQUIREMENT, String pROCESS_IDENTIFIER, String sTARTER_COMMAND, String sTARTER_PATH, String vERSION, Nullable<Int16> tYPE_APPLICATION_TYPE_ID, String tYPE_DESCRPTION, Nullable<Int64> tYP_TYPE_ID, String tYPE_NAME)
        {
			this.APPLICATION_ID = aPPLICATION_ID;
			this.OBJECT_ID = oBJECT_ID;
			this.COMMENT = cOMMENT;
			this.ENUM_TYPE = eNUM_TYPE;
			this.OBJECT_HAPPY_NAME = oBJECT_HAPPY_NAME;
			this.OBJECT_TYPE = oBJECT_TYPE;
			this.QUICK_ACCESS = qUICK_ACCESS;
			this.TYPE_ID = tYPE_ID;
			this.APP_APPLICATION_ID = aPP_APPLICATION_ID;
			this.APP_SHORT_NAME = aPP_SHORT_NAME;
			this.APPLICATION_TYPE_ID = aPPLICATION_TYPE_ID;
			this.COMMENT_APP = cOMMENT_APP;
			this.EXTRAPOPUPMENU = eXTRAPOPUPMENU;
			this.EXTRAREQUIREMENT = eXTRAREQUIREMENT;
			this.PROCESS_IDENTIFIER = pROCESS_IDENTIFIER;
			this.STARTER_COMMAND = sTARTER_COMMAND;
			this.STARTER_PATH = sTARTER_PATH;
			this.VERSION = vERSION;
			this.TYPE_APPLICATION_TYPE_ID = tYPE_APPLICATION_TYPE_ID;
			this.TYPE_DESCRPTION = tYPE_DESCRPTION;
			this.TYP_TYPE_ID = tYP_TYPE_ID;
			this.TYPE_NAME = tYPE_NAME;
        }
    }
}
