//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="V_PROJ_TS_TC_FULLVISION"/> and <see cref="V_PROJ_TS_TC_FULLVISIONDTO"/>.
    /// </summary>
    public static partial class V_PROJ_TS_TC_FULLVISIONAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="V_PROJ_TS_TC_FULLVISIONDTO"/> converted from <see cref="V_PROJ_TS_TC_FULLVISION"/>.</param>
        static partial void OnDTO(this V_PROJ_TS_TC_FULLVISION entity, V_PROJ_TS_TC_FULLVISIONDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="V_PROJ_TS_TC_FULLVISION"/> converted from <see cref="V_PROJ_TS_TC_FULLVISIONDTO"/>.</param>
        static partial void OnEntity(this V_PROJ_TS_TC_FULLVISIONDTO dto, V_PROJ_TS_TC_FULLVISION entity);

        /// <summary>
        /// Converts this instance of <see cref="V_PROJ_TS_TC_FULLVISIONDTO"/> to an instance of <see cref="V_PROJ_TS_TC_FULLVISION"/>.
        /// </summary>
        /// <param name="dto"><see cref="V_PROJ_TS_TC_FULLVISIONDTO"/> to convert.</param>
        public static V_PROJ_TS_TC_FULLVISION ToEntity(this V_PROJ_TS_TC_FULLVISIONDTO dto)
        {
            if (dto == null) return null;

            var entity = new V_PROJ_TS_TC_FULLVISION();

            entity.TEST_SUITE_ID = dto.TEST_SUITE_ID;
            entity.TEST_SUITE_NAME = dto.TEST_SUITE_NAME;
            entity.TEST_SUITE_DESCRIPTION = dto.TEST_SUITE_DESCRIPTION;
            entity.TEST_CASE_ID = dto.TEST_CASE_ID;
            entity.TEST_CASE_NAME = dto.TEST_CASE_NAME;
            entity.TEST_STEP_CREATE_TIME = dto.TEST_STEP_CREATE_TIME;
            entity.TEST_STEP_CREATOR = dto.TEST_STEP_CREATOR;
            entity.TEST_STEP_DESCRIPTION = dto.TEST_STEP_DESCRIPTION;
            entity.USAGE_STATUS = dto.USAGE_STATUS;
            entity.CREATE_DATE = dto.CREATE_DATE;
            entity.CREATOR = dto.CREATOR;
            entity.PROJECT_DESCRIPTION = dto.PROJECT_DESCRIPTION;
            entity.PROJECT_ID = dto.PROJECT_ID;
            entity.PROJECT_NAME = dto.PROJECT_NAME;
            entity.STATUS = dto.STATUS;
            entity.DATA_ALIAS = dto.DATA_ALIAS;
            entity.DATA_SUMMARY_ID = dto.DATA_SUMMARY_ID;
            entity.DATA_AVAILABLE_MARK = dto.DATA_AVAILABLE_MARK;
            entity.DATA_VERSION = dto.DATA_VERSION;
            entity.DATA_STATUS = dto.DATA_STATUS;
            entity.DATA_SET_TYPE = dto.DATA_SET_TYPE;
            entity.DATASET_DESCRIPTION = dto.DATASET_DESCRIPTION;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="V_PROJ_TS_TC_FULLVISION"/> to an instance of <see cref="V_PROJ_TS_TC_FULLVISIONDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="V_PROJ_TS_TC_FULLVISION"/> to convert.</param>
        public static V_PROJ_TS_TC_FULLVISIONDTO ToDTO(this V_PROJ_TS_TC_FULLVISION entity)
        {
            if (entity == null) return null;

            var dto = new V_PROJ_TS_TC_FULLVISIONDTO();

            dto.TEST_SUITE_ID = entity.TEST_SUITE_ID;
            dto.TEST_SUITE_NAME = entity.TEST_SUITE_NAME;
            dto.TEST_SUITE_DESCRIPTION = entity.TEST_SUITE_DESCRIPTION;
            dto.TEST_CASE_ID = entity.TEST_CASE_ID;
            dto.TEST_CASE_NAME = entity.TEST_CASE_NAME;
            dto.TEST_STEP_CREATE_TIME = entity.TEST_STEP_CREATE_TIME;
            dto.TEST_STEP_CREATOR = entity.TEST_STEP_CREATOR;
            dto.TEST_STEP_DESCRIPTION = entity.TEST_STEP_DESCRIPTION;
            dto.USAGE_STATUS = entity.USAGE_STATUS;
            dto.CREATE_DATE = entity.CREATE_DATE;
            dto.CREATOR = entity.CREATOR;
            dto.PROJECT_DESCRIPTION = entity.PROJECT_DESCRIPTION;
            dto.PROJECT_ID = entity.PROJECT_ID;
            dto.PROJECT_NAME = entity.PROJECT_NAME;
            dto.STATUS = entity.STATUS;
            dto.DATA_ALIAS = entity.DATA_ALIAS;
            dto.DATA_SUMMARY_ID = entity.DATA_SUMMARY_ID;
            dto.DATA_AVAILABLE_MARK = entity.DATA_AVAILABLE_MARK;
            dto.DATA_VERSION = entity.DATA_VERSION;
            dto.DATA_STATUS = entity.DATA_STATUS;
            dto.DATA_SET_TYPE = entity.DATA_SET_TYPE;
            dto.DATASET_DESCRIPTION = entity.DATASET_DESCRIPTION;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="V_PROJ_TS_TC_FULLVISIONDTO"/> to an instance of <see cref="V_PROJ_TS_TC_FULLVISION"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<V_PROJ_TS_TC_FULLVISION> ToEntities(this IEnumerable<V_PROJ_TS_TC_FULLVISIONDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="V_PROJ_TS_TC_FULLVISION"/> to an instance of <see cref="V_PROJ_TS_TC_FULLVISIONDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<V_PROJ_TS_TC_FULLVISIONDTO> ToDTOs(this IEnumerable<V_PROJ_TS_TC_FULLVISION> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
