//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class V_STORYBOARD_TEST_FULLVISIONDTO
    {
        [DataMember()]
        public Int64 STORYBOARD_ID { get; set; }

        [DataMember()]
        public Int64 STORYBOARD_DETAIL_ID { get; set; }

        [DataMember()]
        public String STORYBOARD_NAME { get; set; }

        [DataMember()]
        public Int64 PROJECT_ID { get; set; }

        [DataMember()]
        public String PROJECT_NAME { get; set; }

        [DataMember()]
        public String PROJECT_DESCRIPTION { get; set; }

        [DataMember()]
        public String TEST_CASE_NAME { get; set; }

        [DataMember()]
        public Int64 TEST_CASE_ID { get; set; }

        [DataMember()]
        public String TEST_STEP_DESCRIPTION { get; set; }

        [DataMember()]
        public Nullable<Int64> TEST_SUITE_ID { get; set; }

        [DataMember()]
        public String TEST_SUITE_NAME { get; set; }

        [DataMember()]
        public String TEST_SUITE_DESCRIPTION { get; set; }

        [DataMember()]
        public Int64 RUN_ORDER { get; set; }

        [DataMember()]
        public Nullable<Int64> DEPENDS_ON { get; set; }

        [DataMember()]
        public String ALIAS_NAME { get; set; }

        [DataMember()]
        public String PARENT_ALIAS_NAME { get; set; }

        [DataMember()]
        public String DISPLAY_NAME { get; set; }

        [DataMember()]
        public Nullable<Int16> TEST_RUN_VALUE { get; set; }

        [DataMember()]
        public Nullable<Int64> LATEST_TEST_MARK_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> HIST_LATEST_TEST_MARK_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> HIST_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> HIST_TEST_ID { get; set; }

        [DataMember()]
        public Nullable<DateTime> TEST_CASE_BEGIN_TIME { get; set; }

        [DataMember()]
        public Nullable<DateTime> TEST_CASE_END_TIME { get; set; }

        [DataMember()]
        public String HIST_TEST_RESULT_IN_TEXT { get; set; }

        [DataMember()]
        public Int16 HIST_TEST_MODE { get; set; }

        [DataMember()]
        public Nullable<Int16> HIST_RESULT { get; set; }

        [DataMember()]
        public Nullable<Int64> DATA_SETTING_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> DATA_SUMMARY_ID { get; set; }

        [DataMember()]
        public Nullable<DateTime> DATA_SET_CREATETIME { get; set; }

        [DataMember()]
        public Nullable<Int64> DATA_SET_TESTERID { get; set; }

        [DataMember()]
        public Nullable<Int64> DATA_SET_VERSION { get; set; }

        [DataMember()]
        public String DATA_SET_ALIAS_NAME { get; set; }

        [DataMember()]
        public Nullable<Int16> DATA_SET_SHARE_MARK { get; set; }

        [DataMember()]
        public Nullable<Int16> DATA_SET_STATUS { get; set; }

        [DataMember()]
        public Nullable<Int16> DATA_SET_TYPE { get; set; }

        [DataMember()]
        public String DATASET_DESCRIPTION { get; set; }

        public V_STORYBOARD_TEST_FULLVISIONDTO()
        {
        }

        public V_STORYBOARD_TEST_FULLVISIONDTO(Int64 sTORYBOARD_ID, Int64 sTORYBOARD_DETAIL_ID, String sTORYBOARD_NAME, Int64 pROJECT_ID, String pROJECT_NAME, String pROJECT_DESCRIPTION, String tEST_CASE_NAME, Int64 tEST_CASE_ID, String tEST_STEP_DESCRIPTION, Nullable<Int64> tEST_SUITE_ID, String tEST_SUITE_NAME, String tEST_SUITE_DESCRIPTION, Int64 rUN_ORDER, Nullable<Int64> dEPENDS_ON, String aLIAS_NAME, String pARENT_ALIAS_NAME, String dISPLAY_NAME, Nullable<Int16> tEST_RUN_VALUE, Nullable<Int64> lATEST_TEST_MARK_ID, Nullable<Int64> hIST_LATEST_TEST_MARK_ID, Nullable<Int64> hIST_ID, Nullable<Int64> hIST_TEST_ID, Nullable<DateTime> tEST_CASE_BEGIN_TIME, Nullable<DateTime> tEST_CASE_END_TIME, String hIST_TEST_RESULT_IN_TEXT, Int16 hIST_TEST_MODE, Nullable<Int16> hIST_RESULT, Nullable<Int64> dATA_SETTING_ID, Nullable<Int64> dATA_SUMMARY_ID, Nullable<DateTime> dATA_SET_CREATETIME, Nullable<Int64> dATA_SET_TESTERID, Nullable<Int64> dATA_SET_VERSION, String dATA_SET_ALIAS_NAME, Nullable<Int16> dATA_SET_SHARE_MARK, Nullable<Int16> dATA_SET_STATUS, Nullable<Int16> dATA_SET_TYPE, String dATASET_DESCRIPTION)
        {
			this.STORYBOARD_ID = sTORYBOARD_ID;
			this.STORYBOARD_DETAIL_ID = sTORYBOARD_DETAIL_ID;
			this.STORYBOARD_NAME = sTORYBOARD_NAME;
			this.PROJECT_ID = pROJECT_ID;
			this.PROJECT_NAME = pROJECT_NAME;
			this.PROJECT_DESCRIPTION = pROJECT_DESCRIPTION;
			this.TEST_CASE_NAME = tEST_CASE_NAME;
			this.TEST_CASE_ID = tEST_CASE_ID;
			this.TEST_STEP_DESCRIPTION = tEST_STEP_DESCRIPTION;
			this.TEST_SUITE_ID = tEST_SUITE_ID;
			this.TEST_SUITE_NAME = tEST_SUITE_NAME;
			this.TEST_SUITE_DESCRIPTION = tEST_SUITE_DESCRIPTION;
			this.RUN_ORDER = rUN_ORDER;
			this.DEPENDS_ON = dEPENDS_ON;
			this.ALIAS_NAME = aLIAS_NAME;
			this.PARENT_ALIAS_NAME = pARENT_ALIAS_NAME;
			this.DISPLAY_NAME = dISPLAY_NAME;
			this.TEST_RUN_VALUE = tEST_RUN_VALUE;
			this.LATEST_TEST_MARK_ID = lATEST_TEST_MARK_ID;
			this.HIST_LATEST_TEST_MARK_ID = hIST_LATEST_TEST_MARK_ID;
			this.HIST_ID = hIST_ID;
			this.HIST_TEST_ID = hIST_TEST_ID;
			this.TEST_CASE_BEGIN_TIME = tEST_CASE_BEGIN_TIME;
			this.TEST_CASE_END_TIME = tEST_CASE_END_TIME;
			this.HIST_TEST_RESULT_IN_TEXT = hIST_TEST_RESULT_IN_TEXT;
			this.HIST_TEST_MODE = hIST_TEST_MODE;
			this.HIST_RESULT = hIST_RESULT;
			this.DATA_SETTING_ID = dATA_SETTING_ID;
			this.DATA_SUMMARY_ID = dATA_SUMMARY_ID;
			this.DATA_SET_CREATETIME = dATA_SET_CREATETIME;
			this.DATA_SET_TESTERID = dATA_SET_TESTERID;
			this.DATA_SET_VERSION = dATA_SET_VERSION;
			this.DATA_SET_ALIAS_NAME = dATA_SET_ALIAS_NAME;
			this.DATA_SET_SHARE_MARK = dATA_SET_SHARE_MARK;
			this.DATA_SET_STATUS = dATA_SET_STATUS;
			this.DATA_SET_TYPE = dATA_SET_TYPE;
			this.DATASET_DESCRIPTION = dATASET_DESCRIPTION;
        }
    }
}
