//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="V_STORYBOARD_TEST_FULLVISION"/> and <see cref="V_STORYBOARD_TEST_FULLVISIONDTO"/>.
    /// </summary>
    public static partial class V_STORYBOARD_TEST_FULLVISIONAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="V_STORYBOARD_TEST_FULLVISIONDTO"/> converted from <see cref="V_STORYBOARD_TEST_FULLVISION"/>.</param>
        static partial void OnDTO(this V_STORYBOARD_TEST_FULLVISION entity, V_STORYBOARD_TEST_FULLVISIONDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="V_STORYBOARD_TEST_FULLVISION"/> converted from <see cref="V_STORYBOARD_TEST_FULLVISIONDTO"/>.</param>
        static partial void OnEntity(this V_STORYBOARD_TEST_FULLVISIONDTO dto, V_STORYBOARD_TEST_FULLVISION entity);

        /// <summary>
        /// Converts this instance of <see cref="V_STORYBOARD_TEST_FULLVISIONDTO"/> to an instance of <see cref="V_STORYBOARD_TEST_FULLVISION"/>.
        /// </summary>
        /// <param name="dto"><see cref="V_STORYBOARD_TEST_FULLVISIONDTO"/> to convert.</param>
        public static V_STORYBOARD_TEST_FULLVISION ToEntity(this V_STORYBOARD_TEST_FULLVISIONDTO dto)
        {
            if (dto == null) return null;

            var entity = new V_STORYBOARD_TEST_FULLVISION();

            entity.STORYBOARD_ID = dto.STORYBOARD_ID;
            entity.STORYBOARD_DETAIL_ID = dto.STORYBOARD_DETAIL_ID;
            entity.STORYBOARD_NAME = dto.STORYBOARD_NAME;
            entity.PROJECT_ID = dto.PROJECT_ID;
            entity.PROJECT_NAME = dto.PROJECT_NAME;
            entity.PROJECT_DESCRIPTION = dto.PROJECT_DESCRIPTION;
            entity.TEST_CASE_NAME = dto.TEST_CASE_NAME;
            entity.TEST_CASE_ID = dto.TEST_CASE_ID;
            entity.TEST_STEP_DESCRIPTION = dto.TEST_STEP_DESCRIPTION;
            entity.TEST_SUITE_ID = dto.TEST_SUITE_ID;
            entity.TEST_SUITE_NAME = dto.TEST_SUITE_NAME;
            entity.TEST_SUITE_DESCRIPTION = dto.TEST_SUITE_DESCRIPTION;
            entity.RUN_ORDER = dto.RUN_ORDER;
            entity.DEPENDS_ON = dto.DEPENDS_ON;
            entity.ALIAS_NAME = dto.ALIAS_NAME;
            entity.PARENT_ALIAS_NAME = dto.PARENT_ALIAS_NAME;
            entity.DISPLAY_NAME = dto.DISPLAY_NAME;
            entity.TEST_RUN_VALUE = dto.TEST_RUN_VALUE;
            entity.LATEST_TEST_MARK_ID = dto.LATEST_TEST_MARK_ID;
            entity.HIST_LATEST_TEST_MARK_ID = dto.HIST_LATEST_TEST_MARK_ID;
            entity.HIST_ID = dto.HIST_ID;
            entity.HIST_TEST_ID = dto.HIST_TEST_ID;
            entity.TEST_CASE_BEGIN_TIME = dto.TEST_CASE_BEGIN_TIME;
            entity.TEST_CASE_END_TIME = dto.TEST_CASE_END_TIME;
            entity.HIST_TEST_RESULT_IN_TEXT = dto.HIST_TEST_RESULT_IN_TEXT;
            entity.HIST_TEST_MODE = dto.HIST_TEST_MODE;
            entity.HIST_RESULT = dto.HIST_RESULT;
            entity.DATA_SETTING_ID = dto.DATA_SETTING_ID;
            entity.DATA_SUMMARY_ID = dto.DATA_SUMMARY_ID;
            entity.DATA_SET_CREATETIME = dto.DATA_SET_CREATETIME;
            entity.DATA_SET_TESTERID = dto.DATA_SET_TESTERID;
            entity.DATA_SET_VERSION = dto.DATA_SET_VERSION;
            entity.DATA_SET_ALIAS_NAME = dto.DATA_SET_ALIAS_NAME;
            entity.DATA_SET_SHARE_MARK = dto.DATA_SET_SHARE_MARK;
            entity.DATA_SET_STATUS = dto.DATA_SET_STATUS;
            entity.DATA_SET_TYPE = dto.DATA_SET_TYPE;
            entity.DATASET_DESCRIPTION = dto.DATASET_DESCRIPTION;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="V_STORYBOARD_TEST_FULLVISION"/> to an instance of <see cref="V_STORYBOARD_TEST_FULLVISIONDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="V_STORYBOARD_TEST_FULLVISION"/> to convert.</param>
        public static V_STORYBOARD_TEST_FULLVISIONDTO ToDTO(this V_STORYBOARD_TEST_FULLVISION entity)
        {
            if (entity == null) return null;

            var dto = new V_STORYBOARD_TEST_FULLVISIONDTO();

            dto.STORYBOARD_ID = entity.STORYBOARD_ID;
            dto.STORYBOARD_DETAIL_ID = entity.STORYBOARD_DETAIL_ID;
            dto.STORYBOARD_NAME = entity.STORYBOARD_NAME;
            dto.PROJECT_ID = entity.PROJECT_ID;
            dto.PROJECT_NAME = entity.PROJECT_NAME;
            dto.PROJECT_DESCRIPTION = entity.PROJECT_DESCRIPTION;
            dto.TEST_CASE_NAME = entity.TEST_CASE_NAME;
            dto.TEST_CASE_ID = entity.TEST_CASE_ID;
            dto.TEST_STEP_DESCRIPTION = entity.TEST_STEP_DESCRIPTION;
            dto.TEST_SUITE_ID = entity.TEST_SUITE_ID;
            dto.TEST_SUITE_NAME = entity.TEST_SUITE_NAME;
            dto.TEST_SUITE_DESCRIPTION = entity.TEST_SUITE_DESCRIPTION;
            dto.RUN_ORDER = entity.RUN_ORDER;
            dto.DEPENDS_ON = entity.DEPENDS_ON;
            dto.ALIAS_NAME = entity.ALIAS_NAME;
            dto.PARENT_ALIAS_NAME = entity.PARENT_ALIAS_NAME;
            dto.DISPLAY_NAME = entity.DISPLAY_NAME;
            dto.TEST_RUN_VALUE = entity.TEST_RUN_VALUE;
            dto.LATEST_TEST_MARK_ID = entity.LATEST_TEST_MARK_ID;
            dto.HIST_LATEST_TEST_MARK_ID = entity.HIST_LATEST_TEST_MARK_ID;
            dto.HIST_ID = entity.HIST_ID;
            dto.HIST_TEST_ID = entity.HIST_TEST_ID;
            dto.TEST_CASE_BEGIN_TIME = entity.TEST_CASE_BEGIN_TIME;
            dto.TEST_CASE_END_TIME = entity.TEST_CASE_END_TIME;
            dto.HIST_TEST_RESULT_IN_TEXT = entity.HIST_TEST_RESULT_IN_TEXT;
            dto.HIST_TEST_MODE = entity.HIST_TEST_MODE;
            dto.HIST_RESULT = entity.HIST_RESULT;
            dto.DATA_SETTING_ID = entity.DATA_SETTING_ID;
            dto.DATA_SUMMARY_ID = entity.DATA_SUMMARY_ID;
            dto.DATA_SET_CREATETIME = entity.DATA_SET_CREATETIME;
            dto.DATA_SET_TESTERID = entity.DATA_SET_TESTERID;
            dto.DATA_SET_VERSION = entity.DATA_SET_VERSION;
            dto.DATA_SET_ALIAS_NAME = entity.DATA_SET_ALIAS_NAME;
            dto.DATA_SET_SHARE_MARK = entity.DATA_SET_SHARE_MARK;
            dto.DATA_SET_STATUS = entity.DATA_SET_STATUS;
            dto.DATA_SET_TYPE = entity.DATA_SET_TYPE;
            dto.DATASET_DESCRIPTION = entity.DATASET_DESCRIPTION;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="V_STORYBOARD_TEST_FULLVISIONDTO"/> to an instance of <see cref="V_STORYBOARD_TEST_FULLVISION"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<V_STORYBOARD_TEST_FULLVISION> ToEntities(this IEnumerable<V_STORYBOARD_TEST_FULLVISIONDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="V_STORYBOARD_TEST_FULLVISION"/> to an instance of <see cref="V_STORYBOARD_TEST_FULLVISIONDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<V_STORYBOARD_TEST_FULLVISIONDTO> ToDTOs(this IEnumerable<V_STORYBOARD_TEST_FULLVISION> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
