//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:18
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="V_TEST_DATA_REPORT_SUMMARY"/> and <see cref="V_TEST_DATA_REPORT_SUMMARYDTO"/>.
    /// </summary>
    public static partial class V_TEST_DATA_REPORT_SUMMARYAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="V_TEST_DATA_REPORT_SUMMARYDTO"/> converted from <see cref="V_TEST_DATA_REPORT_SUMMARY"/>.</param>
        static partial void OnDTO(this V_TEST_DATA_REPORT_SUMMARY entity, V_TEST_DATA_REPORT_SUMMARYDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="V_TEST_DATA_REPORT_SUMMARY"/> converted from <see cref="V_TEST_DATA_REPORT_SUMMARYDTO"/>.</param>
        static partial void OnEntity(this V_TEST_DATA_REPORT_SUMMARYDTO dto, V_TEST_DATA_REPORT_SUMMARY entity);

        /// <summary>
        /// Converts this instance of <see cref="V_TEST_DATA_REPORT_SUMMARYDTO"/> to an instance of <see cref="V_TEST_DATA_REPORT_SUMMARY"/>.
        /// </summary>
        /// <param name="dto"><see cref="V_TEST_DATA_REPORT_SUMMARYDTO"/> to convert.</param>
        public static V_TEST_DATA_REPORT_SUMMARY ToEntity(this V_TEST_DATA_REPORT_SUMMARYDTO dto)
        {
            if (dto == null) return null;

            var entity = new V_TEST_DATA_REPORT_SUMMARY();

            entity.KEY_WORD_NAME = dto.KEY_WORD_NAME;
            entity.OBJECT_HAPPY_NAME = dto.OBJECT_HAPPY_NAME;
            entity.INPUT_VALUE_SETTING = dto.INPUT_VALUE_SETTING;
            entity.RETURN_VALUES = dto.RETURN_VALUES;
            entity.ACTUAL_INPUT_DATA = dto.ACTUAL_INPUT_DATA;
            entity.LATEST_TEST_MARK_ID = dto.LATEST_TEST_MARK_ID;
            entity.STORYBOARD_DETAIL_ID = dto.STORYBOARD_DETAIL_ID;
            entity.LOOP_ID = dto.LOOP_ID;
            entity.RUN_ORDER = dto.RUN_ORDER;
            entity.TEST_MODE = dto.TEST_MODE;
            entity.TEST_REPORT_STEP_ID = dto.TEST_REPORT_STEP_ID;
            entity.COLUMN_ROW_SETTING = dto.COLUMN_ROW_SETTING;
            entity.STORYBOARD_ORDER = dto.STORYBOARD_ORDER;
            entity.STORYBOARD_ID = dto.STORYBOARD_ID;
            entity.TEST_CASE_ID = dto.TEST_CASE_ID;
            entity.RUNNING_RESULT_INFO = dto.RUNNING_RESULT_INFO;
            entity.STEPS_ID = dto.STEPS_ID;
            entity.INFO_PIC = dto.INFO_PIC;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="V_TEST_DATA_REPORT_SUMMARY"/> to an instance of <see cref="V_TEST_DATA_REPORT_SUMMARYDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="V_TEST_DATA_REPORT_SUMMARY"/> to convert.</param>
        public static V_TEST_DATA_REPORT_SUMMARYDTO ToDTO(this V_TEST_DATA_REPORT_SUMMARY entity)
        {
            if (entity == null) return null;

            var dto = new V_TEST_DATA_REPORT_SUMMARYDTO();

            dto.KEY_WORD_NAME = entity.KEY_WORD_NAME;
            dto.OBJECT_HAPPY_NAME = entity.OBJECT_HAPPY_NAME;
            dto.INPUT_VALUE_SETTING = entity.INPUT_VALUE_SETTING;
            dto.RETURN_VALUES = entity.RETURN_VALUES;
            dto.ACTUAL_INPUT_DATA = entity.ACTUAL_INPUT_DATA;
            dto.LATEST_TEST_MARK_ID = entity.LATEST_TEST_MARK_ID;
            dto.STORYBOARD_DETAIL_ID = entity.STORYBOARD_DETAIL_ID;
            dto.LOOP_ID = entity.LOOP_ID;
            dto.RUN_ORDER = entity.RUN_ORDER;
            dto.TEST_MODE = entity.TEST_MODE;
            dto.TEST_REPORT_STEP_ID = entity.TEST_REPORT_STEP_ID;
            dto.COLUMN_ROW_SETTING = entity.COLUMN_ROW_SETTING;
            dto.STORYBOARD_ORDER = entity.STORYBOARD_ORDER;
            dto.STORYBOARD_ID = entity.STORYBOARD_ID;
            dto.TEST_CASE_ID = entity.TEST_CASE_ID;
            dto.RUNNING_RESULT_INFO = entity.RUNNING_RESULT_INFO;
            dto.STEPS_ID = entity.STEPS_ID;
            dto.INFO_PIC = entity.INFO_PIC;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="V_TEST_DATA_REPORT_SUMMARYDTO"/> to an instance of <see cref="V_TEST_DATA_REPORT_SUMMARY"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<V_TEST_DATA_REPORT_SUMMARY> ToEntities(this IEnumerable<V_TEST_DATA_REPORT_SUMMARYDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="V_TEST_DATA_REPORT_SUMMARY"/> to an instance of <see cref="V_TEST_DATA_REPORT_SUMMARYDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<V_TEST_DATA_REPORT_SUMMARYDTO> ToDTOs(this IEnumerable<V_TEST_DATA_REPORT_SUMMARY> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
