//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class V_TEST_STEPS_FULLVISIONDTO
    {
        [DataMember()]
        public Int64 TEST_CASE_ID { get; set; }

        [DataMember()]
        public String TEST_CASE_NAME { get; set; }

        [DataMember()]
        public Int64 KEY_WORD_ID { get; set; }

        [DataMember()]
        public String KEY_WORD_NAME { get; set; }

        [DataMember()]
        public String OBJECT_HAPPY_NAME { get; set; }

        [DataMember()]
        public Int64 OBJECT_ID { get; set; }

        [DataMember()]
        public String OBJECT_TYPE { get; set; }

        [DataMember()]
        public String QUICK_ACCESS { get; set; }

        [DataMember()]
        public String ENUM_TYPE { get; set; }

        [DataMember()]
        public Nullable<Int64> APPLICATION_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> OBJECT_NAME_ID { get; set; }

        [DataMember()]
        public String TYPE_NAME { get; set; }

        [DataMember()]
        public String COLUMN_ROW_SETTING { get; set; }

        [DataMember()]
        public Int64 STEPS_ID { get; set; }

        [DataMember()]
        public String COMMENTINFO { get; set; }

        [DataMember()]
        public Nullable<Int64> IS_RUNNABLE { get; set; }

        [DataMember()]
        public Int64 RUN_ORDER { get; set; }

        [DataMember()]
        public String VALUE_SETTING { get; set; }

        public V_TEST_STEPS_FULLVISIONDTO()
        {
        }

        public V_TEST_STEPS_FULLVISIONDTO(Int64 tEST_CASE_ID, String tEST_CASE_NAME, Int64 kEY_WORD_ID, String kEY_WORD_NAME, String oBJECT_HAPPY_NAME, Int64 oBJECT_ID, String oBJECT_TYPE, String qUICK_ACCESS, String eNUM_TYPE, Nullable<Int64> aPPLICATION_ID, Nullable<Int64> oBJECT_NAME_ID, String tYPE_NAME, String cOLUMN_ROW_SETTING, Int64 sTEPS_ID, String cOMMENTINFO, Nullable<Int64> iS_RUNNABLE, Int64 rUN_ORDER, String vALUE_SETTING)
        {
			this.TEST_CASE_ID = tEST_CASE_ID;
			this.TEST_CASE_NAME = tEST_CASE_NAME;
			this.KEY_WORD_ID = kEY_WORD_ID;
			this.KEY_WORD_NAME = kEY_WORD_NAME;
			this.OBJECT_HAPPY_NAME = oBJECT_HAPPY_NAME;
			this.OBJECT_ID = oBJECT_ID;
			this.OBJECT_TYPE = oBJECT_TYPE;
			this.QUICK_ACCESS = qUICK_ACCESS;
			this.ENUM_TYPE = eNUM_TYPE;
			this.APPLICATION_ID = aPPLICATION_ID;
			this.OBJECT_NAME_ID = oBJECT_NAME_ID;
			this.TYPE_NAME = tYPE_NAME;
			this.COLUMN_ROW_SETTING = cOLUMN_ROW_SETTING;
			this.STEPS_ID = sTEPS_ID;
			this.COMMENTINFO = cOMMENTINFO;
			this.IS_RUNNABLE = iS_RUNNABLE;
			this.RUN_ORDER = rUN_ORDER;
			this.VALUE_SETTING = vALUE_SETTING;
        }
    }
}
