//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:44
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.message.Dto
{
    [DataContract()]
    public partial class V_TEST_DATARPT_CAPTUREDTO
    {
        [DataMember()]
        public String KEY_WORD_NAME { get; set; }

        [DataMember()]
        public String OBJECT_HAPPY_NAME { get; set; }

        [DataMember()]
        public String INPUT_VALUE_SETTING { get; set; }

        [DataMember()]
        public String RETURN_VALUES { get; set; }

        [DataMember()]
        public String ACTUAL_INPUT_DATA { get; set; }

        [DataMember()]
        public Nullable<Int64> LATEST_TEST_MARK_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> STORYBOARD_DETAIL_ID { get; set; }

        [DataMember()]
        public Nullable<Decimal> LOOP_ID { get; set; }

        [DataMember()]
        public Nullable<Decimal> RUN_ORDER { get; set; }

        [DataMember()]
        public Nullable<Int16> TEST_MODE { get; set; }

        [DataMember()]
        public Int64 TEST_REPORT_STEP_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> STORYBOARD_ID { get; set; }

        public V_TEST_DATARPT_CAPTUREDTO()
        {
        }

        public V_TEST_DATARPT_CAPTUREDTO(String kEY_WORD_NAME, String oBJECT_HAPPY_NAME, String iNPUT_VALUE_SETTING, String rETURN_VALUES, String aCTUAL_INPUT_DATA, Nullable<Int64> lATEST_TEST_MARK_ID, Nullable<Int64> sTORYBOARD_DETAIL_ID, Nullable<Decimal> lOOP_ID, Nullable<Decimal> rUN_ORDER, Nullable<Int16> tEST_MODE, Int64 tEST_REPORT_STEP_ID, Nullable<Int64> sTORYBOARD_ID)
        {
			this.KEY_WORD_NAME = kEY_WORD_NAME;
			this.OBJECT_HAPPY_NAME = oBJECT_HAPPY_NAME;
			this.INPUT_VALUE_SETTING = iNPUT_VALUE_SETTING;
			this.RETURN_VALUES = rETURN_VALUES;
			this.ACTUAL_INPUT_DATA = aCTUAL_INPUT_DATA;
			this.LATEST_TEST_MARK_ID = lATEST_TEST_MARK_ID;
			this.STORYBOARD_DETAIL_ID = sTORYBOARD_DETAIL_ID;
			this.LOOP_ID = lOOP_ID;
			this.RUN_ORDER = rUN_ORDER;
			this.TEST_MODE = tEST_MODE;
			this.TEST_REPORT_STEP_ID = tEST_REPORT_STEP_ID;
			this.STORYBOARD_ID = sTORYBOARD_ID;
        }
    }
}
