//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.message.Dto
{

    /// <summary>
    /// Assembler for <see cref="V_USER_COMPANY"/> and <see cref="V_USER_COMPANYDTO"/>.
    /// </summary>
    public static partial class V_USER_COMPANYAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="V_USER_COMPANYDTO"/> converted from <see cref="V_USER_COMPANY"/>.</param>
        static partial void OnDTO(this V_USER_COMPANY entity, V_USER_COMPANYDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="V_USER_COMPANY"/> converted from <see cref="V_USER_COMPANYDTO"/>.</param>
        static partial void OnEntity(this V_USER_COMPANYDTO dto, V_USER_COMPANY entity);

        /// <summary>
        /// Converts this instance of <see cref="V_USER_COMPANYDTO"/> to an instance of <see cref="V_USER_COMPANY"/>.
        /// </summary>
        /// <param name="dto"><see cref="V_USER_COMPANYDTO"/> to convert.</param>
        public static V_USER_COMPANY ToEntity(this V_USER_COMPANYDTO dto)
        {
            if (dto == null) return null;

            var entity = new V_USER_COMPANY();

            entity.TESTER_ID = dto.TESTER_ID;
            entity.TESTER_NAME_LAST = dto.TESTER_NAME_LAST;
            entity.TESTER_NAME_M = dto.TESTER_NAME_M;
            entity.TESTER_NAME_F = dto.TESTER_NAME_F;
            entity.TESTER_LOGIN_NAME = dto.TESTER_LOGIN_NAME;
            entity.TESTER_PWD = dto.TESTER_PWD;
            entity.AVAILABLE_MARK = dto.AVAILABLE_MARK;
            entity.TESTER_MAIL = dto.TESTER_MAIL;
            entity.TESTER_NUMBER = dto.TESTER_NUMBER;
            entity.COMPANY_ID = dto.COMPANY_ID;
            entity.TESTER_DESC = dto.TESTER_DESC;
            entity.COMPANY_NAME = dto.COMPANY_NAME;
            entity.COMPANY_DESC = dto.COMPANY_DESC;
            entity.COMPANY_ADDRESS = dto.COMPANY_ADDRESS;
            entity.COMPANY_NUMBER = dto.COMPANY_NUMBER;
            entity.COMPANY_AVAILABLE_MARK = dto.COMPANY_AVAILABLE_MARK;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="V_USER_COMPANY"/> to an instance of <see cref="V_USER_COMPANYDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="V_USER_COMPANY"/> to convert.</param>
        public static V_USER_COMPANYDTO ToDTO(this V_USER_COMPANY entity)
        {
            if (entity == null) return null;

            var dto = new V_USER_COMPANYDTO();

            dto.TESTER_ID = entity.TESTER_ID;
            dto.TESTER_NAME_LAST = entity.TESTER_NAME_LAST;
            dto.TESTER_NAME_M = entity.TESTER_NAME_M;
            dto.TESTER_NAME_F = entity.TESTER_NAME_F;
            dto.TESTER_LOGIN_NAME = entity.TESTER_LOGIN_NAME;
            dto.TESTER_PWD = entity.TESTER_PWD;
            dto.AVAILABLE_MARK = entity.AVAILABLE_MARK;
            dto.TESTER_MAIL = entity.TESTER_MAIL;
            dto.TESTER_NUMBER = entity.TESTER_NUMBER;
            dto.COMPANY_ID = entity.COMPANY_ID;
            dto.TESTER_DESC = entity.TESTER_DESC;
            dto.COMPANY_NAME = entity.COMPANY_NAME;
            dto.COMPANY_DESC = entity.COMPANY_DESC;
            dto.COMPANY_ADDRESS = entity.COMPANY_ADDRESS;
            dto.COMPANY_NUMBER = entity.COMPANY_NUMBER;
            dto.COMPANY_AVAILABLE_MARK = entity.COMPANY_AVAILABLE_MARK;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="V_USER_COMPANYDTO"/> to an instance of <see cref="V_USER_COMPANY"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<V_USER_COMPANY> ToEntities(this IEnumerable<V_USER_COMPANYDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="V_USER_COMPANY"/> to an instance of <see cref="V_USER_COMPANYDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<V_USER_COMPANYDTO> ToDTOs(this IEnumerable<V_USER_COMPANY> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
