//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarsEntities : DbContext
    {
        public MarsEntities()
            : base("name=MarsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<REL_TEST_CASE_TEST_STEPS> REL_TEST_CASE_TEST_STEPS { get; set; }
        public DbSet<REL_TEST_SUIT_PROJECT> REL_TEST_SUIT_PROJECT { get; set; }
        public DbSet<SYSTEM_LOOKUP> SYSTEM_LOOKUP { get; set; }
        public DbSet<T_DATA_SOURCE> T_DATA_SOURCE { get; set; }
        public DbSet<T_DIC_RELATION_KEYWORD> T_DIC_RELATION_KEYWORD { get; set; }
        public DbSet<T_GUI_COMPONENT_TYPE_DIC> T_GUI_COMPONENT_TYPE_DIC { get; set; }
        public DbSet<T_KEYWORD> T_KEYWORD { get; set; }
        public DbSet<T_PROJECT_DATA_SOURCE> T_PROJECT_DATA_SOURCE { get; set; }
        public DbSet<T_REGISTED_OBJECT> T_REGISTED_OBJECT { get; set; }
        public DbSet<T_REGISTERED_APPS> T_REGISTERED_APPS { get; set; }
        public DbSet<T_TEST_CASE_SUMMARY> T_TEST_CASE_SUMMARY { get; set; }
        public DbSet<T_TEST_PROJECT> T_TEST_PROJECT { get; set; }
        public DbSet<T_TEST_REPORT> T_TEST_REPORT { get; set; }
        public DbSet<T_TEST_REPORT_STEPS> T_TEST_REPORT_STEPS { get; set; }
        public DbSet<T_TEST_STEPS> T_TEST_STEPS { get; set; }
        public DbSet<T_TEST_SUITE> T_TEST_SUITE { get; set; }
        public DbSet<TEST_DATA_SETTING> TEST_DATA_SETTING { get; set; }
    }
}
