//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TESTSTORYBOARD_SUMMARY
    {
        public string STORYBOARD_NAME { get; set; }
        public long STORYBOARD_ID { get; set; }
        public Nullable<long> TSCNT { get; set; }
        public Nullable<long> TCCNT { get; set; }
        public Nullable<long> BASE_RIGHT_CNT { get; set; }
        public Nullable<long> BASE_FAIL_CNT { get; set; }
        public Nullable<long> BASE_PARTIAL_CNT { get; set; }
        public Nullable<long> CMP_RIGHT_CNT { get; set; }
        public Nullable<long> CMP_FAIL_CNT { get; set; }
        public Nullable<long> CMP_PARTIAL_CNT { get; set; }
        public Nullable<long> STEP_CNT { get; set; }
    }
}
