//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.Inter.MQCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mars.Inter.MQCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact Marquis.
        /// </summary>
        internal static string mars_contact_to_marquis {
            get {
                return ResourceManager.GetString("mars_contact_to_marquis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code MQ008:MARS automation test engine can&apos;t get all data from table.
        /// </summary>
        internal static string mars_mq_capture_batch_cant_get_all_data_from_table {
            get {
                return ResourceManager.GetString("mars_mq_capture_batch_cant_get_all_data_from_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code MQ004:MARS:MARS automation test engine can&apos;t get all columns information for Object [{0}].[{1}].
        /// </summary>
        internal static string mars_mq_capture_batch_exception_when_get_colmns {
            get {
                return ResourceManager.GetString("mars_mq_capture_batch_exception_when_get_colmns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code MQ001: Parameter [{0}] format is not right for batch mode. Please set parameter as &apos;BATCHCAPTURE:variableName&apos;. Another test step with parameter ‘BATCHCAPTUREND’ should be paired..
        /// </summary>
        internal static string mars_mq_capture_batch_format_error {
            get {
                return ResourceManager.GetString("mars_mq_capture_batch_format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code MQ007:More than one column name matches [{0}].
        /// </summary>
        internal static string mars_mq_capture_batch_morethan_one_column_found {
            get {
                return ResourceManager.GetString("mars_mq_capture_batch_morethan_one_column_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code MQ006:No such column [{0}] in table. Column names are:[{0}].
        /// </summary>
        internal static string mars_mq_capture_batch_no_such_column {
            get {
                return ResourceManager.GetString("mars_mq_capture_batch_no_such_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code MQ002:MARS automation test engine can&apos;t get all columns information for Object [{0}].[{1}].
        /// </summary>
        internal static string mars_mq_capture_batch_unknow_excaption {
            get {
                return ResourceManager.GetString("mars_mq_capture_batch_unknow_excaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code MQ005:Wrong invokation for Capturevalue|caputerAndCompare keyword..
        /// </summary>
        internal static string mars_mq_caputre_batch_wrong_call_all_grid {
            get {
                return ResourceManager.GetString("mars_mq_caputre_batch_wrong_call_all_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code MQ003:MARS automation test engine can&apos;t get grid columns&apos; caption ans keys. .
        /// </summary>
        internal static string mars_mq_infragistics_table_cant_get_column_info {
            get {
                return ResourceManager.GetString("mars_mq_infragistics_table_cant_get_column_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap path {
            get {
                object obj = ResourceManager.GetObject("path", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap path1 {
            get {
                object obj = ResourceManager.GetObject("path1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap path2 {
            get {
                object obj = ResourceManager.GetObject("path2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
