//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TEST_STEPS_FULLVISION
    {
        public long TEST_CASE_ID { get; set; }
        public string TEST_CASE_NAME { get; set; }
        public long KEY_WORD_ID { get; set; }
        public string KEY_WORD_NAME { get; set; }
        public string OBJECT_HAPPY_NAME { get; set; }
        public long OBJECT_ID { get; set; }
        public string OBJECT_TYPE { get; set; }
        public string QUICK_ACCESS { get; set; }
        public string ENUM_TYPE { get; set; }
        public Nullable<long> APPLICATION_ID { get; set; }
        public Nullable<long> OBJECT_NAME_ID { get; set; }
        public string TYPE_NAME { get; set; }
        public string COLUMN_ROW_SETTING { get; set; }
        public long STEPS_ID { get; set; }
        public string COMMENTINFO { get; set; }
        public Nullable<long> IS_RUNNABLE { get; set; }
        public long RUN_ORDER { get; set; }
        public string VALUE_SETTING { get; set; }
    }
}
