//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="REL_APP_TESTSUITE"/> and <see cref="REL_APP_TESTSUITEDTO"/>.
    /// </summary>
    public static partial class REL_APP_TESTSUITEAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="REL_APP_TESTSUITEDTO"/> converted from <see cref="REL_APP_TESTSUITE"/>.</param>
        static partial void OnDTO(this REL_APP_TESTSUITE entity, REL_APP_TESTSUITEDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="REL_APP_TESTSUITE"/> converted from <see cref="REL_APP_TESTSUITEDTO"/>.</param>
        static partial void OnEntity(this REL_APP_TESTSUITEDTO dto, REL_APP_TESTSUITE entity);

        /// <summary>
        /// Converts this instance of <see cref="REL_APP_TESTSUITEDTO"/> to an instance of <see cref="REL_APP_TESTSUITE"/>.
        /// </summary>
        /// <param name="dto"><see cref="REL_APP_TESTSUITEDTO"/> to convert.</param>
        public static REL_APP_TESTSUITE ToEntity(this REL_APP_TESTSUITEDTO dto)
        {
            if (dto == null) return null;

            var entity = new REL_APP_TESTSUITE();

            entity.RELATIONSHIP_ID = dto.RELATIONSHIP_ID;
            entity.APPLICATION_ID = dto.APPLICATION_ID;
            entity.TEST_SUITE_ID = dto.TEST_SUITE_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="REL_APP_TESTSUITE"/> to an instance of <see cref="REL_APP_TESTSUITEDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="REL_APP_TESTSUITE"/> to convert.</param>
        public static REL_APP_TESTSUITEDTO ToDTO(this REL_APP_TESTSUITE entity)
        {
            if (entity == null) return null;

            var dto = new REL_APP_TESTSUITEDTO();

            dto.RELATIONSHIP_ID = entity.RELATIONSHIP_ID;
            dto.APPLICATION_ID = entity.APPLICATION_ID;
            dto.TEST_SUITE_ID = entity.TEST_SUITE_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="REL_APP_TESTSUITEDTO"/> to an instance of <see cref="REL_APP_TESTSUITE"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<REL_APP_TESTSUITE> ToEntities(this IEnumerable<REL_APP_TESTSUITEDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="REL_APP_TESTSUITE"/> to an instance of <see cref="REL_APP_TESTSUITEDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<REL_APP_TESTSUITEDTO> ToDTOs(this IEnumerable<REL_APP_TESTSUITE> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
