//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="REL_APP_TESTCASE"/> and <see cref="REL_APP_TESTCASEDTO"/>.
    /// </summary>
    public static partial class REL_APP_TESTCASEAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="REL_APP_TESTCASEDTO"/> converted from <see cref="REL_APP_TESTCASE"/>.</param>
        static partial void OnDTO(this REL_APP_TESTCASE entity, REL_APP_TESTCASEDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="REL_APP_TESTCASE"/> converted from <see cref="REL_APP_TESTCASEDTO"/>.</param>
        static partial void OnEntity(this REL_APP_TESTCASEDTO dto, REL_APP_TESTCASE entity);

        /// <summary>
        /// Converts this instance of <see cref="REL_APP_TESTCASEDTO"/> to an instance of <see cref="REL_APP_TESTCASE"/>.
        /// </summary>
        /// <param name="dto"><see cref="REL_APP_TESTCASEDTO"/> to convert.</param>
        public static REL_APP_TESTCASE ToEntity(this REL_APP_TESTCASEDTO dto)
        {
            if (dto == null) return null;

            var entity = new REL_APP_TESTCASE();

            entity.RELATIONSHIP_ID = dto.RELATIONSHIP_ID;
            entity.APPLICATION_ID = dto.APPLICATION_ID;
            entity.TEST_CASE_ID = dto.TEST_CASE_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="REL_APP_TESTCASE"/> to an instance of <see cref="REL_APP_TESTCASEDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="REL_APP_TESTCASE"/> to convert.</param>
        public static REL_APP_TESTCASEDTO ToDTO(this REL_APP_TESTCASE entity)
        {
            if (entity == null) return null;

            var dto = new REL_APP_TESTCASEDTO();

            dto.RELATIONSHIP_ID = entity.RELATIONSHIP_ID;
            dto.APPLICATION_ID = entity.APPLICATION_ID;
            dto.TEST_CASE_ID = entity.TEST_CASE_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="REL_APP_TESTCASEDTO"/> to an instance of <see cref="REL_APP_TESTCASE"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<REL_APP_TESTCASE> ToEntities(this IEnumerable<REL_APP_TESTCASEDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="REL_APP_TESTCASE"/> to an instance of <see cref="REL_APP_TESTCASEDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<REL_APP_TESTCASEDTO> ToDTOs(this IEnumerable<REL_APP_TESTCASE> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
