//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:36
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class REL_TEST_CASE_TEST_SUITEDTO
    {
        [DataMember()]
        public Int64 RELATIONSHIP_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> TEST_CASE_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> TEST_SUITE_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_SUITE_TEST_SUITE_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_CASE_SUMMARY_TEST_CASE_ID { get; set; }

        public REL_TEST_CASE_TEST_SUITEDTO()
        {
        }

        public REL_TEST_CASE_TEST_SUITEDTO(Int64 rELATIONSHIP_ID, Nullable<Int64> tEST_CASE_ID, Nullable<Int64> tEST_SUITE_ID, Int64 t_TEST_SUITE_TEST_SUITE_ID, Int64 t_TEST_CASE_SUMMARY_TEST_CASE_ID)
        {
			this.RELATIONSHIP_ID = rELATIONSHIP_ID;
			this.TEST_CASE_ID = tEST_CASE_ID;
			this.TEST_SUITE_ID = tEST_SUITE_ID;
			this.T_TEST_SUITE_TEST_SUITE_ID = t_TEST_SUITE_TEST_SUITE_ID;
			this.T_TEST_CASE_SUMMARY_TEST_CASE_ID = t_TEST_CASE_SUMMARY_TEST_CASE_ID;
        }
    }
}
