//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:39
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_BASELINE_DATA_SUMMARYDTO
    {
        [DataMember()]
        public Int64 DATA_BASE_OBJ_ID { get; set; }

        [DataMember()]
        public Nullable<Int16> DATA_SUMMARY_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> DATA_BASE_OBJ_PARENT_ID { get; set; }

        [DataMember()]
        public String OBJECT_HAPPY_NAME { get; set; }

        [DataMember()]
        public Nullable<Int16> ORDER_ID { get; set; }

        public T_BASELINE_DATA_SUMMARYDTO()
        {
        }

        public T_BASELINE_DATA_SUMMARYDTO(Int64 dATA_BASE_OBJ_ID, Nullable<Int16> dATA_SUMMARY_ID, Nullable<Int64> dATA_BASE_OBJ_PARENT_ID, String oBJECT_HAPPY_NAME, Nullable<Int16> oRDER_ID)
        {
			this.DATA_BASE_OBJ_ID = dATA_BASE_OBJ_ID;
			this.DATA_SUMMARY_ID = dATA_SUMMARY_ID;
			this.DATA_BASE_OBJ_PARENT_ID = dATA_BASE_OBJ_PARENT_ID;
			this.OBJECT_HAPPY_NAME = oBJECT_HAPPY_NAME;
			this.ORDER_ID = oRDER_ID;
        }
    }
}
