//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_COMPARE_CONFIG"/> and <see cref="T_COMPARE_CONFIGDTO"/>.
    /// </summary>
    public static partial class T_COMPARE_CONFIGAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_COMPARE_CONFIGDTO"/> converted from <see cref="T_COMPARE_CONFIG"/>.</param>
        static partial void OnDTO(this T_COMPARE_CONFIG entity, T_COMPARE_CONFIGDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_COMPARE_CONFIG"/> converted from <see cref="T_COMPARE_CONFIGDTO"/>.</param>
        static partial void OnEntity(this T_COMPARE_CONFIGDTO dto, T_COMPARE_CONFIG entity);

        /// <summary>
        /// Converts this instance of <see cref="T_COMPARE_CONFIGDTO"/> to an instance of <see cref="T_COMPARE_CONFIG"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_COMPARE_CONFIGDTO"/> to convert.</param>
        public static T_COMPARE_CONFIG ToEntity(this T_COMPARE_CONFIGDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_COMPARE_CONFIG();

            entity.COMPARE_ID = dto.COMPARE_ID;
            entity.COMPARE_NAME = dto.COMPARE_NAME;
            entity.S1_TYPE = dto.S1_TYPE;
            entity.S1_DBCONN = dto.S1_DBCONN;
            entity.S1_QUERY = dto.S1_QUERY;
            entity.S1_FILE_LOC = dto.S1_FILE_LOC;
            entity.S2_TYPE = dto.S2_TYPE;
            entity.S2_DBCONN = dto.S2_DBCONN;
            entity.S2_QUERY = dto.S2_QUERY;
            entity.S2_FILE_LOC = dto.S2_FILE_LOC;
            entity.O_FILE_LOC = dto.O_FILE_LOC;
            entity.KEY_FIELDS = dto.KEY_FIELDS;
            entity.SHOW_FIELDS = dto.SHOW_FIELDS;
            entity.COMPARE_FIELDS = dto.COMPARE_FIELDS;
            entity.ROW_FIELDS = dto.ROW_FIELDS;
            entity.COLUMN_FIELDS = dto.COLUMN_FIELDS;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_COMPARE_CONFIG"/> to an instance of <see cref="T_COMPARE_CONFIGDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_COMPARE_CONFIG"/> to convert.</param>
        public static T_COMPARE_CONFIGDTO ToDTO(this T_COMPARE_CONFIG entity)
        {
            if (entity == null) return null;

            var dto = new T_COMPARE_CONFIGDTO();

            dto.COMPARE_ID = entity.COMPARE_ID;
            dto.COMPARE_NAME = entity.COMPARE_NAME;
            dto.S1_TYPE = entity.S1_TYPE;
            dto.S1_DBCONN = entity.S1_DBCONN;
            dto.S1_QUERY = entity.S1_QUERY;
            dto.S1_FILE_LOC = entity.S1_FILE_LOC;
            dto.S2_TYPE = entity.S2_TYPE;
            dto.S2_DBCONN = entity.S2_DBCONN;
            dto.S2_QUERY = entity.S2_QUERY;
            dto.S2_FILE_LOC = entity.S2_FILE_LOC;
            dto.O_FILE_LOC = entity.O_FILE_LOC;
            dto.KEY_FIELDS = entity.KEY_FIELDS;
            dto.SHOW_FIELDS = entity.SHOW_FIELDS;
            dto.COMPARE_FIELDS = entity.COMPARE_FIELDS;
            dto.ROW_FIELDS = entity.ROW_FIELDS;
            dto.COLUMN_FIELDS = entity.COLUMN_FIELDS;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_COMPARE_CONFIGDTO"/> to an instance of <see cref="T_COMPARE_CONFIG"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_COMPARE_CONFIG> ToEntities(this IEnumerable<T_COMPARE_CONFIGDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_COMPARE_CONFIG"/> to an instance of <see cref="T_COMPARE_CONFIGDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_COMPARE_CONFIGDTO> ToDTOs(this IEnumerable<T_COMPARE_CONFIG> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
