//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_COMPARE_CONNECTIONSDTO
    {
        [DataMember()]
        public Decimal DBCONN_ID { get; set; }

        [DataMember()]
        public String DBCONN_NAME { get; set; }

        [DataMember()]
        public String TYPE { get; set; }

        [DataMember()]
        public String HOST { get; set; }

        [DataMember()]
        public String PORT { get; set; }

        [DataMember()]
        public String PROTOCOL { get; set; }

        [DataMember()]
        public String SERVICE_NAME { get; set; }

        [DataMember()]
        public String USERID { get; set; }

        [DataMember()]
        public String PASSWORD { get; set; }

        public T_COMPARE_CONNECTIONSDTO()
        {
        }

        public T_COMPARE_CONNECTIONSDTO(Decimal dBCONN_ID, String dBCONN_NAME, String tYPE, String hOST, String pORT, String pROTOCOL, String sERVICE_NAME, String uSERID, String pASSWORD)
        {
			this.DBCONN_ID = dBCONN_ID;
			this.DBCONN_NAME = dBCONN_NAME;
			this.TYPE = tYPE;
			this.HOST = hOST;
			this.PORT = pORT;
			this.PROTOCOL = pROTOCOL;
			this.SERVICE_NAME = sERVICE_NAME;
			this.USERID = uSERID;
			this.PASSWORD = pASSWORD;
        }
    }
}
