//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_DIC_RELATION_KEYWORD"/> and <see cref="T_DIC_RELATION_KEYWORDDTO"/>.
    /// </summary>
    public static partial class T_DIC_RELATION_KEYWORDAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_DIC_RELATION_KEYWORDDTO"/> converted from <see cref="T_DIC_RELATION_KEYWORD"/>.</param>
        static partial void OnDTO(this T_DIC_RELATION_KEYWORD entity, T_DIC_RELATION_KEYWORDDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_DIC_RELATION_KEYWORD"/> converted from <see cref="T_DIC_RELATION_KEYWORDDTO"/>.</param>
        static partial void OnEntity(this T_DIC_RELATION_KEYWORDDTO dto, T_DIC_RELATION_KEYWORD entity);

        /// <summary>
        /// Converts this instance of <see cref="T_DIC_RELATION_KEYWORDDTO"/> to an instance of <see cref="T_DIC_RELATION_KEYWORD"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_DIC_RELATION_KEYWORDDTO"/> to convert.</param>
        public static T_DIC_RELATION_KEYWORD ToEntity(this T_DIC_RELATION_KEYWORDDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_DIC_RELATION_KEYWORD();

            entity.RELATION_ID = dto.RELATION_ID;
            entity.TYPE_ID = dto.TYPE_ID;
            entity.KEY_WORD_ID = dto.KEY_WORD_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_DIC_RELATION_KEYWORD"/> to an instance of <see cref="T_DIC_RELATION_KEYWORDDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_DIC_RELATION_KEYWORD"/> to convert.</param>
        public static T_DIC_RELATION_KEYWORDDTO ToDTO(this T_DIC_RELATION_KEYWORD entity)
        {
            if (entity == null) return null;

            var dto = new T_DIC_RELATION_KEYWORDDTO();

            dto.RELATION_ID = entity.RELATION_ID;
            dto.TYPE_ID = entity.TYPE_ID;
            dto.KEY_WORD_ID = entity.KEY_WORD_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_DIC_RELATION_KEYWORDDTO"/> to an instance of <see cref="T_DIC_RELATION_KEYWORD"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_DIC_RELATION_KEYWORD> ToEntities(this IEnumerable<T_DIC_RELATION_KEYWORDDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_DIC_RELATION_KEYWORD"/> to an instance of <see cref="T_DIC_RELATION_KEYWORDDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_DIC_RELATION_KEYWORDDTO> ToDTOs(this IEnumerable<T_DIC_RELATION_KEYWORD> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
