//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:44
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_OBJECT_CHILDDTO
    {
        [DataMember()]
        public Int64 CHILD_ID { get; set; }

        [DataMember()]
        public Int64 OBJECT_ID { get; set; }

        [DataMember()]
        public String OBJ_CHLD_HAPPYNAME { get; set; }

        [DataMember()]
        public Nullable<Int16> CHILD_TYPE { get; set; }

        [DataMember()]
        public String DESCRIPTION { get; set; }

        [DataMember()]
        public Nullable<Int64> PARENT_CHILD_ID { get; set; }

        [DataMember()]
        public String INTERNAL_EXPRESSION { get; set; }

        public T_OBJECT_CHILDDTO()
        {
        }

        public T_OBJECT_CHILDDTO(Int64 cHILD_ID, Int64 oBJECT_ID, String oBJ_CHLD_HAPPYNAME, Nullable<Int16> cHILD_TYPE, String dESCRIPTION, Nullable<Int64> pARENT_CHILD_ID, String iNTERNAL_EXPRESSION)
        {
			this.CHILD_ID = cHILD_ID;
			this.OBJECT_ID = oBJECT_ID;
			this.OBJ_CHLD_HAPPYNAME = oBJ_CHLD_HAPPYNAME;
			this.CHILD_TYPE = cHILD_TYPE;
			this.DESCRIPTION = dESCRIPTION;
			this.PARENT_CHILD_ID = pARENT_CHILD_ID;
			this.INTERNAL_EXPRESSION = iNTERNAL_EXPRESSION;
        }
    }
}
