//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_PROJ_TC_MGRDTO
    {
        [DataMember()]
        public virtual Int64 STORYBOARD_DETAIL_ID { get; set; }

        [DataMember()]
        public virtual Nullable<Int64> PROJECT_ID { get; set; }

        [DataMember()]
        public virtual Nullable<Int64> TEST_CASE_ID { get; set; }

        [DataMember()]
        public virtual Nullable<Int64> STORYBOARD_ID { get; set; }

        [DataMember()]
        public virtual Nullable<Int16> RUN_TYPE { get; set; }

        [DataMember()]
        public virtual Nullable<Int64> DEPENDS_ON { get; set; }

        [DataMember()]
        public virtual Nullable<Int64> RUN_ORDER { get; set; }

        [DataMember()]
        public virtual Nullable<Int64> LATEST_TEST_MARK_ID { get; set; }

        [DataMember()]
        public virtual Nullable<Decimal> RECORD_VERSION { get; set; }

        [DataMember()]
        public virtual String ALIAS_NAME { get; set; }

        [DataMember()]
        public virtual Nullable<Int64> TEST_SUITE_ID { get; set; }

        [DataMember()]
        public Int64 T_STORYBOARD_SUMMARY_STORYBOARD_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_CASE_SUMMARY_TEST_CASE_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_PROJECT_PROJECT_ID { get; set; }

        [DataMember()]
        public  List<Int64> T_STORYBOARD_DATASET_SETTING_SETTING_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_SUITE_TEST_SUITE_ID { get; set; }

        public T_PROJ_TC_MGRDTO()
        {
        }

        public T_PROJ_TC_MGRDTO(Int64 sTORYBOARD_DETAIL_ID, Nullable<Int64> pROJECT_ID, Nullable<Int64> tEST_CASE_ID, Nullable<Int64> sTORYBOARD_ID, Nullable<Int16> rUN_TYPE, Nullable<Int64> dEPENDS_ON, Nullable<Int64> rUN_ORDER, Nullable<Int64> lATEST_TEST_MARK_ID, Nullable<Decimal> rECORD_VERSION, String aLIAS_NAME, Nullable<Int64> tEST_SUITE_ID, Int64 t_STORYBOARD_SUMMARY_STORYBOARD_ID, Int64 t_TEST_CASE_SUMMARY_TEST_CASE_ID, Int64 t_TEST_PROJECT_PROJECT_ID, List<Int64> t_STORYBOARD_DATASET_SETTING_SETTING_ID, Int64 t_TEST_SUITE_TEST_SUITE_ID)
        {
			this.STORYBOARD_DETAIL_ID = sTORYBOARD_DETAIL_ID;
			this.PROJECT_ID = pROJECT_ID;
			this.TEST_CASE_ID = tEST_CASE_ID;
			this.STORYBOARD_ID = sTORYBOARD_ID;
			this.RUN_TYPE = rUN_TYPE;
			this.DEPENDS_ON = dEPENDS_ON;
			this.RUN_ORDER = rUN_ORDER;
			this.LATEST_TEST_MARK_ID = lATEST_TEST_MARK_ID;
			this.RECORD_VERSION = rECORD_VERSION;
			this.ALIAS_NAME = aLIAS_NAME;
			this.TEST_SUITE_ID = tEST_SUITE_ID;
			this.T_STORYBOARD_SUMMARY_STORYBOARD_ID = t_STORYBOARD_SUMMARY_STORYBOARD_ID;
			this.T_TEST_CASE_SUMMARY_TEST_CASE_ID = t_TEST_CASE_SUMMARY_TEST_CASE_ID;
			this.T_TEST_PROJECT_PROJECT_ID = t_TEST_PROJECT_PROJECT_ID;
			this.T_STORYBOARD_DATASET_SETTING_SETTING_ID = t_STORYBOARD_DATASET_SETTING_SETTING_ID;
			this.T_TEST_SUITE_TEST_SUITE_ID = t_TEST_SUITE_TEST_SUITE_ID;
        }
    }
}
