//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_PROJECT_DATA_SOURCEDTO
    {
        [DataMember()]
        public Int64 PRO_DBS_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> PROJECT_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> DATA_SOURCE_ID { get; set; }

        [DataMember()]
        public Int64 T_DATA_SOURCE_DATA_SOURCE_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_PROJECT_PROJECT_ID { get; set; }

        public T_PROJECT_DATA_SOURCEDTO()
        {
        }

        public T_PROJECT_DATA_SOURCEDTO(Int64 pRO_DBS_ID, Nullable<Int64> pROJECT_ID, Nullable<Int64> dATA_SOURCE_ID, Int64 t_DATA_SOURCE_DATA_SOURCE_ID, Int64 t_TEST_PROJECT_PROJECT_ID)
        {
			this.PRO_DBS_ID = pRO_DBS_ID;
			this.PROJECT_ID = pROJECT_ID;
			this.DATA_SOURCE_ID = dATA_SOURCE_ID;
			this.T_DATA_SOURCE_DATA_SOURCE_ID = t_DATA_SOURCE_DATA_SOURCE_ID;
			this.T_TEST_PROJECT_PROJECT_ID = t_TEST_PROJECT_PROJECT_ID;
        }
    }
}
