//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:12
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_PROJ_TEST_RESULT"/> and <see cref="T_PROJ_TEST_RESULTDTO"/>.
    /// </summary>
    public static partial class T_PROJ_TEST_RESULTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_PROJ_TEST_RESULTDTO"/> converted from <see cref="T_PROJ_TEST_RESULT"/>.</param>
        static partial void OnDTO(this T_PROJ_TEST_RESULT entity, T_PROJ_TEST_RESULTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_PROJ_TEST_RESULT"/> converted from <see cref="T_PROJ_TEST_RESULTDTO"/>.</param>
        static partial void OnEntity(this T_PROJ_TEST_RESULTDTO dto, T_PROJ_TEST_RESULT entity);

        /// <summary>
        /// Converts this instance of <see cref="T_PROJ_TEST_RESULTDTO"/> to an instance of <see cref="T_PROJ_TEST_RESULT"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_PROJ_TEST_RESULTDTO"/> to convert.</param>
        public static T_PROJ_TEST_RESULT ToEntity(this T_PROJ_TEST_RESULTDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_PROJ_TEST_RESULT();

            entity.HIST_ID = dto.HIST_ID;
            entity.TEST_CASE_ID = dto.TEST_CASE_ID;
            entity.STORYBOARD_DETAIL_ID = dto.STORYBOARD_DETAIL_ID;
            entity.TEST_BEGIN_TIME = dto.TEST_BEGIN_TIME;
            entity.TEST_END_TIME = dto.TEST_END_TIME;
            entity.TEST_RESULT_IN_TEXT = dto.TEST_RESULT_IN_TEXT;
            entity.TEST_MODE = dto.TEST_MODE;
            entity.TEST_RESULT = dto.TEST_RESULT;
            entity.TESTER_ID = dto.TESTER_ID;
            entity.CREATE_TIME = dto.CREATE_TIME;
            entity.LATEST_TEST_MARK_ID = dto.LATEST_TEST_MARK_ID;
            entity.RELY_TEST_CASE_ID = dto.RELY_TEST_CASE_ID;
            entity.RESULT_ALIAS_NAME = dto.RESULT_ALIAS_NAME;
            entity.RESULT_DESC = dto.RESULT_DESC;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_PROJ_TEST_RESULT"/> to an instance of <see cref="T_PROJ_TEST_RESULTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_PROJ_TEST_RESULT"/> to convert.</param>
        public static T_PROJ_TEST_RESULTDTO ToDTO(this T_PROJ_TEST_RESULT entity)
        {
            if (entity == null) return null;

            var dto = new T_PROJ_TEST_RESULTDTO();

            dto.HIST_ID = entity.HIST_ID;
            dto.TEST_CASE_ID = entity.TEST_CASE_ID;
            dto.STORYBOARD_DETAIL_ID = entity.STORYBOARD_DETAIL_ID;
            dto.TEST_BEGIN_TIME = entity.TEST_BEGIN_TIME;
            dto.TEST_END_TIME = entity.TEST_END_TIME;
            dto.TEST_RESULT_IN_TEXT = entity.TEST_RESULT_IN_TEXT;
            dto.TEST_MODE = entity.TEST_MODE;
            dto.TEST_RESULT = entity.TEST_RESULT;
            dto.TESTER_ID = entity.TESTER_ID;
            dto.CREATE_TIME = entity.CREATE_TIME;
            dto.LATEST_TEST_MARK_ID = entity.LATEST_TEST_MARK_ID;
            dto.RELY_TEST_CASE_ID = entity.RELY_TEST_CASE_ID;
            dto.RESULT_ALIAS_NAME = entity.RESULT_ALIAS_NAME;
            dto.RESULT_DESC = entity.RESULT_DESC;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_PROJ_TEST_RESULTDTO"/> to an instance of <see cref="T_PROJ_TEST_RESULT"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_PROJ_TEST_RESULT> ToEntities(this IEnumerable<T_PROJ_TEST_RESULTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_PROJ_TEST_RESULT"/> to an instance of <see cref="T_PROJ_TEST_RESULTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_PROJ_TEST_RESULTDTO> ToDTOs(this IEnumerable<T_PROJ_TEST_RESULT> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
