//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:11
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_PROJ_TC_MGR"/> and <see cref="T_PROJ_TC_MGRDTO"/>.
    /// </summary>
    public static partial class T_PROJ_TC_MGRAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_PROJ_TC_MGRDTO"/> converted from <see cref="T_PROJ_TC_MGR"/>.</param>
        static partial void OnDTO(this T_PROJ_TC_MGR entity, T_PROJ_TC_MGRDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_PROJ_TC_MGR"/> converted from <see cref="T_PROJ_TC_MGRDTO"/>.</param>
        static partial void OnEntity(this T_PROJ_TC_MGRDTO dto, T_PROJ_TC_MGR entity);

        /// <summary>
        /// Converts this instance of <see cref="T_PROJ_TC_MGRDTO"/> to an instance of <see cref="T_PROJ_TC_MGR"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_PROJ_TC_MGRDTO"/> to convert.</param>
        public static T_PROJ_TC_MGR ToEntity(this T_PROJ_TC_MGRDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_PROJ_TC_MGR();

            entity.STORYBOARD_DETAIL_ID = dto.STORYBOARD_DETAIL_ID;
            entity.PROJECT_ID = dto.PROJECT_ID;
            entity.TEST_CASE_ID = dto.TEST_CASE_ID;
            entity.STORYBOARD_ID = dto.STORYBOARD_ID;
            entity.RUN_TYPE = dto.RUN_TYPE;
            entity.DEPENDS_ON = dto.DEPENDS_ON;
            entity.RUN_ORDER = dto.RUN_ORDER;
            entity.LATEST_TEST_MARK_ID = dto.LATEST_TEST_MARK_ID;
            entity.RECORD_VERSION = dto.RECORD_VERSION;
            entity.ALIAS_NAME = dto.ALIAS_NAME;
            entity.TEST_SUITE_ID = dto.TEST_SUITE_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_PROJ_TC_MGR"/> to an instance of <see cref="T_PROJ_TC_MGRDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_PROJ_TC_MGR"/> to convert.</param>
        public static T_PROJ_TC_MGRDTO ToDTO(this T_PROJ_TC_MGR entity)
        {
            if (entity == null) return null;

            var dto = new T_PROJ_TC_MGRDTO();

            dto.STORYBOARD_DETAIL_ID = entity.STORYBOARD_DETAIL_ID;
            dto.PROJECT_ID = entity.PROJECT_ID;
            dto.TEST_CASE_ID = entity.TEST_CASE_ID;
            dto.STORYBOARD_ID = entity.STORYBOARD_ID;
            dto.RUN_TYPE = entity.RUN_TYPE;
            dto.DEPENDS_ON = entity.DEPENDS_ON;
            dto.RUN_ORDER = entity.RUN_ORDER;
            dto.LATEST_TEST_MARK_ID = entity.LATEST_TEST_MARK_ID;
            dto.RECORD_VERSION = entity.RECORD_VERSION;
            dto.ALIAS_NAME = entity.ALIAS_NAME;
            dto.TEST_SUITE_ID = entity.TEST_SUITE_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_PROJ_TC_MGRDTO"/> to an instance of <see cref="T_PROJ_TC_MGR"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_PROJ_TC_MGR> ToEntities(this IEnumerable<T_PROJ_TC_MGRDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_PROJ_TC_MGR"/> to an instance of <see cref="T_PROJ_TC_MGRDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_PROJ_TC_MGRDTO> ToDTOs(this IEnumerable<T_PROJ_TC_MGR> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
