//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:13
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_SHARED_OBJECT_POOL"/> and <see cref="T_SHARED_OBJECT_POOLDTO"/>.
    /// </summary>
    public static partial class T_SHARED_OBJECT_POOLAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_SHARED_OBJECT_POOLDTO"/> converted from <see cref="T_SHARED_OBJECT_POOL"/>.</param>
        static partial void OnDTO(this T_SHARED_OBJECT_POOL entity, T_SHARED_OBJECT_POOLDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_SHARED_OBJECT_POOL"/> converted from <see cref="T_SHARED_OBJECT_POOLDTO"/>.</param>
        static partial void OnEntity(this T_SHARED_OBJECT_POOLDTO dto, T_SHARED_OBJECT_POOL entity);

        /// <summary>
        /// Converts this instance of <see cref="T_SHARED_OBJECT_POOLDTO"/> to an instance of <see cref="T_SHARED_OBJECT_POOL"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_SHARED_OBJECT_POOLDTO"/> to convert.</param>
        public static T_SHARED_OBJECT_POOL ToEntity(this T_SHARED_OBJECT_POOLDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_SHARED_OBJECT_POOL();

            entity.OBJECT_POOL_ID = dto.OBJECT_POOL_ID;
            entity.DATA_SUMMARY_ID = dto.DATA_SUMMARY_ID;
            entity.OBJECT_NAME = dto.OBJECT_NAME;
            entity.OBJECT_ORDER = dto.OBJECT_ORDER;
            entity.LOOP_ID = dto.LOOP_ID;
            entity.DATA_VALUE = dto.DATA_VALUE;
            entity.CREATE_TIME = dto.CREATE_TIME;
            entity.VERSION = dto.VERSION;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_SHARED_OBJECT_POOL"/> to an instance of <see cref="T_SHARED_OBJECT_POOLDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_SHARED_OBJECT_POOL"/> to convert.</param>
        public static T_SHARED_OBJECT_POOLDTO ToDTO(this T_SHARED_OBJECT_POOL entity)
        {
            if (entity == null) return null;

            var dto = new T_SHARED_OBJECT_POOLDTO();

            dto.OBJECT_POOL_ID = entity.OBJECT_POOL_ID;
            dto.DATA_SUMMARY_ID = entity.DATA_SUMMARY_ID;
            dto.OBJECT_NAME = entity.OBJECT_NAME;
            dto.OBJECT_ORDER = entity.OBJECT_ORDER;
            dto.LOOP_ID = entity.LOOP_ID;
            dto.DATA_VALUE = entity.DATA_VALUE;
            dto.CREATE_TIME = entity.CREATE_TIME;
            dto.VERSION = entity.VERSION;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_SHARED_OBJECT_POOLDTO"/> to an instance of <see cref="T_SHARED_OBJECT_POOL"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_SHARED_OBJECT_POOL> ToEntities(this IEnumerable<T_SHARED_OBJECT_POOLDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_SHARED_OBJECT_POOL"/> to an instance of <see cref="T_SHARED_OBJECT_POOLDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_SHARED_OBJECT_POOLDTO> ToDTOs(this IEnumerable<T_SHARED_OBJECT_POOL> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
