//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:03
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_TEST_CASE_SUMMARY"/> and <see cref="T_TEST_CASE_SUMMARYDTO"/>.
    /// </summary>
    public static partial class T_TEST_CASE_SUMMARYAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_CASE_SUMMARYDTO"/> converted from <see cref="T_TEST_CASE_SUMMARY"/>.</param>
        static partial void OnDTO(this T_TEST_CASE_SUMMARY entity, T_TEST_CASE_SUMMARYDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_CASE_SUMMARY"/> converted from <see cref="T_TEST_CASE_SUMMARYDTO"/>.</param>
        static partial void OnEntity(this T_TEST_CASE_SUMMARYDTO dto, T_TEST_CASE_SUMMARY entity);

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_CASE_SUMMARYDTO"/> to an instance of <see cref="T_TEST_CASE_SUMMARY"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_CASE_SUMMARYDTO"/> to convert.</param>
        public static T_TEST_CASE_SUMMARY ToEntity(this T_TEST_CASE_SUMMARYDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_TEST_CASE_SUMMARY();

            entity.TEST_CASE_ID = dto.TEST_CASE_ID;
            entity.TEST_CASE_NAME = dto.TEST_CASE_NAME;
            entity.TEST_STEP_DESCRIPTION = dto.TEST_STEP_DESCRIPTION;
            entity.TEST_STEP_CREATOR = dto.TEST_STEP_CREATOR;
            entity.TEST_STEP_CREATE_TIME = dto.TEST_STEP_CREATE_TIME;
            entity.USAGE_STATUS = dto.USAGE_STATUS;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_CASE_SUMMARY"/> to an instance of <see cref="T_TEST_CASE_SUMMARYDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_CASE_SUMMARY"/> to convert.</param>
        public static T_TEST_CASE_SUMMARYDTO ToDTO(this T_TEST_CASE_SUMMARY entity)
        {
            if (entity == null) return null;

            var dto = new T_TEST_CASE_SUMMARYDTO();

            dto.TEST_CASE_ID = entity.TEST_CASE_ID;
            dto.TEST_CASE_NAME = entity.TEST_CASE_NAME;
            dto.TEST_STEP_DESCRIPTION = entity.TEST_STEP_DESCRIPTION;
            dto.TEST_STEP_CREATOR = entity.TEST_STEP_CREATOR;
            dto.TEST_STEP_CREATE_TIME = entity.TEST_STEP_CREATE_TIME;
            dto.USAGE_STATUS = entity.USAGE_STATUS;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_CASE_SUMMARYDTO"/> to an instance of <see cref="T_TEST_CASE_SUMMARY"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_TEST_CASE_SUMMARY> ToEntities(this IEnumerable<T_TEST_CASE_SUMMARYDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_CASE_SUMMARY"/> to an instance of <see cref="T_TEST_CASE_SUMMARYDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_TEST_CASE_SUMMARYDTO> ToDTOs(this IEnumerable<T_TEST_CASE_SUMMARY> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
