//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_TEST_SUITEDTO
    {
        [DataMember()]
        public Int64 TEST_SUITE_ID { get; set; }

        [DataMember()]
        public String TEST_SUITE_NAME { get; set; }

        [DataMember()]
        public String TEST_SUITE_DESCRIPTION { get; set; }

        [DataMember()]
        public List<Int64> REL_TEST_CASE_TEST_SUITE_RELATIONSHIP_ID { get; set; }

        [DataMember()]
        public List<Int64> REL_TEST_SUIT_PROJECT_RELATIONSHIP_ID { get; set; }

        [DataMember()]
        public List<Int64> T_PROJ_TC_MGR_STORYBOARD_DETAIL_ID { get; set; }

        public T_TEST_SUITEDTO()
        {
        }

        public T_TEST_SUITEDTO(Int64 tEST_SUITE_ID, String tEST_SUITE_NAME, String tEST_SUITE_DESCRIPTION, List<Int64> rEL_TEST_CASE_TEST_SUITE_RELATIONSHIP_ID, List<Int64> rEL_TEST_SUIT_PROJECT_RELATIONSHIP_ID, List<Int64> t_PROJ_TC_MGR_STORYBOARD_DETAIL_ID)
        {
			this.TEST_SUITE_ID = tEST_SUITE_ID;
			this.TEST_SUITE_NAME = tEST_SUITE_NAME;
			this.TEST_SUITE_DESCRIPTION = tEST_SUITE_DESCRIPTION;
			this.REL_TEST_CASE_TEST_SUITE_RELATIONSHIP_ID = rEL_TEST_CASE_TEST_SUITE_RELATIONSHIP_ID;
			this.REL_TEST_SUIT_PROJECT_RELATIONSHIP_ID = rEL_TEST_SUIT_PROJECT_RELATIONSHIP_ID;
			this.T_PROJ_TC_MGR_STORYBOARD_DETAIL_ID = t_PROJ_TC_MGR_STORYBOARD_DETAIL_ID;
        }
    }
}
