//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:16
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class V_PROJ_TS_TC_FULLVISIONDTO
    {
        [DataMember()]
        public Int64 TEST_SUITE_ID { get; set; }

        [DataMember()]
        public String TEST_SUITE_NAME { get; set; }

        [DataMember()]
        public String TEST_SUITE_DESCRIPTION { get; set; }

        [DataMember()]
        public Int64 TEST_CASE_ID { get; set; }

        [DataMember()]
        public String TEST_CASE_NAME { get; set; }

        [DataMember()]
        public Nullable<DateTime> TEST_STEP_CREATE_TIME { get; set; }

        [DataMember()]
        public String TEST_STEP_CREATOR { get; set; }

        [DataMember()]
        public String TEST_STEP_DESCRIPTION { get; set; }

        [DataMember()]
        public Nullable<Int32> USAGE_STATUS { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_DATE { get; set; }

        [DataMember()]
        public String CREATOR { get; set; }

        [DataMember()]
        public String PROJECT_DESCRIPTION { get; set; }

        [DataMember()]
        public Int32 PROJECT_ID { get; set; }

        [DataMember()]
        public String PROJECT_NAME { get; set; }

        [DataMember()]
        public Nullable<Int32> STATUS { get; set; }

        [DataMember()]
        public String DATA_ALIAS { get; set; }

        [DataMember()]
        public Int64 DATA_SUMMARY_ID { get; set; }

        [DataMember()]
        public Nullable<Int32> DATA_AVAILABLE_MARK { get; set; }

        [DataMember()]
        public Nullable<Int32> DATA_VERSION { get; set; }

        [DataMember()]
        public Nullable<Int32> DATA_STATUS { get; set; }

        [DataMember()]
        public Nullable<Int32> DATA_SET_TYPE { get; set; }

        [DataMember()]
        public String DATASET_DESCRIPTION { get; set; }

        public V_PROJ_TS_TC_FULLVISIONDTO()
        {
        }

        public V_PROJ_TS_TC_FULLVISIONDTO(Int64 tEST_SUITE_ID, String tEST_SUITE_NAME, String tEST_SUITE_DESCRIPTION, Int64 tEST_CASE_ID, String tEST_CASE_NAME, Nullable<DateTime> tEST_STEP_CREATE_TIME, String tEST_STEP_CREATOR, String tEST_STEP_DESCRIPTION, Nullable<Int32> uSAGE_STATUS, Nullable<DateTime> cREATE_DATE, String cREATOR, String pROJECT_DESCRIPTION, Int32 pROJECT_ID, String pROJECT_NAME, Nullable<Int32> sTATUS, String dATA_ALIAS, Int64 dATA_SUMMARY_ID, Nullable<Int32> dATA_AVAILABLE_MARK, Nullable<Int32> dATA_VERSION, Nullable<Int32> dATA_STATUS, Nullable<Int32> dATA_SET_TYPE, String dATASET_DESCRIPTION)
        {
			this.TEST_SUITE_ID = tEST_SUITE_ID;
			this.TEST_SUITE_NAME = tEST_SUITE_NAME;
			this.TEST_SUITE_DESCRIPTION = tEST_SUITE_DESCRIPTION;
			this.TEST_CASE_ID = tEST_CASE_ID;
			this.TEST_CASE_NAME = tEST_CASE_NAME;
			this.TEST_STEP_CREATE_TIME = tEST_STEP_CREATE_TIME;
			this.TEST_STEP_CREATOR = tEST_STEP_CREATOR;
			this.TEST_STEP_DESCRIPTION = tEST_STEP_DESCRIPTION;
			this.USAGE_STATUS = uSAGE_STATUS;
			this.CREATE_DATE = cREATE_DATE;
			this.CREATOR = cREATOR;
			this.PROJECT_DESCRIPTION = pROJECT_DESCRIPTION;
			this.PROJECT_ID = pROJECT_ID;
			this.PROJECT_NAME = pROJECT_NAME;
			this.STATUS = sTATUS;
			this.DATA_ALIAS = dATA_ALIAS;
			this.DATA_SUMMARY_ID = dATA_SUMMARY_ID;
			this.DATA_AVAILABLE_MARK = dATA_AVAILABLE_MARK;
			this.DATA_VERSION = dATA_VERSION;
			this.DATA_STATUS = dATA_STATUS;
			this.DATA_SET_TYPE = dATA_SET_TYPE;
			this.DATASET_DESCRIPTION = dATASET_DESCRIPTION;
        }
    }
}
