//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:14
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class V_STB_PROJ_APP_FULLVISIONDTO
    {
        [DataMember()]
        public Nullable<Int64> PROJECT_ID { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_TIME { get; set; }

        [DataMember()]
        public Nullable<Int64> CREATER { get; set; }

        [DataMember()]
        public String DESCRIPTION { get; set; }

        [DataMember()]
        public Int64 STORYBOARD_ID { get; set; }

        [DataMember()]
        public String STORYBOARD_NAME { get; set; }

        [DataMember()]
        public Int64 APPLICATION_ID { get; set; }

        [DataMember()]
        public String APP_SHORT_NAME { get; set; }

        [DataMember()]
        public Nullable<Int16> APPLICATION_TYPE_ID { get; set; }

        public V_STB_PROJ_APP_FULLVISIONDTO()
        {
        }

        public V_STB_PROJ_APP_FULLVISIONDTO(Nullable<Int64> pROJECT_ID, Nullable<DateTime> cREATE_TIME, Nullable<Int64> cREATER, String dESCRIPTION, Int64 sTORYBOARD_ID, String sTORYBOARD_NAME, Int64 aPPLICATION_ID, String aPP_SHORT_NAME, Nullable<Int16> aPPLICATION_TYPE_ID)
        {
			this.PROJECT_ID = pROJECT_ID;
			this.CREATE_TIME = cREATE_TIME;
			this.CREATER = cREATER;
			this.DESCRIPTION = dESCRIPTION;
			this.STORYBOARD_ID = sTORYBOARD_ID;
			this.STORYBOARD_NAME = sTORYBOARD_NAME;
			this.APPLICATION_ID = aPPLICATION_ID;
			this.APP_SHORT_NAME = aPP_SHORT_NAME;
			this.APPLICATION_TYPE_ID = aPPLICATION_TYPE_ID;
        }
    }
}
