//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:08
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="V_TEST_STEPS_FULLVISION"/> and <see cref="V_TEST_STEPS_FULLVISIONDTO"/>.
    /// </summary>
    public static partial class V_TEST_STEPS_FULLVISIONAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="V_TEST_STEPS_FULLVISIONDTO"/> converted from <see cref="V_TEST_STEPS_FULLVISION"/>.</param>
        static partial void OnDTO(this V_TEST_STEPS_FULLVISION entity, V_TEST_STEPS_FULLVISIONDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="V_TEST_STEPS_FULLVISION"/> converted from <see cref="V_TEST_STEPS_FULLVISIONDTO"/>.</param>
        static partial void OnEntity(this V_TEST_STEPS_FULLVISIONDTO dto, V_TEST_STEPS_FULLVISION entity);

        /// <summary>
        /// Converts this instance of <see cref="V_TEST_STEPS_FULLVISIONDTO"/> to an instance of <see cref="V_TEST_STEPS_FULLVISION"/>.
        /// </summary>
        /// <param name="dto"><see cref="V_TEST_STEPS_FULLVISIONDTO"/> to convert.</param>
        public static V_TEST_STEPS_FULLVISION ToEntity(this V_TEST_STEPS_FULLVISIONDTO dto)
        {
            if (dto == null) return null;

            var entity = new V_TEST_STEPS_FULLVISION();

            entity.TEST_CASE_ID = dto.TEST_CASE_ID;
            entity.TEST_CASE_NAME = dto.TEST_CASE_NAME;
            entity.KEY_WORD_ID = dto.KEY_WORD_ID;
            entity.KEY_WORD_NAME = dto.KEY_WORD_NAME;
            entity.OBJECT_HAPPY_NAME = dto.OBJECT_HAPPY_NAME;
            entity.OBJECT_ID = dto.OBJECT_ID;
            entity.OBJECT_TYPE = dto.OBJECT_TYPE;
            entity.QUICK_ACCESS = dto.QUICK_ACCESS;
            entity.ENUM_TYPE = dto.ENUM_TYPE;
            entity.APPLICATION_ID = dto.APPLICATION_ID;
            entity.OBJECT_NAME_ID = dto.OBJECT_NAME_ID;
            entity.TYPE_NAME = dto.TYPE_NAME;
            entity.COLUMN_ROW_SETTING = dto.COLUMN_ROW_SETTING;
            entity.STEPS_ID = dto.STEPS_ID;
            entity.COMMENTINFO = dto.COMMENTINFO;
            entity.IS_RUNNABLE = dto.IS_RUNNABLE;
            entity.RUN_ORDER = dto.RUN_ORDER;
            entity.VALUE_SETTING = dto.VALUE_SETTING;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="V_TEST_STEPS_FULLVISION"/> to an instance of <see cref="V_TEST_STEPS_FULLVISIONDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="V_TEST_STEPS_FULLVISION"/> to convert.</param>
        public static V_TEST_STEPS_FULLVISIONDTO ToDTO(this V_TEST_STEPS_FULLVISION entity)
        {
            if (entity == null) return null;

            var dto = new V_TEST_STEPS_FULLVISIONDTO();

            dto.TEST_CASE_ID = entity.TEST_CASE_ID;
            dto.TEST_CASE_NAME = entity.TEST_CASE_NAME;
            dto.KEY_WORD_ID = entity.KEY_WORD_ID;
            dto.KEY_WORD_NAME = entity.KEY_WORD_NAME;
            dto.OBJECT_HAPPY_NAME = entity.OBJECT_HAPPY_NAME;
            dto.OBJECT_ID = entity.OBJECT_ID;
            dto.OBJECT_TYPE = entity.OBJECT_TYPE;
            dto.QUICK_ACCESS = entity.QUICK_ACCESS;
            dto.ENUM_TYPE = entity.ENUM_TYPE;
            dto.APPLICATION_ID = entity.APPLICATION_ID;
            dto.OBJECT_NAME_ID = entity.OBJECT_NAME_ID;
            dto.TYPE_NAME = entity.TYPE_NAME;
            dto.COLUMN_ROW_SETTING = entity.COLUMN_ROW_SETTING;
            dto.STEPS_ID = entity.STEPS_ID;
            dto.COMMENTINFO = entity.COMMENTINFO;
            dto.IS_RUNNABLE = entity.IS_RUNNABLE;
            dto.RUN_ORDER = entity.RUN_ORDER;
            dto.VALUE_SETTING = entity.VALUE_SETTING;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="V_TEST_STEPS_FULLVISIONDTO"/> to an instance of <see cref="V_TEST_STEPS_FULLVISION"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<V_TEST_STEPS_FULLVISION> ToEntities(this IEnumerable<V_TEST_STEPS_FULLVISIONDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="V_TEST_STEPS_FULLVISION"/> to an instance of <see cref="V_TEST_STEPS_FULLVISIONDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<V_TEST_STEPS_FULLVISIONDTO> ToDTOs(this IEnumerable<V_TEST_STEPS_FULLVISION> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
