//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class V_USER_COMPANYDTO
    {
        [DataMember()]
        public Decimal TESTER_ID { get; set; }

        [DataMember()]
        public String TESTER_NAME_LAST { get; set; }

        [DataMember()]
        public String TESTER_NAME_M { get; set; }

        [DataMember()]
        public String TESTER_NAME_F { get; set; }

        [DataMember()]
        public String TESTER_LOGIN_NAME { get; set; }

        [DataMember()]
        public String TESTER_PWD { get; set; }

        [DataMember()]
        public Nullable<Decimal> AVAILABLE_MARK { get; set; }

        [DataMember()]
        public String TESTER_MAIL { get; set; }

        [DataMember()]
        public String TESTER_NUMBER { get; set; }

        [DataMember()]
        public Decimal COMPANY_ID { get; set; }

        [DataMember()]
        public String TESTER_DESC { get; set; }

        [DataMember()]
        public String COMPANY_NAME { get; set; }

        [DataMember()]
        public String COMPANY_DESC { get; set; }

        [DataMember()]
        public String COMPANY_ADDRESS { get; set; }

        [DataMember()]
        public String COMPANY_NUMBER { get; set; }

        [DataMember()]
        public Nullable<Decimal> COMPANY_AVAILABLE_MARK { get; set; }

        public V_USER_COMPANYDTO()
        {
        }

        public V_USER_COMPANYDTO(Decimal tESTER_ID, String tESTER_NAME_LAST, String tESTER_NAME_M, String tESTER_NAME_F, String tESTER_LOGIN_NAME, String tESTER_PWD, Nullable<Decimal> aVAILABLE_MARK, String tESTER_MAIL, String tESTER_NUMBER, Decimal cOMPANY_ID, String tESTER_DESC, String cOMPANY_NAME, String cOMPANY_DESC, String cOMPANY_ADDRESS, String cOMPANY_NUMBER, Nullable<Decimal> cOMPANY_AVAILABLE_MARK)
        {
			this.TESTER_ID = tESTER_ID;
			this.TESTER_NAME_LAST = tESTER_NAME_LAST;
			this.TESTER_NAME_M = tESTER_NAME_M;
			this.TESTER_NAME_F = tESTER_NAME_F;
			this.TESTER_LOGIN_NAME = tESTER_LOGIN_NAME;
			this.TESTER_PWD = tESTER_PWD;
			this.AVAILABLE_MARK = aVAILABLE_MARK;
			this.TESTER_MAIL = tESTER_MAIL;
			this.TESTER_NUMBER = tESTER_NUMBER;
			this.COMPANY_ID = cOMPANY_ID;
			this.TESTER_DESC = tESTER_DESC;
			this.COMPANY_NAME = cOMPANY_NAME;
			this.COMPANY_DESC = cOMPANY_DESC;
			this.COMPANY_ADDRESS = cOMPANY_ADDRESS;
			this.COMPANY_NUMBER = cOMPANY_NUMBER;
			this.COMPANY_AVAILABLE_MARK = cOMPANY_AVAILABLE_MARK;
        }
    }
}
