//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/04/15 - 23:20:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_TEST_PROJECTDTO
    {
        [DataMember()]
        public Int64 PROJECT_ID { get; set; }

        [DataMember()]
        public String PROJECT_NAME { get; set; }

        [DataMember()]
        public String PROJECT_DESCRIPTION { get; set; }

        [DataMember()]
        public String CREATOR { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_DATE { get; set; }

        [DataMember()]
        public Nullable<Int16> STATUS { get; set; }

        [DataMember()]
        public List<Int64> REL_APP_PROJ_RELATIONSHIP_ID { get; set; }

        [DataMember()]
        public List<Int64> REL_TEST_SUIT_PROJECT_RELATIONSHIP_ID { get; set; }

        [DataMember()]
        public List<Int64> T_PROJECT_DATA_SOURCE_PRO_DBS_ID { get; set; }

        public T_TEST_PROJECTDTO()
        {
        }

        public T_TEST_PROJECTDTO(Int64 pROJECT_ID, String pROJECT_NAME, String pROJECT_DESCRIPTION, String cREATOR, Nullable<DateTime> cREATE_DATE, Nullable<Int16> sTATUS, List<Int64> rEL_APP_PROJ_RELATIONSHIP_ID, List<Int64> rEL_TEST_SUIT_PROJECT_RELATIONSHIP_ID, List<Int64> t_PROJECT_DATA_SOURCE_PRO_DBS_ID)
        {
			this.PROJECT_ID = pROJECT_ID;
			this.PROJECT_NAME = pROJECT_NAME;
			this.PROJECT_DESCRIPTION = pROJECT_DESCRIPTION;
			this.CREATOR = cREATOR;
			this.CREATE_DATE = cREATE_DATE;
			this.STATUS = sTATUS;
			this.REL_APP_PROJ_RELATIONSHIP_ID = rEL_APP_PROJ_RELATIONSHIP_ID;
			this.REL_TEST_SUIT_PROJECT_RELATIONSHIP_ID = rEL_TEST_SUIT_PROJECT_RELATIONSHIP_ID;
			this.T_PROJECT_DATA_SOURCE_PRO_DBS_ID = t_PROJECT_DATA_SOURCE_PRO_DBS_ID;
        }
    }
}
