/*
Deployment script for FHLB_MARS1_021225

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;

GO
create view  V_MARS_REPORT_TASK as 
 select t.Id,t.TaskName,t.ExecuteTime,t.ExecuteStatus,t.CreateTime,t.ExecuteImmediately,t.ReportPath,t.ReportMsg ,t.ReportStatus,
 stuff((select ',' +  CONVERT(varchar, r.FolderId)   from T_MARS_REPORT r
 where r.ReportTaskId =t.id  for xml path('')) ,1,1,'') as FolderIds,
 stuff((select ',' +  f.FOLDERNAME   from T_MARS_REPORT rr  , T_TEST_FOLDER f  
 where rr.FolderId =f.FolderId and rr.ReportTaskId =t.id order by f.FOLDERNAME for xml path('')) ,1,1,'') as FolderNames
 from t_mars_report_task  t;
GO
PRINT N'Creating View [dbo].[V_TESTSUITE_APP_AGG]...';


GO
CREATE VIEW V_TESTSUITE_APP_AGG AS
select distinct TEST_SUITE_ID,
    STUFF((select ','+APP_SHORT_NAME from (
		SELECT distinct t.TEST_SUITE_ID,t.TEST_SUITE_NAME,tapp.APP_SHORT_NAME, tapp.APPLICATION_ID FROM 
			T_TEST_SUITE t
			INNER JOIN REL_TEST_CASE_TEST_SUITE reltcts ON reltcts.TEST_SUITE_ID = t.TEST_SUITE_ID
			INNER JOIN REL_APP_TESTCASE reapp ON reapp.test_case_id = reltcts.TEST_CASE_ID 
			INNER JOIN T_REGISTERED_APPS tapp ON tapp.APPLICATION_ID = reapp.APPLICATION_ID
	) sub
	where sub.TEST_SUITE_ID= s.TEST_SUITE_ID
	order by sub.APP_SHORT_NAME
	for xml path(''), type).value('.', 'NVARCHAR(MAX)'),1,1,'') as APPLICATIONNAME
from T_TEST_SUITE s
GO
PRINT N'Update complete.';


GO
