/*
Deployment script for FHLB_MARS1_021225

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
PRINT N'Altering Table [dbo].[T_DATA_SOURCE]...';


GO
ALTER TABLE [dbo].[T_DATA_SOURCE]
    ADD [COMPARE_TYPE] BIGINT        CONSTRAINT [DATA_SOURC_TBL_DEFAULT_COMPTYP] DEFAULT ((0)) NULL,
        [NOTE]         VARCHAR (256) NULL;


GO
PRINT N'Altering Table [dbo].[TBLSTGCOMPAREPARAM]...';


GO
ALTER TABLE [dbo].[TBLSTGCOMPAREPARAM]
    ADD [COMPARETYPE] VARCHAR (128) NULL,
        [NOTE]        VARCHAR (256) NULL;


GO
PRINT N'Creating Table [dbo].[T_COMPARE_RUN_RESULT]...';


GO
CREATE TABLE [dbo].[T_COMPARE_RUN_RESULT] (
    [ID]          BIGINT        NOT NULL,
    [UUID]        VARCHAR (64)  NOT NULL,
    [COMPARE_ID]  VARCHAR (200) NOT NULL,
    [CREATE_TIME] DATETIME      NOT NULL,
    [STATUS]      INT           NOT NULL,
    [FILE_PATH]   VARCHAR (500) NULL,
    [END_TIME]    DATETIME      NULL,
    [NOTE]        VARCHAR (500) NULL,
    [MSG]         VARCHAR (500) NULL,
    CONSTRAINT [PK_T_COMPARE_RUN_RESULT] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[T_MARS_REPORT]...';


GO
CREATE TABLE [dbo].[T_MARS_REPORT] (
    [Id]           BIGINT   NOT NULL,
    [FolderId]     BIGINT   NOT NULL,
    [ReportTaskId] BIGINT   NOT NULL,
    [CreateTime]   DATETIME NOT NULL,
    CONSTRAINT [PK_T_MARS_REPORT] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[T_MARS_REPORT_GROUP]...';


GO
CREATE TABLE [dbo].[T_MARS_REPORT_GROUP] (
    [ID]          BIGINT        NOT NULL,
    [GROUP_TYPE]  VARCHAR (32)  NULL,
    [GROUP_NAME]  VARCHAR (64)  NULL,
    [DESCRIPTION] VARCHAR (200) NULL,
    CONSTRAINT [PK_T_MARS_REPORT_GROUP] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[T_MARS_REPORT_TASK]...';


GO
CREATE TABLE [dbo].[T_MARS_REPORT_TASK] (
    [Id]                 BIGINT        NOT NULL,
    [TaskName]           VARCHAR (200) NOT NULL,
    [ExecuteTime]        DATETIME      NOT NULL,
    [ExecuteStatus]      INT           NOT NULL,
    [CreateTime]         DATETIME      NOT NULL,
    [ExecuteImmediately] INT           NOT NULL,
    [ReportPath]         VARCHAR (500) NULL,
    [ReportStatus]       INT           NULL,
    [ReportMsg]          VARCHAR (MAX) NULL,
    CONSTRAINT [PK_T_MARS_REPORT_TASK] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[TEMP_IMPORT_APP]...';


GO
CREATE TABLE [dbo].[TEMP_IMPORT_APP] (
    [ID]                BIGINT        NOT NULL,
    [BATCHID]           BIGINT        NOT NULL,
    [APPNAME]           VARCHAR (64)  NULL,
    [PROCESSIDENTIFIER] VARCHAR (64)  NULL,
    [STARTERPATH]       VARCHAR (200) NULL,
    [STARTERCMD]        VARCHAR (200) NULL,
    [VERSION]           VARCHAR (32)  NULL,
    [COMMENT]           VARCHAR (200) NULL,
    [APPTYPE]           VARCHAR (32)  NULL,
    [RECORDBY]          VARCHAR (64)  NULL,
    [EXTRAREQUIREMENT]  VARCHAR (64)  NULL,
    [MODE]              VARCHAR (16)  NULL,
    [EXPLORERBIT]       VARCHAR (16)  NULL,
    CONSTRAINT [PK_TEMP_IMPORT_APP] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[TEMP_IMPORT_KEYWORD]...';


GO
CREATE TABLE [dbo].[TEMP_IMPORT_KEYWORD] (
    [ID]               BIGINT        NOT NULL,
    [KEYWORD_NAME]     VARCHAR (64)  NULL,
    [NAME_DESCRIPTION] VARCHAR (200) NULL,
    [APPLICATION_TYPE] VARCHAR (64)  NULL,
    [DATA_TYPE]        INT           NULL,
    [BATCH_ID]         BIGINT        NULL,
    CONSTRAINT [PK_TEMP_IMPORT_KEYWORD] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[tmp_quick_access_for_split]...';


GO
CREATE TABLE [dbo].[tmp_quick_access_for_split] (
    [TEST_CASE_ID]      BIGINT         NOT NULL,
    [RUN_ORDER]         INT            NULL,
    [Quick_Access]      VARCHAR (512)  NULL,
    [Quick_Access_Line] VARCHAR (8000) NULL
);


GO
PRINT N'Creating Table [dbo].[TMP_STEP_FULLVISION]...';


GO
CREATE TABLE [dbo].[TMP_STEP_FULLVISION] (
    [TEST_CASE_ID]       BIGINT        NOT NULL,
    [TEST_CASE_NAME]     VARCHAR (64)  NULL,
    [KEY_WORD_ID]        BIGINT        NOT NULL,
    [KEY_WORD_NAME]      VARCHAR (255) NULL,
    [OBJECT_HAPPY_NAME]  VARCHAR (256) NULL,
    [OBJECT_ID]          BIGINT        NULL,
    [OBJECT_TYPE]        VARCHAR (32)  NULL,
    [QUICK_ACCESS]       VARCHAR (512) NULL,
    [ENUM_TYPE]          VARCHAR (100) NULL,
    [APPLICATION_ID]     BIGINT        NULL,
    [OBJECT_NAME_ID]     BIGINT        NULL,
    [TYPE_NAME]          VARCHAR (32)  NULL,
    [STEPS_ID]           BIGINT        NULL,
    [COLUMN_ROW_SETTING] VARCHAR (128) NULL,
    [COMMENTINFO]        VARCHAR (128) NULL,
    [IS_RUNNABLE]        INT           NULL,
    [RUN_ORDER]          INT           NULL,
    [VALUE_SETTING]      VARCHAR (128) NULL,
    [WORKFLOW_POSITION]  VARCHAR (64)  NULL,
    [CREATETIME]         DATETIME2 (7) NULL
);


GO
PRINT N'Refreshing View [dbo].[V_STORYBOARD_DETAIL]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[V_STORYBOARD_DETAIL]';


GO
PRINT N'Refreshing View [dbo].[V_STORYBOARD_TEST_FULLVIEW]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[V_STORYBOARD_TEST_FULLVIEW]';


GO
PRINT N'Refreshing View [dbo].[V_STORYBOARD_TEST_FULLVISION]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[V_STORYBOARD_TEST_FULLVISION]';


GO
PRINT N'Refreshing View [dbo].[V_TESTSTORYBOARD_SUMMARY]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[V_TESTSTORYBOARD_SUMMARY]';


GO
PRINT N'Refreshing Procedure [dbo].[SP_EXPORT_ALL_STORYBOARDS]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[SP_EXPORT_ALL_STORYBOARDS]';


GO
PRINT N'Refreshing Procedure [dbo].[SP_EXPORT_PROJ_STORYBOARD]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[SP_EXPORT_PROJ_STORYBOARD]';


GO
PRINT N'Refreshing Procedure [dbo].[SP_EXPORT_STORYBOARD]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[SP_EXPORT_STORYBOARD]';


GO
PRINT N'Refreshing Procedure [dbo].[SP_EXPORT_STORYBOARDNEW]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[SP_EXPORT_STORYBOARDNEW]';


GO
PRINT N'Refreshing Procedure [dbo].[SP_EXPORT_VARIABLE]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[SP_EXPORT_VARIABLE]';


GO
PRINT N'Refreshing Procedure [dbo].[SP_GET_STORYBOARD_DETAILS]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[SP_GET_STORYBOARD_DETAILS]';


GO
PRINT N'Refreshing Procedure [dbo].[SP_SaveStoryboard]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[SP_SaveStoryboard]';


GO
PRINT N'Refreshing Procedure [dbo].[USP_FEEDPROCESSMAPPING_MODE_D]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[USP_FEEDPROCESSMAPPING_MODE_D]';


GO
PRINT N'Refreshing Procedure [dbo].[USP_MAPPING_VALIDATION]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[USP_MAPPING_VALIDATION]';


GO
PRINT N'Refreshing Procedure [dbo].[SP_EXPORT_COMPAREPARAM]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[SP_EXPORT_COMPAREPARAM]';


GO
PRINT N'Refreshing Procedure [dbo].[SP_IMPORT_FILE_COMPAREPARAM]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[SP_IMPORT_FILE_COMPAREPARAM]';


GO
PRINT N'Update complete.';


GO
