//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_CASE_SUMMARY
    {
        public T_TEST_CASE_SUMMARY()
        {
            this.REL_TEST_CASE_TEST_SUITE = new HashSet<REL_TEST_CASE_TEST_SUITE>();
            this.T_TEST_REPORT = new HashSet<T_TEST_REPORT>();
            this.T_TEST_STEPS = new HashSet<T_TEST_STEPS>();
        }
    
        public long TEST_CASE_ID { get; set; }
        public string TEST_CASE_NAME { get; set; }
        public string TEST_STEP_DESCRIPTION { get; set; }
        public string TEST_STEP_CREATOR { get; set; }
        public Nullable<System.DateTime> TEST_STEP_CREATE_TIME { get; set; }
        public Nullable<short> USAGE_STATUS { get; set; }
    
        public virtual ICollection<REL_TEST_CASE_TEST_SUITE> REL_TEST_CASE_TEST_SUITE { get; set; }
        public virtual ICollection<T_TEST_REPORT> T_TEST_REPORT { get; set; }
        public virtual ICollection<T_TEST_STEPS> T_TEST_STEPS { get; set; }
    }
}
