//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsTestFrame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeywordsDef {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeywordsDef() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarsTestFrame.Properties.KeywordsDef", typeof(KeywordsDef).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function ClickButton(Identifier,Data,RC,Data_TC)	
        ///	Dim uThere,uEnabled,uText
        ///	Dim m_happy_env, m_happy   
        ///	Dim mDeskPhoto	
        ///	On Error Resume Next
        ///	ClickButton = False	
        ///	Set  m_happy_env = environment.Value(&quot;INST_CURRENT_OBJ&quot;)
        ///	m_happy = m_happy_env.m_strObject	
        ///	If Data = &quot;&quot; Then
        ///		Data = Data_TC
        ///	End If	
        ///	Reporter.Filter = rfEnableErrorsAndWarnings 	
        ///	Call u_WriteOneLine2LogFile(&quot;INFO&quot;,&quot;Before exist&quot;)
        ///	Execute &quot;uThere =&quot; &amp;  Identifier &amp; &quot;.exist(0)&quot;
        ///	If Not Catch(Err.number,Err.description)Then [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _QTP_KEYWORDS_CLICKBUTTON {
            get {
                return ResourceManager.GetString("_QTP_KEYWORDS_CLICKBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function FillEdit(Identifier,Data,RC,ByRef Data_TC)
        ///   &apos; Enters data into a edit box, Editor or a multi-line data box.
        ///   Dim uThere,uEnabled,uText
        ///   Dim m_happy_env, m_happy
        ///   Dim strErrorInfo, mDeskPhoto
        ///
        ///   On Error Resume Next
        ///   FillEdit = False
        ///
        ///   Call u_WirteOneLine2LogFile(&quot;INFO&quot;,&quot;Starting FillEdit Keyword&quot;)
        ///
        ///     &apos;Get the Happy Name
        ///&apos;	Set  m_happy_env = environment.Value(&quot;INST_CURRENT_OBJ&quot;)
        ///&apos;	m_happy = m_happy_env.m_strObject
        ///
        ///	&apos;If the value in the Test Case column  is blank then  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _QTP_KEYWORDS_FILLEDIT {
            get {
                return ResourceManager.GetString("_QTP_KEYWORDS_FILLEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function KillSummit(Identifier,Data,RC,Data_TC)
        ///   KillSummit = False
        ///   	&apos;If the value in the Test Case column  is blank then use the data from the Data Workbook. 
        ///	If Data = &quot;&quot; Then
        ///		Data = Data_TC
        ///	End If
        ///
        ///	Reporter.Filter = rfEnableErrorsAndWarnings &apos; Send only Errors and Warnings to the QTP log.
        ///
        ///	&apos;Kill open versions of Summit
        ///	SystemUtil.CloseProcessByName(&quot;SummitFT.exe&quot;)
        ///	If Not Catch(err.number,err.description)Then : Exit Function
        ///
        ///	Reporter.Filter = rfEnableAll  &apos; Send All messages to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _QTP_KEYWORDS_KILLSUMMIT {
            get {
                return ResourceManager.GetString("_QTP_KEYWORDS_KILLSUMMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function PegWindow(strKeyWord,object,column_row,strValue)
        ///	PegWindow = 0
        ///End Function.
        /// </summary>
        internal static string _QTP_KEYWORDS_PEGWINDOW {
            get {
                return ResourceManager.GetString("_QTP_KEYWORDS_PEGWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function SnapShot(Identifier,Data,RC,Data_TC)
        ///	Dim fso
        ///	Dim m_happy_env, m_happy
        ///	Dim mDeskPhoto
        ///	
        ///	SnapShot = False
        ///	
        ///	Set  m_happy_env = environment.Value(&quot;INST_CURRENT_OBJ&quot;)
        ///	m_happy = m_happy_env.m_strObject
        ///	
        ///	Dim BitmapFileName
        ///	On Error Resume Next
        ///	If Data = &quot;&quot; Then
        ///		Data = Data_TC
        ///	End If
        ///	Set fso = CreateObject(&quot;scripting.FileSystemObject&quot;)
        ///	If Not fso.FolderExists(&quot;d:\Bitmaps&quot;) Then
        ///		fso.CreateFolder(&quot;d:\Bitmaps&quot;)
        ///	End If
        ///	BitmapFileName = &quot;d:\Bitmaps\SnapShot_&quot; &amp; Year(Now) &amp; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _QTP_KEYWORDS_SNAPSHOT {
            get {
                return ResourceManager.GetString("_QTP_KEYWORDS_SNAPSHOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function WaitForSeconds(strIdentifier,Data,RC,Data_TC)
        ///	Call u_WriteOneLine2LogFile(&quot;INFO&quot;, &quot;WaitForSeconds:&quot;&amp;Data_TC)
        ///	
        ///	Reporter.Filter = rfEnableErrorsAndWarnings 
        ///	If (Data_TC=&quot;&quot;) Then
        ///		Data_TC = 3 
        ///	End If
        ///	If Not IsNumeric(Data_TC) Then
        ///		Reporter.ReportEvent micDone, &quot; WaitForSeconds uses non-numeric parameter, default value 3 will be applied.&quot;, &quot;Default value 3 will be applied.&quot;
        ///	End If
        ///	
        ///	If RC=&quot;&quot; Or StrComp(UCase(RC),&quot;SMARTWAIT&quot;)&lt;&gt;0 Then
        ///		Call wait(Data_TC)
        ///		Call u_ReportInfo2Word( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _QTP_KEYWORDS_WAITFORSECONDS {
            get {
                return ResourceManager.GetString("_QTP_KEYWORDS_WAITFORSECONDS", resourceCulture);
            }
        }
    }
}
