//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_TC_DATA_SUMMARY
    {
        public long ID { get; set; }
        public Nullable<long> DATA_SUMMARY_ID { get; set; }
        public Nullable<long> TEST_CASE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
    
        public virtual T_TEST_CASE_SUMMARY T_TEST_CASE_SUMMARY { get; set; }
        public virtual T_TEST_DATA_SUMMARY T_TEST_DATA_SUMMARY { get; set; }
    }
}
