//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COMPARE_CONFIG
    {
        public decimal COMPARE_ID { get; set; }
        public string COMPARE_NAME { get; set; }
        public string S1_TYPE { get; set; }
        public string S1_DBCONN { get; set; }
        public string S1_QUERY { get; set; }
        public string S1_FILE_LOC { get; set; }
        public string S2_TYPE { get; set; }
        public string S2_DBCONN { get; set; }
        public string S2_QUERY { get; set; }
        public string S2_FILE_LOC { get; set; }
        public string O_FILE_LOC { get; set; }
        public string KEY_FIELDS { get; set; }
        public string SHOW_FIELDS { get; set; }
        public string COMPARE_FIELDS { get; set; }
        public string ROW_FIELDS { get; set; }
        public string COLUMN_FIELDS { get; set; }
    }
}
