//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_STORYBOARD_SUMMARY
    {
        public T_STORYBOARD_SUMMARY()
        {
            this.T_PROJ_TC_MGR = new HashSet<T_PROJ_TC_MGR>();
            this.T_STORYBOARD_HISTORY = new HashSet<T_STORYBOARD_HISTORY>();
        }
    
        public long STORYBOARD_ID { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<decimal> LATEST_VERISON { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> CREATER { get; set; }
        public Nullable<long> ASSIGNED_PROJECT_ID { get; set; }
        public string STORYBOARD_NAME { get; set; }
    
        public virtual ICollection<T_PROJ_TC_MGR> T_PROJ_TC_MGR { get; set; }
        public virtual ICollection<T_STORYBOARD_HISTORY> T_STORYBOARD_HISTORY { get; set; }
    }
}
