//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_STORYBOARD_HISTORY
    {
        public long DASHBOARD_HIST_ID { get; set; }
        public Nullable<long> STORYBOARD_ID { get; set; }
        public Nullable<long> VERION { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<long> CREATOR { get; set; }
        public string STORYBOARD_NAME { get; set; }
        public Nullable<long> ASSIGNED_PROJECT_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> HISTORY_CREATE_TIME { get; set; }
        public string REASON { get; set; }
    
        public virtual T_STORYBOARD_SUMMARY T_STORYBOARD_SUMMARY { get; set; }
    }
}
