//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_STEPS
    {
        public T_TEST_STEPS()
        {
            this.T_TEST_REPORT_STEPS = new HashSet<T_TEST_REPORT_STEPS>();
            this.TEST_DATA_SETTING = new HashSet<TEST_DATA_SETTING>();
        }
    
        public long STEPS_ID { get; set; }
        public Nullable<decimal> RUN_ORDER { get; set; }
        public Nullable<long> KEY_WORD_ID { get; set; }
        public Nullable<long> TEST_CASE_ID { get; set; }
        public Nullable<long> OBJECT_ID { get; set; }
        public string COLUMN_ROW_SETTING { get; set; }
        public string VALUE_SETTING { get; set; }
        public string COMMENT { get; set; }
        public Nullable<decimal> IS_RUNNABLE { get; set; }
    
        public virtual T_KEYWORD T_KEYWORD { get; set; }
        public virtual T_REGISTED_OBJECT T_REGISTED_OBJECT { get; set; }
        public virtual T_TEST_CASE_SUMMARY T_TEST_CASE_SUMMARY { get; set; }
        public virtual ICollection<T_TEST_REPORT_STEPS> T_TEST_REPORT_STEPS { get; set; }
        public virtual ICollection<TEST_DATA_SETTING> TEST_DATA_SETTING { get; set; }
    }
}
