//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OBJECT_CHILD
    {
        public long CHILD_ID { get; set; }
        public long OBJECT_ID { get; set; }
        public string OBJ_CHLD_HAPPYNAME { get; set; }
        public Nullable<short> CHILD_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> PARENT_CHILD_ID { get; set; }
        public string INTERNAL_EXPRESSION { get; set; }
    }
}
