//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MarsEntities : DbContext
    {
        public static string Database_Password { get; set; }
        public static string Database_ConnectionString { get; set; }
        public MarsEntities()
           : base((string.IsNullOrEmpty(Database_Password) || string.IsNullOrEmpty(Database_ConnectionString)) ? "name = MarsEntities"
                 : string.Format(Database_ConnectionString, Database_Password))
        //: base("name=MarsEntities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 3600;


        }

        private static string combinCnnStr(string strCnn, string strPwd)
        {
            return string.Format(strCnn, strPwd);
        }
        public MarsEntities(string strCnn, string strPwd) : base(combinCnnStr(strCnn, strPwd))
        {
            //;[.kkkkbase(strFromCnfgWithPasswrd);
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 3600;
        }

        public MarsEntities(DbConnection dbCnn) : base(dbCnn, false)
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 3600;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<REL_APP_PROJ> REL_APP_PROJ { get; set; }
        public DbSet<REL_APP_TESTCASE> REL_APP_TESTCASE { get; set; }
        public DbSet<REL_APP_TESTSUITE> REL_APP_TESTSUITE { get; set; }
        public DbSet<REL_TEST_CASE_TEST_SUITE> REL_TEST_CASE_TEST_SUITE { get; set; }
        public DbSet<REL_TEST_SUIT_PROJECT> REL_TEST_SUIT_PROJECT { get; set; }
        public DbSet<SYSTEM_LOOKUP> SYSTEM_LOOKUP { get; set; }
        public DbSet<T_BASELINE_DATA_DETAIL> T_BASELINE_DATA_DETAIL { get; set; }
        public DbSet<T_BASELINE_DATA_SUMMARY> T_BASELINE_DATA_SUMMARY { get; set; }
        public DbSet<T_DATA_SOURCE> T_DATA_SOURCE { get; set; }
        public DbSet<T_DIC_RELATION_KEYWORD> T_DIC_RELATION_KEYWORD { get; set; }
        public DbSet<T_GUI_COMPONENT_TYPE_DIC> T_GUI_COMPONENT_TYPE_DIC { get; set; }
        public DbSet<T_KEYWORD> T_KEYWORD { get; set; }
        public DbSet<T_OBJECT_NAMEINFO> T_OBJECT_NAMEINFO { get; set; }
        public DbSet<T_OBJECT_CHILD> T_OBJECT_CHILD { get; set; }
        public DbSet<T_PROJECT_DATA_SOURCE> T_PROJECT_DATA_SOURCE { get; set; }
        public DbSet<T_REGISTED_OBJECT> T_REGISTED_OBJECT { get; set; }
        public DbSet<T_REGISTERED_APPS> T_REGISTERED_APPS { get; set; }
        public DbSet<T_TEST_CASE_SUMMARY> T_TEST_CASE_SUMMARY { get; set; }
        public DbSet<T_TEST_ENUM> T_TEST_ENUM { get; set; }
        public DbSet<T_TEST_PROJECT> T_TEST_PROJECT { get; set; }
        public DbSet<T_TEST_REPORT> T_TEST_REPORT { get; set; }
        public DbSet<T_TEST_REPORT_STEPS> T_TEST_REPORT_STEPS { get; set; }
        public DbSet<T_TEST_STEPS> T_TEST_STEPS { get; set; }
        public DbSet<T_TEST_SUITE> T_TEST_SUITE { get; set; }
        public DbSet<TEST_DATA_SETTING> TEST_DATA_SETTING { get; set; }
        public DbSet<V_TEST_STEPS_FULLVISION> V_TEST_STEPS_FULLVISION { get; set; }
        public DbSet<V_PROJ_TS_TC_FULLVISION> V_PROJ_TS_TC_FULLVISION { get; set; }
        public DbSet<V_STB_PROJ_APP_FULLVISION> V_STB_PROJ_APP_FULLVISION { get; set; }
        public DbSet<V_STORYBOARD_TEST_FULLVISION> V_STORYBOARD_TEST_FULLVISION { get; set; }
        public DbSet<REL_TC_DATA_SUMMARY> REL_TC_DATA_SUMMARY { get; set; }
        public DbSet<T_COMPARE_CONFIG> T_COMPARE_CONFIG { get; set; }
        public DbSet<T_COMPARE_CONNECTIONS> T_COMPARE_CONNECTIONS { get; set; }
        public DbSet<T_COMPARE_QUERIES> T_COMPARE_QUERIES { get; set; }
        public DbSet<T_PROJ_TC_MGR> T_PROJ_TC_MGR { get; set; }
        public DbSet<T_PROJ_TEST_RESULT> T_PROJ_TEST_RESULT { get; set; }
        public DbSet<T_SHARED_OBJECT_POOL> T_SHARED_OBJECT_POOL { get; set; }
        public DbSet<T_STORYBOARD_DATASET_SETTING> T_STORYBOARD_DATASET_SETTING { get; set; }
        public DbSet<T_STORYBOARD_HISTORY> T_STORYBOARD_HISTORY { get; set; }
        public DbSet<T_STORYBOARD_SUMMARY> T_STORYBOARD_SUMMARY { get; set; }
        public DbSet<T_TEST_CASE_VERSION> T_TEST_CASE_VERSION { get; set; }
        public DbSet<T_TEST_DATA_SUMMARY> T_TEST_DATA_SUMMARY { get; set; }
        public DbSet<V_BASE_LINEDATA> V_BASE_LINEDATA { get; set; }
        public DbSet<V_TESTSTORYBOARD_SUMMARY> V_TESTSTORYBOARD_SUMMARY { get; set; }
        public DbSet<V_OBJECT_SNAPSHOT> V_OBJECT_SNAPSHOT { get; set; }
        public DbSet<V_OBJECT_APPS> V_OBJECT_APPS { get; set; }
        public DbSet<V_TEST_DATA_REPORT_SUMMARY> V_TEST_DATA_REPORT_SUMMARY { get; set; }
        public DbSet<V_TEST_DATARPT_CAPTURE> V_TEST_DATARPT_CAPTURE { get; set; }
        public DbSet<T_MARS_COMPANY> T_MARS_COMPANY { get; set; }
        public DbSet<T_TESTER_INFO> T_TESTER_INFO { get; set; }
        public DbSet<V_USER_COMPANY> V_USER_COMPANY { get; set; }
        public DbSet<T_BAT_RESULT> T_BAT_RESULT { get; set; }
        public DbSet<T_BAT_RESULT_DETAIL> T_BAT_RESULT_DETAIL { get; set; }
        public DbSet<T_TEST_BATCH> T_TEST_BATCH { get; set; }
        public DbSet<T_TEST_BATCH_DETAIL> T_TEST_BATCH_DETAIL { get; set; }
    
        public virtual int GETNEXT_VAL(string p_SEQUENCE_NAME, ObjectParameter v_NEXTVAL)
        {
            var p_SEQUENCE_NAMEParameter = p_SEQUENCE_NAME != null ?
                new ObjectParameter("P_SEQUENCE_NAME", p_SEQUENCE_NAME) :
                new ObjectParameter("P_SEQUENCE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GETNEXT_VAL", p_SEQUENCE_NAMEParameter, v_NEXTVAL);
        }
    }
}
