//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class REL_APP_TESTSUITEDTO
    {
        [DataMember()]
        public Int64 RELATIONSHIP_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> APPLICATION_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> TEST_SUITE_ID { get; set; }

        public REL_APP_TESTSUITEDTO()
        {
        }

        public REL_APP_TESTSUITEDTO(Int64 rELATIONSHIP_ID, Nullable<Int64> aPPLICATION_ID, Nullable<Int64> tEST_SUITE_ID)
        {
			this.RELATIONSHIP_ID = rELATIONSHIP_ID;
			this.APPLICATION_ID = aPPLICATION_ID;
			this.TEST_SUITE_ID = tEST_SUITE_ID;
        }
    }
}
