//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class REL_TC_DATA_SUMMARYDTO
    {
        [DataMember()]
        public Int64 ID { get; set; }

        [DataMember()]
        public Nullable<Int64> DATA_SUMMARY_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> TEST_CASE_ID { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_TIME { get; set; }

        [DataMember()]
        public Int64 T_TEST_CASE_SUMMARY_TEST_CASE_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_DATA_SUMMARY_DATA_SUMMARY_ID { get; set; }

        public REL_TC_DATA_SUMMARYDTO()
        {
        }

        public REL_TC_DATA_SUMMARYDTO(Int64 iD, Nullable<Int64> dATA_SUMMARY_ID, Nullable<Int64> tEST_CASE_ID, Nullable<DateTime> cREATE_TIME, Int64 t_TEST_CASE_SUMMARY_TEST_CASE_ID, Int64 t_TEST_DATA_SUMMARY_DATA_SUMMARY_ID)
        {
			this.ID = iD;
			this.DATA_SUMMARY_ID = dATA_SUMMARY_ID;
			this.TEST_CASE_ID = tEST_CASE_ID;
			this.CREATE_TIME = cREATE_TIME;
			this.T_TEST_CASE_SUMMARY_TEST_CASE_ID = t_TEST_CASE_SUMMARY_TEST_CASE_ID;
			this.T_TEST_DATA_SUMMARY_DATA_SUMMARY_ID = t_TEST_DATA_SUMMARY_DATA_SUMMARY_ID;
        }
    }
}
