//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="REL_APP_PROJ"/> and <see cref="REL_APP_PROJDTO"/>.
    /// </summary>
    public static partial class REL_APP_PROJAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="REL_APP_PROJDTO"/> converted from <see cref="REL_APP_PROJ"/>.</param>
        static partial void OnDTO(this REL_APP_PROJ entity, REL_APP_PROJDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="REL_APP_PROJ"/> converted from <see cref="REL_APP_PROJDTO"/>.</param>
        static partial void OnEntity(this REL_APP_PROJDTO dto, REL_APP_PROJ entity);

        /// <summary>
        /// Converts this instance of <see cref="REL_APP_PROJDTO"/> to an instance of <see cref="REL_APP_PROJ"/>.
        /// </summary>
        /// <param name="dto"><see cref="REL_APP_PROJDTO"/> to convert.</param>
        public static REL_APP_PROJ ToEntity(this REL_APP_PROJDTO dto)
        {
            if (dto == null) return null;

            var entity = new REL_APP_PROJ();

            entity.RELATIONSHIP_ID = dto.RELATIONSHIP_ID;
            entity.APPLICATION_ID = dto.APPLICATION_ID;
            entity.PROJECT_ID = dto.PROJECT_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="REL_APP_PROJ"/> to an instance of <see cref="REL_APP_PROJDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="REL_APP_PROJ"/> to convert.</param>
        public static REL_APP_PROJDTO ToDTO(this REL_APP_PROJ entity)
        {
            if (entity == null) return null;

            var dto = new REL_APP_PROJDTO();

            dto.RELATIONSHIP_ID = entity.RELATIONSHIP_ID;
            dto.APPLICATION_ID = entity.APPLICATION_ID;
            dto.PROJECT_ID = entity.PROJECT_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="REL_APP_PROJDTO"/> to an instance of <see cref="REL_APP_PROJ"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<REL_APP_PROJ> ToEntities(this IEnumerable<REL_APP_PROJDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="REL_APP_PROJ"/> to an instance of <see cref="REL_APP_PROJDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<REL_APP_PROJDTO> ToDTOs(this IEnumerable<REL_APP_PROJ> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
