//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:51
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_BAT_RESULTDTO
    {
        [DataMember()]
        public Int64 BAT_RESULT_ID { get; set; }

        [DataMember()]
        public Int64 BAT_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> RESULT_ID { get; set; }

        [DataMember()]
        public Nullable<DateTime> START_TIME { get; set; }

        [DataMember()]
        public Nullable<DateTime> END_TIME { get; set; }

        [DataMember()]
        public String ERROR_MESSAGE { get; set; }

        [DataMember()]
        public Int64 T_TEST_BATCH_BAT_ID { get; set; }

        [DataMember()]
        public List<Int64> T_BAT_RESULT_DETAIL_BAT_RESULT_DTL_ID { get; set; }

        public T_BAT_RESULTDTO()
        {
        }

        public T_BAT_RESULTDTO(Int64 bAT_RESULT_ID, Int64 bAT_ID, Nullable<Int64> rESULT_ID, Nullable<DateTime> sTART_TIME, Nullable<DateTime> eND_TIME, String eRROR_MESSAGE, Int64 t_TEST_BATCH_BAT_ID, List<Int64> t_BAT_RESULT_DETAIL_BAT_RESULT_DTL_ID)
        {
			this.BAT_RESULT_ID = bAT_RESULT_ID;
			this.BAT_ID = bAT_ID;
			this.RESULT_ID = rESULT_ID;
			this.START_TIME = sTART_TIME;
			this.END_TIME = eND_TIME;
			this.ERROR_MESSAGE = eRROR_MESSAGE;
			this.T_TEST_BATCH_BAT_ID = t_TEST_BATCH_BAT_ID;
			this.T_BAT_RESULT_DETAIL_BAT_RESULT_DTL_ID = t_BAT_RESULT_DETAIL_BAT_RESULT_DTL_ID;
        }
    }
}
