//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:20
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_BAT_RESULT"/> and <see cref="T_BAT_RESULTDTO"/>.
    /// </summary>
    public static partial class T_BAT_RESULTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_BAT_RESULTDTO"/> converted from <see cref="T_BAT_RESULT"/>.</param>
        static partial void OnDTO(this T_BAT_RESULT entity, T_BAT_RESULTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_BAT_RESULT"/> converted from <see cref="T_BAT_RESULTDTO"/>.</param>
        static partial void OnEntity(this T_BAT_RESULTDTO dto, T_BAT_RESULT entity);

        /// <summary>
        /// Converts this instance of <see cref="T_BAT_RESULTDTO"/> to an instance of <see cref="T_BAT_RESULT"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_BAT_RESULTDTO"/> to convert.</param>
        public static T_BAT_RESULT ToEntity(this T_BAT_RESULTDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_BAT_RESULT();

            entity.BAT_RESULT_ID = dto.BAT_RESULT_ID;
            entity.BAT_ID = dto.BAT_ID;
            entity.RESULT_ID = dto.RESULT_ID;
            entity.START_TIME = dto.START_TIME;
            entity.END_TIME = dto.END_TIME;
            entity.ERROR_MESSAGE = dto.ERROR_MESSAGE;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_BAT_RESULT"/> to an instance of <see cref="T_BAT_RESULTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_BAT_RESULT"/> to convert.</param>
        public static T_BAT_RESULTDTO ToDTO(this T_BAT_RESULT entity)
        {
            if (entity == null) return null;

            var dto = new T_BAT_RESULTDTO();

            dto.BAT_RESULT_ID = entity.BAT_RESULT_ID;
            dto.BAT_ID = entity.BAT_ID;
            dto.RESULT_ID = entity.RESULT_ID;
            dto.START_TIME = entity.START_TIME;
            dto.END_TIME = entity.END_TIME;
            dto.ERROR_MESSAGE = entity.ERROR_MESSAGE;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_BAT_RESULTDTO"/> to an instance of <see cref="T_BAT_RESULT"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_BAT_RESULT> ToEntities(this IEnumerable<T_BAT_RESULTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_BAT_RESULT"/> to an instance of <see cref="T_BAT_RESULTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_BAT_RESULTDTO> ToDTOs(this IEnumerable<T_BAT_RESULT> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
