//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:11
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_COMPARE_QUERIES"/> and <see cref="T_COMPARE_QUERIESDTO"/>.
    /// </summary>
    public static partial class T_COMPARE_QUERIESAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_COMPARE_QUERIESDTO"/> converted from <see cref="T_COMPARE_QUERIES"/>.</param>
        static partial void OnDTO(this T_COMPARE_QUERIES entity, T_COMPARE_QUERIESDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_COMPARE_QUERIES"/> converted from <see cref="T_COMPARE_QUERIESDTO"/>.</param>
        static partial void OnEntity(this T_COMPARE_QUERIESDTO dto, T_COMPARE_QUERIES entity);

        /// <summary>
        /// Converts this instance of <see cref="T_COMPARE_QUERIESDTO"/> to an instance of <see cref="T_COMPARE_QUERIES"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_COMPARE_QUERIESDTO"/> to convert.</param>
        public static T_COMPARE_QUERIES ToEntity(this T_COMPARE_QUERIESDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_COMPARE_QUERIES();

            entity.QUERY_ID = dto.QUERY_ID;
            entity.QUERY_NAME = dto.QUERY_NAME;
            entity.QUERY_VAL = dto.QUERY_VAL;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_COMPARE_QUERIES"/> to an instance of <see cref="T_COMPARE_QUERIESDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_COMPARE_QUERIES"/> to convert.</param>
        public static T_COMPARE_QUERIESDTO ToDTO(this T_COMPARE_QUERIES entity)
        {
            if (entity == null) return null;

            var dto = new T_COMPARE_QUERIESDTO();

            dto.QUERY_ID = entity.QUERY_ID;
            dto.QUERY_NAME = entity.QUERY_NAME;
            dto.QUERY_VAL = entity.QUERY_VAL;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_COMPARE_QUERIESDTO"/> to an instance of <see cref="T_COMPARE_QUERIES"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_COMPARE_QUERIES> ToEntities(this IEnumerable<T_COMPARE_QUERIESDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_COMPARE_QUERIES"/> to an instance of <see cref="T_COMPARE_QUERIESDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_COMPARE_QUERIESDTO> ToDTOs(this IEnumerable<T_COMPARE_QUERIES> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
