//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:59
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_DATA_SOURCE"/> and <see cref="T_DATA_SOURCEDTO"/>.
    /// </summary>
    public static partial class T_DATA_SOURCEAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_DATA_SOURCEDTO"/> converted from <see cref="T_DATA_SOURCE"/>.</param>
        static partial void OnDTO(this T_DATA_SOURCE entity, T_DATA_SOURCEDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_DATA_SOURCE"/> converted from <see cref="T_DATA_SOURCEDTO"/>.</param>
        static partial void OnEntity(this T_DATA_SOURCEDTO dto, T_DATA_SOURCE entity);

        /// <summary>
        /// Converts this instance of <see cref="T_DATA_SOURCEDTO"/> to an instance of <see cref="T_DATA_SOURCE"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_DATA_SOURCEDTO"/> to convert.</param>
        public static T_DATA_SOURCE ToEntity(this T_DATA_SOURCEDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_DATA_SOURCE();

            entity.DATA_SOURCE_ID = dto.DATA_SOURCE_ID;
            entity.DATA_SOURCE_NAME = dto.DATA_SOURCE_NAME;
            entity.DATA_SOURCE_TYPE = dto.DATA_SOURCE_TYPE;
            entity.DETAILS = dto.DETAILS;
            entity.DB_CONNECTION = dto.DB_CONNECTION;
            entity.DB_TYPE = dto.DB_TYPE;
            entity.TEST_CONNECTION = dto.TEST_CONNECTION;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_DATA_SOURCE"/> to an instance of <see cref="T_DATA_SOURCEDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_DATA_SOURCE"/> to convert.</param>
        public static T_DATA_SOURCEDTO ToDTO(this T_DATA_SOURCE entity)
        {
            if (entity == null) return null;

            var dto = new T_DATA_SOURCEDTO();

            dto.DATA_SOURCE_ID = entity.DATA_SOURCE_ID;
            dto.DATA_SOURCE_NAME = entity.DATA_SOURCE_NAME;
            dto.DATA_SOURCE_TYPE = entity.DATA_SOURCE_TYPE;
            dto.DETAILS = entity.DETAILS;
            dto.DB_CONNECTION = entity.DB_CONNECTION;
            dto.DB_TYPE = entity.DB_TYPE;
            dto.TEST_CONNECTION = entity.TEST_CONNECTION;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_DATA_SOURCEDTO"/> to an instance of <see cref="T_DATA_SOURCE"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_DATA_SOURCE> ToEntities(this IEnumerable<T_DATA_SOURCEDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_DATA_SOURCE"/> to an instance of <see cref="T_DATA_SOURCEDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_DATA_SOURCEDTO> ToDTOs(this IEnumerable<T_DATA_SOURCE> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
