//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:41
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_DIC_RELATION_KEYWORDDTO
    {
        [DataMember()]
        public Int64 RELATION_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> TYPE_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> KEY_WORD_ID { get; set; }

        [DataMember()]
        public Int64 T_GUI_COMPONENT_TYPE_DIC_TYPE_ID { get; set; }

        [DataMember()]
        public Int64 T_KEYWORD_KEY_WORD_ID { get; set; }

        public T_DIC_RELATION_KEYWORDDTO()
        {
        }

        public T_DIC_RELATION_KEYWORDDTO(Int64 rELATION_ID, Nullable<Int64> tYPE_ID, Nullable<Int64> kEY_WORD_ID, Int64 t_GUI_COMPONENT_TYPE_DIC_TYPE_ID, Int64 t_KEYWORD_KEY_WORD_ID)
        {
			this.RELATION_ID = rELATION_ID;
			this.TYPE_ID = tYPE_ID;
			this.KEY_WORD_ID = kEY_WORD_ID;
			this.T_GUI_COMPONENT_TYPE_DIC_TYPE_ID = t_GUI_COMPONENT_TYPE_DIC_TYPE_ID;
			this.T_KEYWORD_KEY_WORD_ID = t_KEYWORD_KEY_WORD_ID;
        }
    }
}
