//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:43
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_KEYWORDDTO
    {
        [DataMember()]
        public Int64 KEY_WORD_ID { get; set; }

        [DataMember()]
        public String KEY_WORD_NAME { get; set; }

        [DataMember()]
        public String DESCRIPTION { get; set; }

        [DataMember()]
        public Nullable<Int16> KEY_WORD_POSITION_ID { get; set; }

        [DataMember()]
        public String ENTRY_IN_DATA_FILE { get; set; }

        [DataMember()]
        public List<Int64> T_DIC_RELATION_KEYWORD_RELATION_ID { get; set; }

        [DataMember()]
        public List<Int64> T_TEST_STEPS_STEPS_ID { get; set; }

        public T_KEYWORDDTO()
        {
        }

        public T_KEYWORDDTO(Int64 kEY_WORD_ID, String kEY_WORD_NAME, String dESCRIPTION, Nullable<Int16> kEY_WORD_POSITION_ID, String eNTRY_IN_DATA_FILE, List<Int64> t_DIC_RELATION_KEYWORD_RELATION_ID, List<Int64> t_TEST_STEPS_STEPS_ID)
        {
			this.KEY_WORD_ID = kEY_WORD_ID;
			this.KEY_WORD_NAME = kEY_WORD_NAME;
			this.DESCRIPTION = dESCRIPTION;
			this.KEY_WORD_POSITION_ID = kEY_WORD_POSITION_ID;
			this.ENTRY_IN_DATA_FILE = eNTRY_IN_DATA_FILE;
			this.T_DIC_RELATION_KEYWORD_RELATION_ID = t_DIC_RELATION_KEYWORD_RELATION_ID;
			this.T_TEST_STEPS_STEPS_ID = t_TEST_STEPS_STEPS_ID;
        }
    }
}
