//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_KEYWORD"/> and <see cref="T_KEYWORDDTO"/>.
    /// </summary>
    public static partial class T_KEYWORDAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_KEYWORDDTO"/> converted from <see cref="T_KEYWORD"/>.</param>
        static partial void OnDTO(this T_KEYWORD entity, T_KEYWORDDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_KEYWORD"/> converted from <see cref="T_KEYWORDDTO"/>.</param>
        static partial void OnEntity(this T_KEYWORDDTO dto, T_KEYWORD entity);

        /// <summary>
        /// Converts this instance of <see cref="T_KEYWORDDTO"/> to an instance of <see cref="T_KEYWORD"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_KEYWORDDTO"/> to convert.</param>
        public static T_KEYWORD ToEntity(this T_KEYWORDDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_KEYWORD();

            entity.KEY_WORD_ID = dto.KEY_WORD_ID;
            entity.KEY_WORD_NAME = dto.KEY_WORD_NAME;
            entity.DESCRIPTION = dto.DESCRIPTION;
            entity.KEY_WORD_POSITION_ID = dto.KEY_WORD_POSITION_ID;
            entity.ENTRY_IN_DATA_FILE = dto.ENTRY_IN_DATA_FILE;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_KEYWORD"/> to an instance of <see cref="T_KEYWORDDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_KEYWORD"/> to convert.</param>
        public static T_KEYWORDDTO ToDTO(this T_KEYWORD entity)
        {
            if (entity == null) return null;

            var dto = new T_KEYWORDDTO();

            dto.KEY_WORD_ID = entity.KEY_WORD_ID;
            dto.KEY_WORD_NAME = entity.KEY_WORD_NAME;
            dto.DESCRIPTION = entity.DESCRIPTION;
            dto.KEY_WORD_POSITION_ID = entity.KEY_WORD_POSITION_ID;
            dto.ENTRY_IN_DATA_FILE = entity.ENTRY_IN_DATA_FILE;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_KEYWORDDTO"/> to an instance of <see cref="T_KEYWORD"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_KEYWORD> ToEntities(this IEnumerable<T_KEYWORDDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_KEYWORD"/> to an instance of <see cref="T_KEYWORDDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_KEYWORDDTO> ToDTOs(this IEnumerable<T_KEYWORD> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
