//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_MARS_COMPANY"/> and <see cref="T_MARS_COMPANYDTO"/>.
    /// </summary>
    public static partial class T_MARS_COMPANYAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_MARS_COMPANYDTO"/> converted from <see cref="T_MARS_COMPANY"/>.</param>
        static partial void OnDTO(this T_MARS_COMPANY entity, T_MARS_COMPANYDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_MARS_COMPANY"/> converted from <see cref="T_MARS_COMPANYDTO"/>.</param>
        static partial void OnEntity(this T_MARS_COMPANYDTO dto, T_MARS_COMPANY entity);

        /// <summary>
        /// Converts this instance of <see cref="T_MARS_COMPANYDTO"/> to an instance of <see cref="T_MARS_COMPANY"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_MARS_COMPANYDTO"/> to convert.</param>
        public static T_MARS_COMPANY ToEntity(this T_MARS_COMPANYDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_MARS_COMPANY();

            entity.COMPANY_ID = dto.COMPANY_ID;
            entity.COMPANY_NAME = dto.COMPANY_NAME;
            entity.COMPANY_DESC = dto.COMPANY_DESC;
            entity.COMPANY_NUMBER = dto.COMPANY_NUMBER;
            entity.COMPANY_ADDRESS = dto.COMPANY_ADDRESS;
            entity.CREATE_USERNAME = dto.CREATE_USERNAME;
            entity.CREATE_TIME = dto.CREATE_TIME;
            entity.AVAILABLE_MARK = dto.AVAILABLE_MARK;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_MARS_COMPANY"/> to an instance of <see cref="T_MARS_COMPANYDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_MARS_COMPANY"/> to convert.</param>
        public static T_MARS_COMPANYDTO ToDTO(this T_MARS_COMPANY entity)
        {
            if (entity == null) return null;

            var dto = new T_MARS_COMPANYDTO();

            dto.COMPANY_ID = entity.COMPANY_ID;
            dto.COMPANY_NAME = entity.COMPANY_NAME;
            dto.COMPANY_DESC = entity.COMPANY_DESC;
            dto.COMPANY_NUMBER = entity.COMPANY_NUMBER;
            dto.COMPANY_ADDRESS = entity.COMPANY_ADDRESS;
            dto.CREATE_USERNAME = entity.CREATE_USERNAME;
            dto.CREATE_TIME = entity.CREATE_TIME;
            dto.AVAILABLE_MARK = entity.AVAILABLE_MARK;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_MARS_COMPANYDTO"/> to an instance of <see cref="T_MARS_COMPANY"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_MARS_COMPANY> ToEntities(this IEnumerable<T_MARS_COMPANYDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_MARS_COMPANY"/> to an instance of <see cref="T_MARS_COMPANYDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_MARS_COMPANYDTO> ToDTOs(this IEnumerable<T_MARS_COMPANY> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
