//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_OBJECT_CHILD"/> and <see cref="T_OBJECT_CHILDDTO"/>.
    /// </summary>
    public static partial class T_OBJECT_CHILDAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_OBJECT_CHILDDTO"/> converted from <see cref="T_OBJECT_CHILD"/>.</param>
        static partial void OnDTO(this T_OBJECT_CHILD entity, T_OBJECT_CHILDDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_OBJECT_CHILD"/> converted from <see cref="T_OBJECT_CHILDDTO"/>.</param>
        static partial void OnEntity(this T_OBJECT_CHILDDTO dto, T_OBJECT_CHILD entity);

        /// <summary>
        /// Converts this instance of <see cref="T_OBJECT_CHILDDTO"/> to an instance of <see cref="T_OBJECT_CHILD"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_OBJECT_CHILDDTO"/> to convert.</param>
        public static T_OBJECT_CHILD ToEntity(this T_OBJECT_CHILDDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_OBJECT_CHILD();

            entity.CHILD_ID = dto.CHILD_ID;
            entity.OBJECT_ID = dto.OBJECT_ID;
            entity.OBJ_CHLD_HAPPYNAME = dto.OBJ_CHLD_HAPPYNAME;
            entity.CHILD_TYPE = dto.CHILD_TYPE;
            entity.DESCRIPTION = dto.DESCRIPTION;
            entity.PARENT_CHILD_ID = dto.PARENT_CHILD_ID;
            entity.INTERNAL_EXPRESSION = dto.INTERNAL_EXPRESSION;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_OBJECT_CHILD"/> to an instance of <see cref="T_OBJECT_CHILDDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_OBJECT_CHILD"/> to convert.</param>
        public static T_OBJECT_CHILDDTO ToDTO(this T_OBJECT_CHILD entity)
        {
            if (entity == null) return null;

            var dto = new T_OBJECT_CHILDDTO();

            dto.CHILD_ID = entity.CHILD_ID;
            dto.OBJECT_ID = entity.OBJECT_ID;
            dto.OBJ_CHLD_HAPPYNAME = entity.OBJ_CHLD_HAPPYNAME;
            dto.CHILD_TYPE = entity.CHILD_TYPE;
            dto.DESCRIPTION = entity.DESCRIPTION;
            dto.PARENT_CHILD_ID = entity.PARENT_CHILD_ID;
            dto.INTERNAL_EXPRESSION = entity.INTERNAL_EXPRESSION;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_OBJECT_CHILDDTO"/> to an instance of <see cref="T_OBJECT_CHILD"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_OBJECT_CHILD> ToEntities(this IEnumerable<T_OBJECT_CHILDDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_OBJECT_CHILD"/> to an instance of <see cref="T_OBJECT_CHILDDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_OBJECT_CHILDDTO> ToDTOs(this IEnumerable<T_OBJECT_CHILD> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
