//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_PROJ_TEST_RESULTDTO
    {
        [DataMember()]
        public Int64 HIST_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> TEST_CASE_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> STORYBOARD_DETAIL_ID { get; set; }

        [DataMember()]
        public Nullable<DateTime> TEST_BEGIN_TIME { get; set; }

        [DataMember()]
        public Nullable<DateTime> TEST_END_TIME { get; set; }

        [DataMember()]
        public String TEST_RESULT_IN_TEXT { get; set; }

        [DataMember()]
        public Nullable<Int16> TEST_MODE { get; set; }

        [DataMember()]
        public Nullable<Int16> TEST_RESULT { get; set; }

        [DataMember()]
        public Nullable<Int64> TESTER_ID { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_TIME { get; set; }

        [DataMember()]
        public Nullable<Int64> LATEST_TEST_MARK_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> RELY_TEST_CASE_ID { get; set; }

        [DataMember()]
        public String RESULT_ALIAS_NAME { get; set; }

        [DataMember()]
        public String RESULT_DESC { get; set; }

        public T_PROJ_TEST_RESULTDTO()
        {
        }

        public T_PROJ_TEST_RESULTDTO(Int64 hIST_ID, Nullable<Int64> tEST_CASE_ID, Nullable<Int64> sTORYBOARD_DETAIL_ID, Nullable<DateTime> tEST_BEGIN_TIME, Nullable<DateTime> tEST_END_TIME, String tEST_RESULT_IN_TEXT, Nullable<Int16> tEST_MODE, Nullable<Int16> tEST_RESULT, Nullable<Int64> tESTER_ID, Nullable<DateTime> cREATE_TIME, Nullable<Int64> lATEST_TEST_MARK_ID, Nullable<Int64> rELY_TEST_CASE_ID, String rESULT_ALIAS_NAME, String rESULT_DESC)
        {
			this.HIST_ID = hIST_ID;
			this.TEST_CASE_ID = tEST_CASE_ID;
			this.STORYBOARD_DETAIL_ID = sTORYBOARD_DETAIL_ID;
			this.TEST_BEGIN_TIME = tEST_BEGIN_TIME;
			this.TEST_END_TIME = tEST_END_TIME;
			this.TEST_RESULT_IN_TEXT = tEST_RESULT_IN_TEXT;
			this.TEST_MODE = tEST_MODE;
			this.TEST_RESULT = tEST_RESULT;
			this.TESTER_ID = tESTER_ID;
			this.CREATE_TIME = cREATE_TIME;
			this.LATEST_TEST_MARK_ID = lATEST_TEST_MARK_ID;
			this.RELY_TEST_CASE_ID = rELY_TEST_CASE_ID;
			this.RESULT_ALIAS_NAME = rESULT_ALIAS_NAME;
			this.RESULT_DESC = rESULT_DESC;
        }
    }
}
