//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_TEST_REPORT"/> and <see cref="T_TEST_REPORTDTO"/>.
    /// </summary>
    public static partial class T_TEST_REPORTAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_REPORTDTO"/> converted from <see cref="T_TEST_REPORT"/>.</param>
        static partial void OnDTO(this T_TEST_REPORT entity, T_TEST_REPORTDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_REPORT"/> converted from <see cref="T_TEST_REPORTDTO"/>.</param>
        static partial void OnEntity(this T_TEST_REPORTDTO dto, T_TEST_REPORT entity);

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_REPORTDTO"/> to an instance of <see cref="T_TEST_REPORT"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_REPORTDTO"/> to convert.</param>
        public static T_TEST_REPORT ToEntity(this T_TEST_REPORTDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_TEST_REPORT();

            entity.TEST_REPORT_ID = dto.TEST_REPORT_ID;
            entity.TEST_CASE_ID = dto.TEST_CASE_ID;
            entity.LOOP_ID = dto.LOOP_ID;
            entity.BEGIN_TIME = dto.BEGIN_TIME;
            entity.END_TIME = dto.END_TIME;
            entity.RUNNING_RESULT = dto.RUNNING_RESULT;
            entity.RETURN_VALUES = dto.RETURN_VALUES;
            entity.RUNNING_RESULT_INFO = dto.RUNNING_RESULT_INFO;
            entity.HIST_ID = dto.HIST_ID;
            entity.APPLICATION_ID = dto.APPLICATION_ID;
            entity.TEST_MODE = dto.TEST_MODE;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_REPORT"/> to an instance of <see cref="T_TEST_REPORTDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_REPORT"/> to convert.</param>
        public static T_TEST_REPORTDTO ToDTO(this T_TEST_REPORT entity)
        {
            if (entity == null) return null;

            var dto = new T_TEST_REPORTDTO();

            dto.TEST_REPORT_ID = entity.TEST_REPORT_ID;
            dto.TEST_CASE_ID = entity.TEST_CASE_ID;
            dto.LOOP_ID = entity.LOOP_ID;
            dto.BEGIN_TIME = entity.BEGIN_TIME;
            dto.END_TIME = entity.END_TIME;
            dto.RUNNING_RESULT = entity.RUNNING_RESULT;
            dto.RETURN_VALUES = entity.RETURN_VALUES;
            dto.RUNNING_RESULT_INFO = entity.RUNNING_RESULT_INFO;
            dto.HIST_ID = entity.HIST_ID;
            dto.APPLICATION_ID = entity.APPLICATION_ID;
            dto.TEST_MODE = entity.TEST_MODE;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_REPORTDTO"/> to an instance of <see cref="T_TEST_REPORT"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_TEST_REPORT> ToEntities(this IEnumerable<T_TEST_REPORTDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_REPORT"/> to an instance of <see cref="T_TEST_REPORTDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_TEST_REPORTDTO> ToDTOs(this IEnumerable<T_TEST_REPORT> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
