//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:21
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_TEST_BATCH"/> and <see cref="T_TEST_BATCHDTO"/>.
    /// </summary>
    public static partial class T_TEST_BATCHAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_BATCHDTO"/> converted from <see cref="T_TEST_BATCH"/>.</param>
        static partial void OnDTO(this T_TEST_BATCH entity, T_TEST_BATCHDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_BATCH"/> converted from <see cref="T_TEST_BATCHDTO"/>.</param>
        static partial void OnEntity(this T_TEST_BATCHDTO dto, T_TEST_BATCH entity);

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_BATCHDTO"/> to an instance of <see cref="T_TEST_BATCH"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_BATCHDTO"/> to convert.</param>
        public static T_TEST_BATCH ToEntity(this T_TEST_BATCHDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_TEST_BATCH();

            entity.BAT_ID = dto.BAT_ID;
            entity.BAT_NAME = dto.BAT_NAME;
            entity.BAT_DESC = dto.BAT_DESC;
            entity.CREATE_TIME = dto.CREATE_TIME;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_BATCH"/> to an instance of <see cref="T_TEST_BATCHDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_BATCH"/> to convert.</param>
        public static T_TEST_BATCHDTO ToDTO(this T_TEST_BATCH entity)
        {
            if (entity == null) return null;

            var dto = new T_TEST_BATCHDTO();

            dto.BAT_ID = entity.BAT_ID;
            dto.BAT_NAME = entity.BAT_NAME;
            dto.BAT_DESC = entity.BAT_DESC;
            dto.CREATE_TIME = entity.CREATE_TIME;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_BATCHDTO"/> to an instance of <see cref="T_TEST_BATCH"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_TEST_BATCH> ToEntities(this IEnumerable<T_TEST_BATCHDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_BATCH"/> to an instance of <see cref="T_TEST_BATCHDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_TEST_BATCHDTO> ToDTOs(this IEnumerable<T_TEST_BATCH> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
