//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:17:59
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_TEST_STEPSDTO
    {
        [DataMember()]
        public Int64 STEPS_ID { get; set; }

        [DataMember()]
        public Nullable<Decimal> RUN_ORDER { get; set; }

        [DataMember()]
        public Nullable<Int64> KEY_WORD_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> TEST_CASE_ID { get; set; }

        [DataMember()]
        public Nullable<Int64> OBJECT_ID { get; set; }

        [DataMember()]
        public String COLUMN_ROW_SETTING { get; set; }

        [DataMember()]
        public String VALUE_SETTING { get; set; }

        [DataMember()]
        public String COMMENT { get; set; }

        [DataMember()]
        public Nullable<Decimal> IS_RUNNABLE { get; set; }

        [DataMember()]
        public Nullable<Int64> OBJECT_NAME_ID { get; set; }

        [DataMember()]
        public Int64 T_KEYWORD_KEY_WORD_ID { get; set; }

        [DataMember()]
        public Int64 T_REGISTED_OBJECT_OBJECT_ID { get; set; }

        [DataMember()]
        public Int64 T_TEST_CASE_SUMMARY_TEST_CASE_ID { get; set; }

        [DataMember()]
        public List<Int64> T_TEST_REPORT_STEPS_TEST_REPORT_STEP_ID { get; set; }

        [DataMember()]
        public List<Int64> TEST_DATA_SETTING_DATA_SETTING_ID { get; set; }

        public T_TEST_STEPSDTO()
        {
        }

        public T_TEST_STEPSDTO(Int64 sTEPS_ID, Nullable<Decimal> rUN_ORDER, Nullable<Int64> kEY_WORD_ID, Nullable<Int64> tEST_CASE_ID, Nullable<Int64> oBJECT_ID, String cOLUMN_ROW_SETTING, String vALUE_SETTING, String cOMMENT, Nullable<Decimal> iS_RUNNABLE, Nullable<Int64> oBJECT_NAME_ID, Int64 t_KEYWORD_KEY_WORD_ID, Int64 t_REGISTED_OBJECT_OBJECT_ID, Int64 t_TEST_CASE_SUMMARY_TEST_CASE_ID, List<Int64> t_TEST_REPORT_STEPS_TEST_REPORT_STEP_ID, List<Int64> tEST_DATA_SETTING_DATA_SETTING_ID)
        {
			this.STEPS_ID = sTEPS_ID;
			this.RUN_ORDER = rUN_ORDER;
			this.KEY_WORD_ID = kEY_WORD_ID;
			this.TEST_CASE_ID = tEST_CASE_ID;
			this.OBJECT_ID = oBJECT_ID;
			this.COLUMN_ROW_SETTING = cOLUMN_ROW_SETTING;
			this.VALUE_SETTING = vALUE_SETTING;
			this.COMMENT = cOMMENT;
			this.IS_RUNNABLE = iS_RUNNABLE;
			this.OBJECT_NAME_ID = oBJECT_NAME_ID;
			this.T_KEYWORD_KEY_WORD_ID = t_KEYWORD_KEY_WORD_ID;
			this.T_REGISTED_OBJECT_OBJECT_ID = t_REGISTED_OBJECT_OBJECT_ID;
			this.T_TEST_CASE_SUMMARY_TEST_CASE_ID = t_TEST_CASE_SUMMARY_TEST_CASE_ID;
			this.T_TEST_REPORT_STEPS_TEST_REPORT_STEP_ID = t_TEST_REPORT_STEPS_TEST_REPORT_STEP_ID;
			this.TEST_DATA_SETTING_DATA_SETTING_ID = tEST_DATA_SETTING_DATA_SETTING_ID;
        }
    }
}
