//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class T_TEST_DATA_SUMMARYDTO
    {
        [DataMember()]
        public Int64 DATA_SUMMARY_ID { get; set; }

        [DataMember()]
        public String ALIAS_NAME { get; set; }

        [DataMember()]
        public String DESCRIPTION_INFO { get; set; }

        [DataMember()]
        public Nullable<Int16> AVAILABLE_MARK { get; set; }

        [DataMember()]
        public Nullable<Int64> VERSION { get; set; }

        [DataMember()]
        public Nullable<Int16> SHARE_MARK { get; set; }

        [DataMember()]
        public Nullable<DateTime> CREATE_TIME { get; set; }

        [DataMember()]
        public Nullable<Int16> STATUS { get; set; }

        [DataMember()]
        public Nullable<Int16> DATA_SET_TYPE { get; set; }

        [DataMember()]
        public List<Int64> REL_TC_DATA_SUMMARY_ID { get; set; }

        [DataMember()]
        public List<Int64> T_SHARED_OBJECT_POOL_OBJECT_POOL_ID { get; set; }

        [DataMember()]
        public List<Int64> T_STORYBOARD_DATASET_SETTING_SETTING_ID { get; set; }

        [DataMember()]
        public List<Int64> TEST_DATA_SETTING_DATA_SETTING_ID { get; set; }

        public T_TEST_DATA_SUMMARYDTO()
        {
        }

        public T_TEST_DATA_SUMMARYDTO(Int64 dATA_SUMMARY_ID, String aLIAS_NAME, String dESCRIPTION_INFO, Nullable<Int16> aVAILABLE_MARK, Nullable<Int64> vERSION, Nullable<Int16> sHARE_MARK, Nullable<DateTime> cREATE_TIME, Nullable<Int16> sTATUS, Nullable<Int16> dATA_SET_TYPE, List<Int64> rEL_TC_DATA_SUMMARY_ID, List<Int64> t_SHARED_OBJECT_POOL_OBJECT_POOL_ID, List<Int64> t_STORYBOARD_DATASET_SETTING_SETTING_ID, List<Int64> tEST_DATA_SETTING_DATA_SETTING_ID)
        {
			this.DATA_SUMMARY_ID = dATA_SUMMARY_ID;
			this.ALIAS_NAME = aLIAS_NAME;
			this.DESCRIPTION_INFO = dESCRIPTION_INFO;
			this.AVAILABLE_MARK = aVAILABLE_MARK;
			this.VERSION = vERSION;
			this.SHARE_MARK = sHARE_MARK;
			this.CREATE_TIME = cREATE_TIME;
			this.STATUS = sTATUS;
			this.DATA_SET_TYPE = dATA_SET_TYPE;
			this.REL_TC_DATA_SUMMARY_ID = rEL_TC_DATA_SUMMARY_ID;
			this.T_SHARED_OBJECT_POOL_OBJECT_POOL_ID = t_SHARED_OBJECT_POOL_OBJECT_POOL_ID;
			this.T_STORYBOARD_DATASET_SETTING_SETTING_ID = t_STORYBOARD_DATASET_SETTING_SETTING_ID;
			this.TEST_DATA_SETTING_DATA_SETTING_ID = tEST_DATA_SETTING_DATA_SETTING_ID;
        }
    }
}
