//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_TESTER_INFO"/> and <see cref="T_TESTER_INFODTO"/>.
    /// </summary>
    public static partial class T_TESTER_INFOAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_TESTER_INFODTO"/> converted from <see cref="T_TESTER_INFO"/>.</param>
        static partial void OnDTO(this T_TESTER_INFO entity, T_TESTER_INFODTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_TESTER_INFO"/> converted from <see cref="T_TESTER_INFODTO"/>.</param>
        static partial void OnEntity(this T_TESTER_INFODTO dto, T_TESTER_INFO entity);

        /// <summary>
        /// Converts this instance of <see cref="T_TESTER_INFODTO"/> to an instance of <see cref="T_TESTER_INFO"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_TESTER_INFODTO"/> to convert.</param>
        public static T_TESTER_INFO ToEntity(this T_TESTER_INFODTO dto)
        {
            if (dto == null) return null;

            var entity = new T_TESTER_INFO();

            entity.TESTER_ID = dto.TESTER_ID;
            entity.TESTER_NAME_LAST = dto.TESTER_NAME_LAST;
            entity.TESTER_NAME_M = dto.TESTER_NAME_M;
            entity.TESTER_NAME_F = dto.TESTER_NAME_F;
            entity.TESTER_LOGIN_NAME = dto.TESTER_LOGIN_NAME;
            entity.TESTER_PWD = dto.TESTER_PWD;
            entity.AVAILABLE_MARK = dto.AVAILABLE_MARK;
            entity.TESTER_MAIL = dto.TESTER_MAIL;
            entity.TESTER_NUMBER = dto.TESTER_NUMBER;
            entity.COMPANY_ID = dto.COMPANY_ID;
            entity.CREATOR_NAME = dto.CREATOR_NAME;
            entity.CREATE_TIME = dto.CREATE_TIME;
            entity.TESTER_DESC = dto.TESTER_DESC;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_TESTER_INFO"/> to an instance of <see cref="T_TESTER_INFODTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_TESTER_INFO"/> to convert.</param>
        public static T_TESTER_INFODTO ToDTO(this T_TESTER_INFO entity)
        {
            if (entity == null) return null;

            var dto = new T_TESTER_INFODTO();

            dto.TESTER_ID = entity.TESTER_ID;
            dto.TESTER_NAME_LAST = entity.TESTER_NAME_LAST;
            dto.TESTER_NAME_M = entity.TESTER_NAME_M;
            dto.TESTER_NAME_F = entity.TESTER_NAME_F;
            dto.TESTER_LOGIN_NAME = entity.TESTER_LOGIN_NAME;
            dto.TESTER_PWD = entity.TESTER_PWD;
            dto.AVAILABLE_MARK = entity.AVAILABLE_MARK;
            dto.TESTER_MAIL = entity.TESTER_MAIL;
            dto.TESTER_NUMBER = entity.TESTER_NUMBER;
            dto.COMPANY_ID = entity.COMPANY_ID;
            dto.CREATOR_NAME = entity.CREATOR_NAME;
            dto.CREATE_TIME = entity.CREATE_TIME;
            dto.TESTER_DESC = entity.TESTER_DESC;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TESTER_INFODTO"/> to an instance of <see cref="T_TESTER_INFO"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_TESTER_INFO> ToEntities(this IEnumerable<T_TESTER_INFODTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TESTER_INFO"/> to an instance of <see cref="T_TESTER_INFODTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_TESTER_INFODTO> ToDTOs(this IEnumerable<T_TESTER_INFO> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
