//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:21
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="T_TEST_BATCH_DETAIL"/> and <see cref="T_TEST_BATCH_DETAILDTO"/>.
    /// </summary>
    public static partial class T_TEST_BATCH_DETAILAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_BATCH_DETAILDTO"/> converted from <see cref="T_TEST_BATCH_DETAIL"/>.</param>
        static partial void OnDTO(this T_TEST_BATCH_DETAIL entity, T_TEST_BATCH_DETAILDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_BATCH_DETAIL"/> converted from <see cref="T_TEST_BATCH_DETAILDTO"/>.</param>
        static partial void OnEntity(this T_TEST_BATCH_DETAILDTO dto, T_TEST_BATCH_DETAIL entity);

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_BATCH_DETAILDTO"/> to an instance of <see cref="T_TEST_BATCH_DETAIL"/>.
        /// </summary>
        /// <param name="dto"><see cref="T_TEST_BATCH_DETAILDTO"/> to convert.</param>
        public static T_TEST_BATCH_DETAIL ToEntity(this T_TEST_BATCH_DETAILDTO dto)
        {
            if (dto == null) return null;

            var entity = new T_TEST_BATCH_DETAIL();

            entity.BAT_DTL_ID = dto.BAT_DTL_ID;
            entity.BAT_ID = dto.BAT_ID;
            entity.STORYOBARD_ID = dto.STORYOBARD_ID;
            entity.DTL_DESC = dto.DTL_DESC;
            entity.RUN_ORDER = dto.RUN_ORDER;
            entity.CREATE_TIME = dto.CREATE_TIME;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="T_TEST_BATCH_DETAIL"/> to an instance of <see cref="T_TEST_BATCH_DETAILDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="T_TEST_BATCH_DETAIL"/> to convert.</param>
        public static T_TEST_BATCH_DETAILDTO ToDTO(this T_TEST_BATCH_DETAIL entity)
        {
            if (entity == null) return null;

            var dto = new T_TEST_BATCH_DETAILDTO();

            dto.BAT_DTL_ID = entity.BAT_DTL_ID;
            dto.BAT_ID = entity.BAT_ID;
            dto.STORYOBARD_ID = entity.STORYOBARD_ID;
            dto.DTL_DESC = entity.DTL_DESC;
            dto.RUN_ORDER = entity.RUN_ORDER;
            dto.CREATE_TIME = entity.CREATE_TIME;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_BATCH_DETAILDTO"/> to an instance of <see cref="T_TEST_BATCH_DETAIL"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<T_TEST_BATCH_DETAIL> ToEntities(this IEnumerable<T_TEST_BATCH_DETAILDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="T_TEST_BATCH_DETAIL"/> to an instance of <see cref="T_TEST_BATCH_DETAILDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<T_TEST_BATCH_DETAILDTO> ToDTOs(this IEnumerable<T_TEST_BATCH_DETAIL> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
