//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:18:39
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Mars.Dto
{
    [DataContract()]
    public partial class V_OBJECT_SNAPSHOTDTO
    {
        [DataMember()]
        public Nullable<Int64> OBJECT_NAME_ID { get; set; }

        [DataMember()]
        public String OBJECT_HAPPY_NAME { get; set; }

        [DataMember()]
        public String COMMENT { get; set; }

        [DataMember()]
        public Nullable<Int64> APPLICATION_ID { get; set; }

        [DataMember()]
        public String ENUM_TYPE { get; set; }

        [DataMember()]
        public Int64 OBJECT_ID { get; set; }

        [DataMember()]
        public String OBJECT_TYPE { get; set; }

        [DataMember()]
        public String QUICK_ACCESS { get; set; }

        [DataMember()]
        public Nullable<Int16> TYPE_ID { get; set; }

        [DataMember()]
        public String TYPE_NAME { get; set; }

        [DataMember()]
        public String PEG_NAME { get; set; }

        [DataMember()]
        public String PEG_QUICK_ACCESS { get; set; }

        [DataMember()]
        public Nullable<Int64> PEG_ID { get; set; }

        [DataMember()]
        public Nullable<Int16> IS_CHECKERROR_OBJ { get; set; }

        public V_OBJECT_SNAPSHOTDTO()
        {
        }

        public V_OBJECT_SNAPSHOTDTO(Nullable<Int64> oBJECT_NAME_ID, String oBJECT_HAPPY_NAME, String cOMMENT, Nullable<Int64> aPPLICATION_ID, String eNUM_TYPE, Int64 oBJECT_ID, String oBJECT_TYPE, String qUICK_ACCESS, Nullable<Int16> tYPE_ID, String tYPE_NAME, String pEG_NAME, String pEG_QUICK_ACCESS, Nullable<Int64> pEG_ID, Nullable<Int16> iS_CHECKERROR_OBJ)
        {
			this.OBJECT_NAME_ID = oBJECT_NAME_ID;
			this.OBJECT_HAPPY_NAME = oBJECT_HAPPY_NAME;
			this.COMMENT = cOMMENT;
			this.APPLICATION_ID = aPPLICATION_ID;
			this.ENUM_TYPE = eNUM_TYPE;
			this.OBJECT_ID = oBJECT_ID;
			this.OBJECT_TYPE = oBJECT_TYPE;
			this.QUICK_ACCESS = qUICK_ACCESS;
			this.TYPE_ID = tYPE_ID;
			this.TYPE_NAME = tYPE_NAME;
			this.PEG_NAME = pEG_NAME;
			this.PEG_QUICK_ACCESS = pEG_QUICK_ACCESS;
			this.PEG_ID = pEG_ID;
			this.IS_CHECKERROR_OBJ = iS_CHECKERROR_OBJ;
        }
    }
}
