//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/01/02 - 12:19:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Mars.Model;

namespace Mars.Dto
{

    /// <summary>
    /// Assembler for <see cref="V_STB_PROJ_APP_FULLVISION"/> and <see cref="V_STB_PROJ_APP_FULLVISIONDTO"/>.
    /// </summary>
    public static partial class V_STB_PROJ_APP_FULLVISIONAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="V_STB_PROJ_APP_FULLVISIONDTO"/> converted from <see cref="V_STB_PROJ_APP_FULLVISION"/>.</param>
        static partial void OnDTO(this V_STB_PROJ_APP_FULLVISION entity, V_STB_PROJ_APP_FULLVISIONDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="V_STB_PROJ_APP_FULLVISION"/> converted from <see cref="V_STB_PROJ_APP_FULLVISIONDTO"/>.</param>
        static partial void OnEntity(this V_STB_PROJ_APP_FULLVISIONDTO dto, V_STB_PROJ_APP_FULLVISION entity);

        /// <summary>
        /// Converts this instance of <see cref="V_STB_PROJ_APP_FULLVISIONDTO"/> to an instance of <see cref="V_STB_PROJ_APP_FULLVISION"/>.
        /// </summary>
        /// <param name="dto"><see cref="V_STB_PROJ_APP_FULLVISIONDTO"/> to convert.</param>
        public static V_STB_PROJ_APP_FULLVISION ToEntity(this V_STB_PROJ_APP_FULLVISIONDTO dto)
        {
            if (dto == null) return null;

            var entity = new V_STB_PROJ_APP_FULLVISION();

            entity.PROJECT_ID = dto.PROJECT_ID;
            entity.CREATE_TIME = dto.CREATE_TIME;
            entity.CREATER = dto.CREATER;
            entity.DESCRIPTION = dto.DESCRIPTION;
            entity.STORYBOARD_ID = dto.STORYBOARD_ID;
            entity.STORYBOARD_NAME = dto.STORYBOARD_NAME;
            entity.APPLICATION_ID = dto.APPLICATION_ID;
            entity.APP_SHORT_NAME = dto.APP_SHORT_NAME;
            entity.APPLICATION_TYPE_ID = dto.APPLICATION_TYPE_ID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="V_STB_PROJ_APP_FULLVISION"/> to an instance of <see cref="V_STB_PROJ_APP_FULLVISIONDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="V_STB_PROJ_APP_FULLVISION"/> to convert.</param>
        public static V_STB_PROJ_APP_FULLVISIONDTO ToDTO(this V_STB_PROJ_APP_FULLVISION entity)
        {
            if (entity == null) return null;

            var dto = new V_STB_PROJ_APP_FULLVISIONDTO();

            dto.PROJECT_ID = entity.PROJECT_ID;
            dto.CREATE_TIME = entity.CREATE_TIME;
            dto.CREATER = entity.CREATER;
            dto.DESCRIPTION = entity.DESCRIPTION;
            dto.STORYBOARD_ID = entity.STORYBOARD_ID;
            dto.STORYBOARD_NAME = entity.STORYBOARD_NAME;
            dto.APPLICATION_ID = entity.APPLICATION_ID;
            dto.APP_SHORT_NAME = entity.APP_SHORT_NAME;
            dto.APPLICATION_TYPE_ID = entity.APPLICATION_TYPE_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="V_STB_PROJ_APP_FULLVISIONDTO"/> to an instance of <see cref="V_STB_PROJ_APP_FULLVISION"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<V_STB_PROJ_APP_FULLVISION> ToEntities(this IEnumerable<V_STB_PROJ_APP_FULLVISIONDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="V_STB_PROJ_APP_FULLVISION"/> to an instance of <see cref="V_STB_PROJ_APP_FULLVISIONDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<V_STB_PROJ_APP_FULLVISIONDTO> ToDTOs(this IEnumerable<V_STB_PROJ_APP_FULLVISION> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
