//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARSUtility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MARSUtility.Properties.ServiceResource", typeof(ServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t end Navigate current Test Steps. .
        /// </summary>
        internal static string _SERVICE_ERROR_CLIENT_CANT_END_NAVIGATE {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_CLIENT_CANT_END_NAVIGATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start to Navigate Test flows..
        /// </summary>
        internal static string _SERVICE_ERROR_CLIENT_CANT_START_NAVIGATE {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_CLIENT_CANT_START_NAVIGATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Mars Testing framework Service First..
        /// </summary>
        internal static string _SERVICE_ERROR_CLIENT_CONNECT_2_SERVICE_FIRST {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_CLIENT_CONNECT_2_SERVICE_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from client side is NULL..
        /// </summary>
        internal static string _SERVICE_ERROR_CLIENT_DATA_ISNULL_PARA_0 {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_CLIENT_DATA_ISNULL_PARA_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword name from client side is NULL..
        /// </summary>
        internal static string _SERVICE_ERROR_CLIENT_KEYWORDNAME_ISNULL_PARA_0 {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_CLIENT_KEYWORDNAME_ISNULL_PARA_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop is not a int. Loop:[{0}].
        /// </summary>
        internal static string _SERVICE_ERROR_CLIENT_LOOP_ISNOT_A_NUMBER_PARA_1 {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_CLIENT_LOOP_ISNOT_A_NUMBER_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop from client side is NULL..
        /// </summary>
        internal static string _SERVICE_ERROR_CLIENT_LOOP_ISNULL_PARA_0 {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_CLIENT_LOOP_ISNULL_PARA_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectName from client side is NULL..
        /// </summary>
        internal static string _SERVICE_ERROR_CLIENT_OBJECTNAME_ISNULL_PARA_0 {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_CLIENT_OBJECTNAME_ISNULL_PARA_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File name passed when call switch Data..
        /// </summary>
        internal static string _SERVICE_ERROR_CLIENT_SWITCH_DATA_NO_FILENAME_PARA_0 {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_CLIENT_SWITCH_DATA_NO_FILENAME_PARA_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow Exception occurres when Connect to Server [{1}].Exception:[{0}].
        /// </summary>
        internal static string _SERVICE_ERROR_CLIENT_UNKNOW {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_CLIENT_UNKNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No host setting for WCF server..
        /// </summary>
        internal static string _SERVICE_ERROR_NO_HOST_SETTING {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_NO_HOST_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No port setting for WCF server..
        /// </summary>
        internal static string _SERVICE_ERROR_NO_PORT_SETTING {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_NO_PORT_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No protocol setting for WCF server..
        /// </summary>
        internal static string _SERVICE_ERROR_NO_PROTOCO_SETTING {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_NO_PROTOCO_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow Exception occurres when start Service. Exception:[{0}].
        /// </summary>
        internal static string _SERVICE_ERROR_NO_SERVICE_START_UNKNOW {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_NO_SERVICE_START_UNKNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow Exception occurres when stop Service. Exception:[{0}].
        /// </summary>
        internal static string _SERVICE_ERROR_NO_SERVICE_STOP_UNKNOW {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_NO_SERVICE_STOP_UNKNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ServiceName setting for WCF server..
        /// </summary>
        internal static string _SERVICE_ERROR_NO_SERVICENAME_SETTING {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_NO_SERVICENAME_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teststep is required but [{0}] find..
        /// </summary>
        internal static string _SERVICE_ERROR_OBJECT_TYPE_IS_NOT_TEST_STEP {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_OBJECT_TYPE_IS_NOT_TEST_STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find loaded data file in Memory. FileName:[{0}].
        /// </summary>
        internal static string _SERVICE_ERROR_SERVER_NO_DATAFILE_CREATED_PARA_1 {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_SERVER_NO_DATAFILE_CREATED_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Test case name passed from client. .
        /// </summary>
        internal static string _SERVICE_ERROR_SERVER_NO_TESTCASENAME_PARA_0 {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_SERVER_NO_TESTCASENAME_PARA_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Test suite instance is setting on server side. .
        /// </summary>
        internal static string _SERVICE_ERROR_SERVER_NO_TESTSUITE_SETTING {
            get {
                return ResourceManager.GetString("_SERVICE_ERROR_SERVER_NO_TESTSUITE_SETTING", resourceCulture);
            }
        }
    }
}
