//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_APP_PROJ
    {
        public long RELATIONSHIP_ID { get; set; }
        public Nullable<long> APPLICATION_ID { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
    
        public virtual T_TEST_PROJECT T_TEST_PROJECT { get; set; }
    }
}
