//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COMPARE_CONNECTIONS
    {
        public decimal DBCONN_ID { get; set; }
        public string DBCONN_NAME { get; set; }
        public string TYPE { get; set; }
        public string HOST { get; set; }
        public string PORT { get; set; }
        public string PROTOCOL { get; set; }
        public string SERVICE_NAME { get; set; }
        public string USERID { get; set; }
        public string PASSWORD { get; set; }
    }
}
