//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUI_COMPONENT_TYPE_DIC
    {
        public T_GUI_COMPONENT_TYPE_DIC()
        {
            this.T_DIC_RELATION_KEYWORD = new HashSet<T_DIC_RELATION_KEYWORD>();
            this.T_REGISTED_OBJECT = new HashSet<T_REGISTED_OBJECT>();
        }
    
        public long TYPE_ID { get; set; }
        public string TYPE_NAME { get; set; }
        public Nullable<short> APPLICATION_TYPE_ID { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<T_DIC_RELATION_KEYWORD> T_DIC_RELATION_KEYWORD { get; set; }
        public virtual ICollection<T_REGISTED_OBJECT> T_REGISTED_OBJECT { get; set; }
    }
}
