//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_KEYWORD
    {
        public T_KEYWORD()
        {
            this.T_DIC_RELATION_KEYWORD = new HashSet<T_DIC_RELATION_KEYWORD>();
            this.T_TEST_STEPS = new HashSet<T_TEST_STEPS>();
        }
    
        public long KEY_WORD_ID { get; set; }
        public string KEY_WORD_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<short> KEY_WORD_POSITION_ID { get; set; }
        public string ENTRY_IN_DATA_FILE { get; set; }
    
        public virtual ICollection<T_DIC_RELATION_KEYWORD> T_DIC_RELATION_KEYWORD { get; set; }
        public virtual ICollection<T_TEST_STEPS> T_TEST_STEPS { get; set; }
    }
}
