//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROJ_TC_MGR
    {
        public long STORYBOARD_DETAIL_ID { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
        public Nullable<long> TEST_CASE_ID { get; set; }
        public Nullable<long> STORYBOARD_ID { get; set; }
        public Nullable<short> RUN_TYPE { get; set; }
        public Nullable<long> DEPENDS_ON { get; set; }
        public Nullable<long> RUN_ORDER { get; set; }
        public Nullable<long> LATEST_TEST_MARK_ID { get; set; }
        public Nullable<decimal> RECORD_VERSION { get; set; }
        public string ALIAS_NAME { get; set; }
    
        public virtual T_STORYBOARD_SUMMARY T_STORYBOARD_SUMMARY { get; set; }
        public virtual T_TEST_CASE_SUMMARY T_TEST_CASE_SUMMARY { get; set; }
        public virtual T_TEST_PROJECT T_TEST_PROJECT { get; set; }
    }
}
