//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REGISTERED_APPS
    {
        public long APPLICATION_ID { get; set; }
        public string APP_SHORT_NAME { get; set; }
        public string PROCESS_IDENTIFIER { get; set; }
        public string STARTER_PATH { get; set; }
        public string STARTER_COMMAND { get; set; }
        public string VERSION { get; set; }
        public string COMMENT { get; set; }
        public Nullable<short> APPLICATION_TYPE_ID { get; set; }
        public string RECORD_CREATE_PERSON { get; set; }
        public Nullable<System.DateTime> RECORD_CREATE_DATE { get; set; }
        public string EXTRAREQUIREMENT { get; set; }
        public string EXTRAPOPUPMENU { get; set; }
    }
}
