//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REGISTED_OBJECT
    {
        public T_REGISTED_OBJECT()
        {
            this.T_TEST_STEPS = new HashSet<T_TEST_STEPS>();
        }
    
        public long OBJECT_ID { get; set; }
        public string OBJECT_HAPPY_NAME { get; set; }
        public Nullable<long> APPLICATION_ID { get; set; }
        public Nullable<long> TYPE_ID { get; set; }
        public string QUICK_ACCESS { get; set; }
        public string OBJECT_TYPE { get; set; }
        public string COMMENT { get; set; }
        public string ENUM_TYPE { get; set; }
    
        public virtual T_GUI_COMPONENT_TYPE_DIC T_GUI_COMPONENT_TYPE_DIC { get; set; }
        public virtual ICollection<T_TEST_STEPS> T_TEST_STEPS { get; set; }
    }
}
