//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_PROJECT
    {
        public T_TEST_PROJECT()
        {
            this.REL_APP_PROJ = new HashSet<REL_APP_PROJ>();
            this.REL_TEST_SUIT_PROJECT = new HashSet<REL_TEST_SUIT_PROJECT>();
            this.T_PROJ_TC_MGR = new HashSet<T_PROJ_TC_MGR>();
            this.T_PROJECT_DATA_SOURCE = new HashSet<T_PROJECT_DATA_SOURCE>();
        }
    
        public long PROJECT_ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public string PROJECT_DESCRIPTION { get; set; }
        public string CREATOR { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<short> STATUS { get; set; }
    
        public virtual ICollection<REL_APP_PROJ> REL_APP_PROJ { get; set; }
        public virtual ICollection<REL_TEST_SUIT_PROJECT> REL_TEST_SUIT_PROJECT { get; set; }
        public virtual ICollection<T_PROJ_TC_MGR> T_PROJ_TC_MGR { get; set; }
        public virtual ICollection<T_PROJECT_DATA_SOURCE> T_PROJECT_DATA_SOURCE { get; set; }
    }
}
