//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_DATA_SUMMARY
    {
        public T_TEST_DATA_SUMMARY()
        {
            this.REL_TC_DATA_SUMMARY = new HashSet<REL_TC_DATA_SUMMARY>();
            this.T_SHARED_OBJECT_POOL = new HashSet<T_SHARED_OBJECT_POOL>();
            this.TEST_DATA_SETTING = new HashSet<TEST_DATA_SETTING>();
        }
    
        public long DATA_SUMMARY_ID { get; set; }
        public string ALIAS_NAME { get; set; }
        public string DESCRIPTION_INFO { get; set; }
        public Nullable<short> AVAILABLE_MARK { get; set; }
        public Nullable<long> VERSION { get; set; }
        public Nullable<short> SHARE_MARK { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> DATA_SET_TYPE { get; set; }
    
        public virtual ICollection<REL_TC_DATA_SUMMARY> REL_TC_DATA_SUMMARY { get; set; }
        public virtual ICollection<T_SHARED_OBJECT_POOL> T_SHARED_OBJECT_POOL { get; set; }
        public virtual ICollection<TEST_DATA_SETTING> TEST_DATA_SETTING { get; set; }
    }
}
