//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_CASE_VIEW2
    {
        public string PROJECT_NAME { get; set; }
        public string TEST_SUITE_NAME { get; set; }
        public string TEST_CASE_NAME { get; set; }
        public string KEY_WORD_NAME { get; set; }
        public long OBJECT_ID { get; set; }
        public string OBJECT_HAPPY_NAME { get; set; }
        public string COLUMN_ROW_SETTING { get; set; }
        public string DATA_VALUE { get; set; }
        public Nullable<decimal> LOOP_ID { get; set; }
        public long STEPS_ID { get; set; }
    }
}
