//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OBJECT_APPS
    {
        public Nullable<long> APPLICATION_ID { get; set; }
        public long OBJECT_ID { get; set; }
        public string COMMENT { get; set; }
        public string ENUM_TYPE { get; set; }
        public string OBJECT_HAPPY_NAME { get; set; }
        public string OBJECT_TYPE { get; set; }
        public string QUICK_ACCESS { get; set; }
        public Nullable<long> TYPE_ID { get; set; }
        public Nullable<long> APP_APPLICATION_ID { get; set; }
        public string APP_SHORT_NAME { get; set; }
        public Nullable<short> APPLICATION_TYPE_ID { get; set; }
        public string COMMENT_APP { get; set; }
        public string EXTRAPOPUPMENU { get; set; }
        public string EXTRAREQUIREMENT { get; set; }
        public string PROCESS_IDENTIFIER { get; set; }
        public string STARTER_COMMAND { get; set; }
        public string STARTER_PATH { get; set; }
        public string VERSION { get; set; }
        public Nullable<short> TYPE_APPLICATION_TYPE_ID { get; set; }
        public string TYPE_DESCRPTION { get; set; }
        public Nullable<long> TYP_TYPE_ID { get; set; }
        public string TYPE_NAME { get; set; }
    }
}
