//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.DB.Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STORYBOARD_TEST_FULLVISION
    {
        public long STORYBOARD_DETAIL_ID { get; set; }
        public string STORYBOARD_NAME { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public string PROJECT_DESCRIPTION { get; set; }
        public string TEST_CASE_NAME { get; set; }
        public Nullable<long> TEST_CASE_ID { get; set; }
        public string TEST_STEP_DESCRIPTION { get; set; }
        public Nullable<long> TEST_SUITE_ID { get; set; }
        public string TEST_SUITE_NAME { get; set; }
        public string TEST_SUITE_DESCRIPTION { get; set; }
        public Nullable<long> RUN_ORDER { get; set; }
        public Nullable<long> DEPENDS_ON { get; set; }
        public string ALIAS_NAME { get; set; }
        public string PARENT_ALIAS_NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
        public Nullable<short> TEST_RUN_VALUE { get; set; }
        public Nullable<long> LATEST_TEST_MARK_ID { get; set; }
        public Nullable<long> HIST_LATEST_TEST_MARK_ID { get; set; }
        public Nullable<long> HIST_ID { get; set; }
        public Nullable<long> HIST_TEST_ID { get; set; }
        public Nullable<System.DateTime> TEST_CASE_BEGIN_TIME { get; set; }
        public Nullable<System.DateTime> TEST_CASE_END_TIME { get; set; }
        public string HIST_TEST_RESULT_IN_TEXT { get; set; }
        public Nullable<short> HIST_TEST_MODE { get; set; }
        public Nullable<short> HIST_RESULT { get; set; }
    }
}
