//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFlowClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestFlowClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Keywords Section in app.config file. .
        /// </summary>
        internal static string _APP_NO_SECTION_KEWWORDS {
            get {
                return ResourceManager.GetString("_APP_NO_SECTION_KEWWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such key exists on the section..
        /// </summary>
        internal static string _APP_NO_SECTION_KEY {
            get {
                return ResourceManager.GetString("_APP_NO_SECTION_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error,No &quot;ObjectSource&quot; item in &lt;appsettings&gt;, Value shoulde be &quot;xlsFile&quot; or &quot;dataBalse&quot;..
        /// </summary>
        internal static string _APP_NO_SECTION_OBJECT_FROM {
            get {
                return ResourceManager.GetString("_APP_NO_SECTION_OBJECT_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Special Section Exists..
        /// </summary>
        internal static string _APP_NO_SECTION_SPECIAL {
            get {
                return ResourceManager.GetString("_APP_NO_SECTION_SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setting for Keyword source. .
        /// </summary>
        internal static string _APP_NO_SETTING_KEYWORD_FROM {
            get {
                return ResourceManager.GetString("_APP_NO_SETTING_KEYWORD_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such setting ([{0}]) for Keyword from..
        /// </summary>
        internal static string _APP_WRONG_VALUE_SETTING_KEYWORD_FROM {
            get {
                return ResourceManager.GetString("_APP_WRONG_VALUE_SETTING_KEYWORD_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, value for &quot;ObjectSource&quot; should be &quot;xlsFile&quot; or &quot;dataBase&quot;..
        /// </summary>
        internal static string _APP_WRONG_VALUE_SETTING_OBJECT_FROM {
            get {
                return ResourceManager.GetString("_APP_WRONG_VALUE_SETTING_OBJECT_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Update Batch file status. Testsuite Name:[{0}]-TestCase Name:[{1}], RowNumber:[{2}], Error Information:[{3}].
        /// </summary>
        internal static string _BATCH_ERROR_CANT_UPDATE_PARA_4 {
            get {
                return ResourceManager.GetString("_BATCH_ERROR_CANT_UPDATE_PARA_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception comes out when Read Xls file by Jet.
        /// </summary>
        internal static string _BATCH_ERROR_JET_READ_EXCEPTION {
            get {
                return ResourceManager.GetString("_BATCH_ERROR_JET_READ_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Batch Sheet(xls Mode) or Test suite information (Database mode).
        /// </summary>
        internal static string _BATCH_ERROR_NO_EXECUTE_TABLE {
            get {
                return ResourceManager.GetString("_BATCH_ERROR_NO_EXECUTE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one application currently support..
        /// </summary>
        internal static string _COMPILER_APPLICATON_LENTH_NOT_1 {
            get {
                return ResourceManager.GetString("_COMPILER_APPLICATON_LENTH_NOT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors [{0}] come when load objects file:[{1}].
        /// </summary>
        internal static string _COMPILER_CANT_LOAD_OBJECTFILE {
            get {
                return ResourceManager.GetString("_COMPILER_CANT_LOAD_OBJECTFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;DefaultApplication&quot; desn&apos;t exist on App.config..
        /// </summary>
        internal static string _COMPILER_NO_DEFAULT_APPLICATION_INFO {
            get {
                return ResourceManager.GetString("_COMPILER_NO_DEFAULT_APPLICATION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such object Indentifier information. Object HappName:[{0}], PegWindow:[{1}].
        /// </summary>
        internal static string _COMPILER_NO_OBJECT_INDENTIFY_INFO {
            get {
                return ResourceManager.GetString("_COMPILER_NO_OBJECT_INDENTIFY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pegwindow information is available when validate step settings..
        /// </summary>
        internal static string _COMPILER_NO_PEGWINDOW_FOR_TESTSTEP_FIND {
            get {
                return ResourceManager.GetString("_COMPILER_NO_PEGWINDOW_FOR_TESTSTEP_FIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No object Identifier information found for the current Pegwindow:[{0}].
        /// </summary>
        internal static string _COMPILER_NO_PEGWINDOW_IDENTIFIERINFO {
            get {
                return ResourceManager.GetString("_COMPILER_NO_PEGWINDOW_IDENTIFIERINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC information is required for the current Test step. [{0}].
        /// </summary>
        internal static string _COMPILER_NO_RC {
            get {
                return ResourceManager.GetString("_COMPILER_NO_RC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Steps List is passed to Compiler. .
        /// </summary>
        internal static string _COMPILER_NO_STEPS {
            get {
                return ResourceManager.GetString("_COMPILER_NO_STEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such application [{0}] configed in Database or Config file. .
        /// </summary>
        internal static string _COMPILER_NO_SUCH_APPLICATION_CONFIGED {
            get {
                return ResourceManager.GetString("_COMPILER_NO_SUCH_APPLICATION_CONFIGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such Object file exists:[{0}].
        /// </summary>
        internal static string _COMPILER_NO_SUCH_OBJECT_FILE {
            get {
                return ResourceManager.GetString("_COMPILER_NO_SUCH_OBJECT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find Pegwindow object([{0}]) from Application:[{1}].
        /// </summary>
        internal static string _COMPILER_NO_SUCH_PEGWINDOW_INFO {
            get {
                return ResourceManager.GetString("_COMPILER_NO_SUCH_PEGWINDOW_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current TestSteps and TestSuite don&apos;t match the required.Current Serving TestSuite And TestCase:[{0}-{1}].Required TestCase Info:[{2}-{3}].
        /// </summary>
        internal static string _COMPILER_NOT_THE_CURRENT_TESTCASE_SERVIING_PARA_4 {
            get {
                return ResourceManager.GetString("_COMPILER_NOT_THE_CURRENT_TESTCASE_SERVIING_PARA_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object types mismatch, ConfigTestApplication is required. But type {0} find..
        /// </summary>
        internal static string _COMPILER_OBJECT_TYPE_MISMATCH_CONFIGTEST_REQUIRED {
            get {
                return ResourceManager.GetString("_COMPILER_OBJECT_TYPE_MISMATCH_CONFIGTEST_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registerd applications information in app.config should be &quot;config&quot; or &quot;database&quot;..
        /// </summary>
        internal static string _COMPILER_SETCURRENT_APPLICATION_VALUEFORMAT_ERROR {
            get {
                return ResourceManager.GetString("_COMPILER_SETCURRENT_APPLICATION_VALUEFORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current keyword is not a sub-action keyword. Keyword:[{0}].
        /// </summary>
        internal static string _COMPILER_SUBACTION_KEYWORD_IS_NOT_A_SUBACTION_PARA_1 {
            get {
                return ResourceManager.GetString("_COMPILER_SUBACTION_KEYWORD_IS_NOT_A_SUBACTION_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No peg-window information when pre-compiler sub actions. AppcationName:[{0}], Pegwindows:[{1}].
        /// </summary>
        internal static string _COMPILER_SUBACTION_NO_PEGININFORMATION_PARA_2 {
            get {
                return ResourceManager.GetString("_COMPILER_SUBACTION_NO_PEGININFORMATION_PARA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subaction test step object is NULL..
        /// </summary>
        internal static string _COMPILER_SUBACTION_OBJECT_ISNULL_PARA_0 {
            get {
                return ResourceManager.GetString("_COMPILER_SUBACTION_OBJECT_ISNULL_PARA_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Except a Teststep object,but other type object is found.
        /// </summary>
        internal static string _COMPILER_TEST_STEP_OBJECT_EXPECT {
            get {
                return ResourceManager.GetString("_COMPILER_TEST_STEP_OBJECT_EXPECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow error when Call GetDefaultApplication. Error Message is:[{0}].
        /// </summary>
        internal static string _COMPILER_UNKNOW_ERROR_GET_DEFAULT_APP {
            get {
                return ResourceManager.GetString("_COMPILER_UNKNOW_ERROR_GET_DEFAULT_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception when convert data from OleDB:[{0}].
        /// </summary>
        internal static string _COMPILER_UNKNOW_GETDATA_FROM_DICFILE {
            get {
                return ResourceManager.GetString("_COMPILER_UNKNOW_GETDATA_FROM_DICFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions when Load a sheet from Excel. SheetName:[{0}] ,Exceptions:[{1}].
        /// </summary>
        internal static string _EXCEL_FILE_CANT_LOADSHEET_PARA_2 {
            get {
                return ResourceManager.GetString("_EXCEL_FILE_CANT_LOADSHEET_PARA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions occur when expand an excel column. Exception:{0}.
        /// </summary>
        internal static string _JET_DB_CMD_EXPAND_COLUMN_PARA_1 {
            get {
                return ResourceManager.GetString("_JET_DB_CMD_EXPAND_COLUMN_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant&apos;t Open Ject DB connections with exception:{0}.
        /// </summary>
        internal static string _JET_DB_CONNECTOIN_OPEN_PARA_1 {
            get {
                return ResourceManager.GetString("_JET_DB_CONNECTOIN_OPEN_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions occur, when a non-query sql executed. Sql:[{0}] Exceptions:[{1}].
        /// </summary>
        internal static string _JET_DB_EXCEPTION_WHEN_RUN_NON_QUERY_PARA_2 {
            get {
                return ResourceManager.GetString("_JET_DB_EXCEPTION_WHEN_RUN_NON_QUERY_PARA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions occurred when ran Query Sql on Jet DB. Sql:[{0}], Exception:[{1}].
        /// </summary>
        internal static string _JET_DB_EXCEPTION_WHEN_RUN_QUERY_PARA_2 {
            get {
                return ResourceManager.GetString("_JET_DB_EXCEPTION_WHEN_RUN_QUERY_PARA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields&apos; Lenght doesn&apos;t match values&apos; length before call insert into clause on Jet DB. Fields&apos; Lenght:[{0}], Values&apos; Length:[{1}].
        /// </summary>
        internal static string _JET_DB_FIELDNAMES_DNTMATCH_VALUES_PARA_2 {
            get {
                return ResourceManager.GetString("_JET_DB_FIELDNAMES_DNTMATCH_VALUES_PARA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions occur when get table&apos;s columns count.Exception:{0}.
        /// </summary>
        internal static string _JET_DB_GET_COLUMN_EXCEPTION_PARA_1 {
            get {
                return ResourceManager.GetString("_JET_DB_GET_COLUMN_EXCEPTION_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ole DB Driver doesn&apos;t support column expanding. Now, the current Loop count is greater than Data file contained. Make sure that columns of data file is more than :{0}.
        /// </summary>
        internal static string _JET_DB_NO_EXPAND_COLUMN_SUPPORT_PARA_1 {
            get {
                return ResourceManager.GetString("_JET_DB_NO_EXPAND_COLUMN_SUPPORT_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallSubAction keyword should contain Testsuitename and TestCaseName. Formatter shoulde :TestSuiteName;TestCaseName. Current Value:[{0}].
        /// </summary>
        internal static string _KEYWORDS_CALL_FORMATTER_PARA_1 {
            get {
                return ResourceManager.GetString("_KEYWORDS_CALL_FORMATTER_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value setting information for IF keyword..
        /// </summary>
        internal static string _KEYWORDS_IF_FORMATTER_NO_VALUE_PARA_0 {
            get {
                return ResourceManager.GetString("_KEYWORDS_IF_FORMATTER_NO_VALUE_PARA_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF keyword setting is wrong.  Wrong Item of value :[{0}].
        /// </summary>
        internal static string _KEYWORDS_IF_FORMATTER_SETTING_ERROR_PARA_1 {
            get {
                return ResourceManager.GetString("_KEYWORDS_IF_FORMATTER_SETTING_ERROR_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such keyword name configured[{0}]..
        /// </summary>
        internal static string _KEYWORDS_NO_SUCH_FUNCTION {
            get {
                return ResourceManager.GetString("_KEYWORDS_NO_SUCH_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No keyword concept [{0}] found..
        /// </summary>
        internal static string _KEYWORDS_NO_SUCH_KEYWORDS_CONCEPT_FOUND {
            get {
                return ResourceManager.GetString("_KEYWORDS_NO_SUCH_KEYWORDS_CONCEPT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword Parameter class [{0}] should be inherited from KeyWordsValidate and implement IKeyWordParse.
        /// </summary>
        internal static string _KEYWORDS_PARSE_CONFIGED_OBJECT_TYPE_WRONG {
            get {
                return ResourceManager.GetString("_KEYWORDS_PARSE_CONFIGED_OBJECT_TYPE_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such object information.ApplicationShortName:[{0}],Pegwindow:[{1}],ObjectName:[{2}].
        /// </summary>
        internal static string _KEYWORDS_PARSE_NO_SUCH_OBJECT_UNDER_PEGWINDOW {
            get {
                return ResourceManager.GetString("_KEYWORDS_PARSE_NO_SUCH_OBJECT_UNDER_PEGWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such pegwindow informtion [{0}] under application [{1}] objects..
        /// </summary>
        internal static string _KEYWORDS_PARSE_NO_SUCH_PEGWINDOW {
            get {
                return ResourceManager.GetString("_KEYWORDS_PARSE_NO_SUCH_PEGWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such applicatioin short name[{0}] when parse keyword..
        /// </summary>
        internal static string _KEYWORDS_PARSE_NO_SUCHAPPLICATION_SHORTNAME {
            get {
                return ResourceManager.GetString("_KEYWORDS_PARSE_NO_SUCHAPPLICATION_SHORTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t reflection the class [{0}], exception message is :[{1}].
        /// </summary>
        internal static string _KEYWORDS_PARSE_REFLECTION {
            get {
                return ResourceManager.GetString("_KEYWORDS_PARSE_REFLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create Parse object Instance for class name:[{0}].
        /// </summary>
        internal static string _KEYWORDS_PARSE_REFLECTION_NULL {
            get {
                return ResourceManager.GetString("_KEYWORDS_PARSE_REFLECTION_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such application short name [{0}] defined..
        /// </summary>
        internal static string _KEYWORDS_SETTING_NO_SUCHAPPLICATION_SHORTNAME {
            get {
                return ResourceManager.GetString("_KEYWORDS_SETTING_NO_SUCHAPPLICATION_SHORTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Run-From value find. .
        /// </summary>
        internal static string _KEYWORDS_UNSUPPORT_RUN_FROM {
            get {
                return ResourceManager.GetString("_KEYWORDS_UNSUPPORT_RUN_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string _NO_ERROR {
            get {
                return ResourceManager.GetString("_NO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is Null.
        /// </summary>
        internal static string _OBJECT_IS_NULL {
            get {
                return ResourceManager.GetString("_OBJECT_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception find when create empty QTP/UFT test.Exception:[{0}].
        /// </summary>
        internal static string _QTP_ERROR_CREATE_EMPTYTEST {
            get {
                return ResourceManager.GetString("_QTP_ERROR_CREATE_EMPTYTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions when call QTP functions:[{0}].
        /// </summary>
        internal static string _QTP_ERROR_GENERAL {
            get {
                return ResourceManager.GetString("_QTP_ERROR_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTP/UFT instance is null. .
        /// </summary>
        internal static string _QTP_ERROR_INSTANCE_NULL {
            get {
                return ResourceManager.GetString("_QTP_ERROR_INSTANCE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions when refreshs QTP:[{0}].
        /// </summary>
        internal static string _QTP_ERROR_REFRESH {
            get {
                return ResourceManager.GetString("_QTP_ERROR_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception ocurres, when set Test Addins. Exception:[{0}].
        /// </summary>
        internal static string _QTP_ERROR_SETTINGADDINS {
            get {
                return ResourceManager.GetString("_QTP_ERROR_SETTINGADDINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t validate Runnable script with error message:[{0}].
        /// </summary>
        internal static string _QTP_ERROR_VALIDATE {
            get {
                return ResourceManager.GetString("_QTP_ERROR_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Such Registered application Info:[{0}].
        /// </summary>
        internal static string _REG_APPS_NO_SUCH_APPLICATION_SHORTNAMEORPATH {
            get {
                return ResourceManager.GetString("_REG_APPS_NO_SUCH_APPLICATION_SHORTNAMEORPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions occur when Get data from cell. Cell Index:[{0}], Column Index:[{1}] Exceptions:[{2}].
        /// </summary>
        internal static string _TCDATA_DATA_CELL_EXCEPTION_PARA_3 {
            get {
                return ResourceManager.GetString("_TCDATA_DATA_CELL_EXCEPTION_PARA_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required more column than result can support..
        /// </summary>
        internal static string _TCDATA_DATA_COLUMN_EXCEED {
            get {
                return ResourceManager.GetString("_TCDATA_DATA_COLUMN_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions when insert object to Data File. DataFile:[{0}], ObjectName:[{1}], Exception:[{2}].
        /// </summary>
        internal static string _TCDATA_DATA_INSERT_OBJECT_EXCEPTION_PARA_3 {
            get {
                return ResourceManager.GetString("_TCDATA_DATA_INSERT_OBJECT_EXCEPTION_PARA_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data return for the cell. Cell Index:[{0}], Column Index:[{1}].
        /// </summary>
        internal static string _TCDATA_DATA_NO_SPECIAL_CELLDATA_PARA_2 {
            get {
                return ResourceManager.GetString("_TCDATA_DATA_NO_SPECIAL_CELLDATA_PARA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions occur when Update to Cell. Cell Index:[{0}], Column Index:[{1}] Exceptions:[{2}].
        /// </summary>
        internal static string _TCDATA_DATA_UPDATE_EXCEPTION_PARA_3 {
            get {
                return ResourceManager.GetString("_TCDATA_DATA_UPDATE_EXCEPTION_PARA_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iLoop value is greater than current Data set lenght. iLoop:[{0}], Object Index:[{1}], CurrentLength:[{2}].
        /// </summary>
        internal static string _TCDATA_DATA_UPDATECACHE_LOOPID_GREATER_PARA_3 {
            get {
                return ResourceManager.GetString("_TCDATA_DATA_UPDATECACHE_LOOPID_GREATER_PARA_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iLoop value is less than 0. iLoop:[{0}], Objext Index:[{1}].
        /// </summary>
        internal static string _TCDATA_DATA_UPDATECACHE_LOOPID_LESS_0_PARA_2 {
            get {
                return ResourceManager.GetString("_TCDATA_DATA_UPDATECACHE_LOOPID_LESS_0_PARA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Object index found on cache. Object Index:[{0}].
        /// </summary>
        internal static string _TCDATA_DATA_UPDATECACHE_NO_OBJECTINDEX_PARA_1 {
            get {
                return ResourceManager.GetString("_TCDATA_DATA_UPDATECACHE_NO_OBJECTINDEX_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None defined error when call GetSpecialTableDataToList.[{0}].
        /// </summary>
        internal static string _TCDATA_EXCEPTION_LOADDATA {
            get {
                return ResourceManager.GetString("_TCDATA_EXCEPTION_LOADDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions come across when reading data from TCfile or database.[{0}].
        /// </summary>
        internal static string _TCDATA_EXCEPTION_READFROM_ONEROW {
            get {
                return ResourceManager.GetString("_TCDATA_EXCEPTION_READFROM_ONEROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load Tablenames/SheetNames from DataFile.Error Code:[{0}].
        /// </summary>
        internal static string _TCDATA_LOAD_TABLENAMES {
            get {
                return ResourceManager.GetString("_TCDATA_LOAD_TABLENAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data records found on Database or table sheet[{0}]..
        /// </summary>
        internal static string _TCDATA_NO_DATA_FIND {
            get {
                return ResourceManager.GetString("_TCDATA_NO_DATA_FIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such table/Sheet [{0}] exists on Database/DataXlsFile..
        /// </summary>
        internal static string _TCDATA_NO_DATA_SHEET {
            get {
                return ResourceManager.GetString("_TCDATA_NO_DATA_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such Adapter is supported for Test script Data :[{0}].
        /// </summary>
        internal static string _TCDATA_NO_SUCH_ADAPTER {
            get {
                return ResourceManager.GetString("_TCDATA_NO_SUCH_ADAPTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such Data file exists:[{0}].
        /// </summary>
        internal static string _TCDATA_NO_SUCH_DATAFILE {
            get {
                return ResourceManager.GetString("_TCDATA_NO_SUCH_DATAFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number (1/2) should after ColIndex. Current Setting string:[0].
        /// </summary>
        internal static string _TEST_KEYWORD_SETTING_CAPTUREVALUE_COMPARISON_NUMBER_PARA_1 {
            get {
                return ResourceManager.GetString("_TEST_KEYWORD_SETTING_CAPTUREVALUE_COMPARISON_NUMBER_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureValue settings(comparison mode) are wrong. Formatter should be -[StorageMode:Comparing;ColIndx:&lt;Number 1 or 2&gt;;ConvertMethod:&lt;string&gt;];ObjectHappName. Current Setting string:[{0}].
        /// </summary>
        internal static string _TEST_KEYWORD_SETTING_CAPTUREVALUE_COMPARISON_PARA_1 {
            get {
                return ResourceManager.GetString("_TEST_KEYWORD_SETTING_CAPTUREVALUE_COMPARISON_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapturavalueAndcompare only support &apos;Build/Comprison&apos;. Current parameter is:[{0}].
        /// </summary>
        internal static string _TEST_STEP_COMPARISON_MODE_BASELINE_PARAMETER_NOTSUPPORT_PARA_1 {
            get {
                return ResourceManager.GetString("_TEST_STEP_COMPARISON_MODE_BASELINE_PARAMETER_NOTSUPPORT_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Step file setting problem, no Object Name info on Value column. setting string :[{0}].
        /// </summary>
        internal static string _TEST_STEP_COMPARISON_MODE_VALUE_SETTING_NO_OBJECT_PARA_1 {
            get {
                return ResourceManager.GetString("_TEST_STEP_COMPARISON_MODE_VALUE_SETTING_NO_OBJECT_PARA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such Test Step Info or No such Sheet Name in TC file..
        /// </summary>
        internal static string _TEST_STEP_NO_SUCH_TABLE_OR_SHEET {
            get {
                return ResourceManager.GetString("_TEST_STEP_NO_SUCH_TABLE_OR_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Open co-[App].config file.
        /// </summary>
        internal static string APP_CONFIG_ERROR_CONFIGOBJ_NULL {
            get {
                return ResourceManager.GetString("APP_CONFIG_ERROR_CONFIGOBJ_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XlsMode configuration node in App.config file.
        /// </summary>
        internal static string APP_CONFIG_ERROR_NOXLSMODE_SECTOIN {
            get {
                return ResourceManager.GetString("APP_CONFIG_ERROR_NOXLSMODE_SECTOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter,DataRow is Null.
        /// </summary>
        internal static string DATA_ROW_IS_NULL {
            get {
                return ResourceManager.GetString("DATA_ROW_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, there is no reg application setting in App.config.  Item like &quot;&lt;add key=&quot;RegistedApplicationsMode&quot; value=&quot;config&quot;&gt;&lt;/add&gt;&quot; should be inserted into config file..
        /// </summary>
        internal static string ERR_CONFIG_NO_REGAPPLICATONS_SETTING_IN_CONFIG_FILE {
            get {
                return ResourceManager.GetString("ERR_CONFIG_NO_REGAPPLICATONS_SETTING_IN_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function:[{0}] returns [{1}].
        /// </summary>
        internal static string FUNTION_RETURN_VALUE {
            get {
                return ResourceManager.GetString("FUNTION_RETURN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start Framework Service, Check Log file to find details..
        /// </summary>
        internal static string HINT_CANT_START_FRAMEWORK_SERVICE {
            get {
                return ResourceManager.GetString("HINT_CANT_START_FRAMEWORK_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Object[{0}] is initized..
        /// </summary>
        internal static string HINT_CLASS_INITED {
            get {
                return ResourceManager.GetString("HINT_CLASS_INITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get such section from app.config file as Name-Value collection. Section Name:[{0}].
        /// </summary>
        internal static string HINT_CONFIGREADER_NO_SUCHSECTION_AS_NAMEVALUE {
            get {
                return ResourceManager.GetString("HINT_CONFIGREADER_NO_SUCHSECTION_AS_NAMEVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Creates a new instance..
        /// </summary>
        internal static string HINT_CREATE_NEW_SINGLE_INSTANCE {
            get {
                return ResourceManager.GetString("HINT_CREATE_NEW_SINGLE_INSTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current regApplication setting is config file.
        /// </summary>
        internal static string HINT_FIND_APPLICATION_SETTINGMODE_CONFIG {
            get {
                return ResourceManager.GetString("HINT_FIND_APPLICATION_SETTINGMODE_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current regApplicaton setting is Database.
        /// </summary>
        internal static string HINT_FIND_APPLICATOIN_SETTINGMODE_DATABASE {
            get {
                return ResourceManager.GetString("HINT_FIND_APPLICATOIN_SETTINGMODE_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find application setting for ObjectSource:DataBase.
        /// </summary>
        internal static string HINT_FIND_APPLICATON_SETTING_OBJECTSOURCE_DB {
            get {
                return ResourceManager.GetString("HINT_FIND_APPLICATON_SETTING_OBJECTSOURCE_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find application setting for ObjectSource:Xls.
        /// </summary>
        internal static string HINT_FIND_APPLICATON_SETTING_OBJECTSOURCE_XLS {
            get {
                return ResourceManager.GetString("HINT_FIND_APPLICATON_SETTING_OBJECTSOURCE_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Validate class is Set, return true..
        /// </summary>
        internal static string HINT_KEYWORD_VALIDATE_NO_VALIDATECLASS_RETURN_TRUE {
            get {
                return ResourceManager.GetString("HINT_KEYWORD_VALIDATE_NO_VALIDATECLASS_RETURN_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returns {1}.
        /// </summary>
        internal static string HINT_RETURN_WITH_VALUE {
            get {
                return ResourceManager.GetString("HINT_RETURN_WITH_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to below is runnable script with values..
        /// </summary>
        internal static string HINT_RUNABLESCRIPT_STARTER_MARK {
            get {
                return ResourceManager.GetString("HINT_RUNABLESCRIPT_STARTER_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default test action for Tiger Mars Automaion Testing Framework..
        /// </summary>
        internal static string HINT_TEST_ACTION_DEFAULT_DESCRIPTION {
            get {
                return ResourceManager.GetString("HINT_TEST_ACTION_DEFAULT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find path root:[{0}].
        /// </summary>
        internal static string STRFORMAT_0_FIND_XLSPATH_ROOT {
            get {
                return ResourceManager.GetString("STRFORMAT_0_FIND_XLSPATH_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Test Suites are done!.
        /// </summary>
        internal static string SYS_RESULT_DONE {
            get {
                return ResourceManager.GetString("SYS_RESULT_DONE", resourceCulture);
            }
        }
    }
}
