//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PROJ_TS_TC_FULLVISION
    {
        public long TEST_SUITE_ID { get; set; }
        public string TEST_SUITE_NAME { get; set; }
        public string TEST_SUITE_DESCRIPTION { get; set; }
        public long TEST_CASE_ID { get; set; }
        public string TEST_CASE_NAME { get; set; }
        public Nullable<System.DateTime> TEST_STEP_CREATE_TIME { get; set; }
        public string TEST_STEP_CREATOR { get; set; }
        public string TEST_STEP_DESCRIPTION { get; set; }
        public Nullable<int> USAGE_STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATOR { get; set; }
        public string PROJECT_DESCRIPTION { get; set; }
        public int PROJECT_ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string DATA_ALIAS { get; set; }
        public long DATA_SUMMARY_ID { get; set; }
        public Nullable<int> DATA_AVAILABLE_MARK { get; set; }
        public Nullable<int> DATA_VERSION { get; set; }
        public Nullable<int> DATA_STATUS { get; set; }
        public Nullable<int> DATA_SET_TYPE { get; set; }
        public string DATASET_DESCRIPTION { get; set; }
    }
}
