<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>10</LangVersion>
    <RootNamespace>MaRSAgentServerDemo</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\AIAgentClient.csproj" />
  </ItemGroup>
</Project>
