using System.Collections.Generic;

namespace MARS.WebAutomation.Services
{
    /// <summary>Workbench UI strings (English / 中文) keyed for menus, tabs, and messages.</summary>
    public static class UiStrings
    {
        private static readonly Dictionary<string, (string En, string Zh)> Map = new Dictionary<string, (string, string)>
        {
            ["AppTitle"] = ("MARS Web Automation", "MARS 网页自动化"),
            ["File"] = ("File", "文件"),
            ["Save"] = ("Save", "保存"),
            ["Load"] = ("Load…", "加载…"),
            ["Clear"] = ("Clear", "清空"),
            ["Export"] = ("Export Object…", "导出对象…"),
            ["Import"] = ("Import Object…", "导入对象…"),
            ["Exit"] = ("Exit", "退出"),
            ["Help"] = ("Help", "帮助"),
            ["About"] = ("About", "关于"),
            ["Language"] = ("Language", "语言"),
            ["English"] = ("English", "英语"),
            ["Chinese"] = ("中文 (简体)", "中文 (简体)"),
            ["Target"] = ("Target", "目标页"),
            ["Objects"] = ("Objects", "对象"),
            ["RecordReplay"] = ("Record / Replay", "录制 / 回放"),
            ["ApiPerformanceTesting"] = ("API Performance Testing", "API 性能测试"),
            ["Settings"] = ("Settings", "设置"),
            ["PageUrl"] = ("Page URL", "页面 URL"),
            ["StartBrowser"] = ("Start browser", "启动浏览器"),
            ["Navigate"] = ("Navigate", "导航"),
            ["Scheme"] = ("Scheme:", "协议:"),
            ["Host"] = ("Host:", "主机:"),
            ["Port"] = ("Port:", "端口:"),
            ["Path"] = ("Path:", "路径:"),
            ["Query"] = ("Query:", "查询:"),
            ["RefreshTree"] = ("Refresh tree", "刷新树"),
            ["TreeSearch"] = ("Search tree…", "在树中搜索…"),
            ["SearchGo"] = ("Find", "查找"),
            ["SearchPrev"] = ("Previous match", "上一个"),
            ["SearchNext"] = ("Next match", "下一个"),
            ["RegexMode"] = ("Regex", "正则"),
            ["DataRoot"] = ("Data root folder", "数据根目录"),
            ["Headless"] = ("Headless mode", "无头模式"),
            ["Timeout"] = ("Default timeout (ms)", "默认超时 (毫秒)"),
            ["PersistHeaders"] = ("Persist sensitive headers/cookies in network log", "在网络日志中保留敏感头/Cookie"),
            ["Channel"] = ("Browser channel (opt.)", "浏览器通道 (可选)"),
            ["Viewport"] = ("Viewport W / H", "视口 宽 / 高"),
            ["SaveSettings"] = ("Save settings", "保存设置"),
            ["Ready"] = ("Ready", "就绪"),
            ["Brand"] = ("MARS Web Automation", "MARS 网页自动化"),
            ["ToolbarTarget"] = ("Target", "拾取"),
            ["ToolbarRecord"] = ("Record", "录制"),
            ["ToolbarReplay"] = ("Replay", "回放"),
            ["ToolbarExport"] = ("Export Object", "导出对象"),
            ["ToolbarImport"] = ("Import Object", "导入对象"),
            ["ToolbarSave"] = ("Save", "保存"),
            ["ToolbarReloadEngine"] = ("Reload engine", "重载引擎"),
            ["ToolbarSync"] = ("Sync", "同步"),
            ["ToolbarWithPerformanceTest"] = ("With Performance Test", "启用性能测试"),
            ["ToolbarRunPerf"] = ("Run Perf", "运行性能"),
            ["ToolbarStopPerf"] = ("Stop", "停止"),
            ["ToolbarRunSelectedAnchor"] = ("Run Selected Anchor", "运行选中锚点"),
            ["ApiPerformanceHint"] = ("Use this module to execute NBomber API performance testing and manage performance packs.", "在此模块执行 NBomber API 性能测试，并管理性能包。"),
            ["ApiPerfRun"] = ("Run NBomber", "运行 NBomber"),
            ["ApiPerfConfig"] = ("Configure Transactions", "配置事务"),
            ["ApiPerfExport"] = ("Export Performance Pack", "导出性能包"),
            ["ApiPerfImport"] = ("Import Performance Pack", "导入性能包"),
            ["ApiPerfGoRecord"] = ("Open Record/Replay Performance Grid", "打开录制回放性能面板"),
            ["SkipInjectPrefixes"] = ("Skip inject URL prefixes", "跳过注入的 URL 前缀"),
            ["RecorderTabDepth"] = ("Recorder: tab context ancestor depth (1–12)", "录制：Tab 语义向上查找层数 (1–12)"),
            ["PerformanceFilterTokens"] = ("Performance filter tokens (semicolon-separated; match filter tag or resource type)", "性能筛选词（分号分隔；匹配 FilterTag 或资源类型）"),
            ["Prop.OuterHtml"] = ("outerHTML", "outerHTML"),
            ["RecordHint"] = ("Record: semantic steps in the grid (left); workflow map (right). Drag nodes to arrange; positions are saved with the test JSON.", "录制：左侧为语义步骤表，右侧为流程图。可拖动节点排版，位置随测试 JSON 保存。"),
            ["PreviewTitle"] = ("Preview", "预览"),
            ["PropColumn"] = ("Property", "属性"),
            ["ValueColumn"] = ("Value", "值"),
            ["StepsColAction"] = ("Action", "操作"),
            ["StepsColOrder"] = ("#", "序号"),
            ["StepsColElapsed"] = ("Δ ms", "耗时 ms"),
            ["StepsColKeyword"] = ("Keyword", "关键字"),
            ["StepsColEvent"] = ("Event", "事件"),
            ["StepsColData"] = ("Data", "数据"),
            ["StepsColBounds"] = ("Bounds", "布局"),
            ["StepsColLogicalKind"] = ("Logical", "逻辑对象"),
            ["StepsColLocator"] = ("Locator", "定位"),
            ["StepsColXPath"] = ("XPath", "XPath"),
            ["StepsColLocatorAlt"] = ("Alt locators", "备用定位"),
            ["StepsColParameter"] = ("Parameter", "参数"),
            ["StepsMoveUp"] = ("Move step up", "上移步骤"),
            ["StepsMoveDown"] = ("Move step down", "下移步骤"),
            ["GridRun"] = ("Run", "运行"),
            ["GridDelete"] = ("Delete", "删除"),
            ["GridHighlight"] = ("Highlight", "高亮"),
            ["GridExport"] = ("Export", "导出"),
            ["GridInsertRow"] = ("Insert row", "增加一行"),
            ["GridPrettyPaint"] = ("Pretty Paint", "自动排版"),
            ["GridExportHasEmptyKeyword"] = ("Please fill all keywords before export.", "导出前请先填写所有 keyword。"),
            ["CanvasZoomOut"] = ("Zoom out", "缩小"),
            ["CanvasZoomIn"] = ("Zoom in", "放大"),
            ["CanvasCenter"] = ("Center", "居中"),
            ["CanvasZoomLevel"] = ("Zoom level", "缩放比例"),
            ["BadRegex"] = ("Invalid regular expression.", "正则表达式无效。"),
            ["SearchNoMatch"] = ("No tree node matched the search.", "没有节点匹配搜索条件。"),
            ["SearchMatchCount"] = ("{0} matching node(s).", "共 {0} 个匹配节点。"),
            ["UriInvalid"] = ("(invalid URL)", "(无效 URL)"),
            ["UriScheme"] = ("Scheme: ", "协议: "),
            ["UriHost"] = ("Host: ", "主机: "),
            ["UriPortDefault"] = ("Port: (default)", "端口: (默认)"),
            ["UriPort"] = ("Port: ", "端口: "),
            ["UriPath"] = ("Path: ", "路径: "),
            ["UriQuery"] = ("Query: ", "查询: "),
            ["UriQueryNone"] = ("(none)", "(无)"),
            ["Prop.InteractiveKind"] = ("Interactive kind", "交互类型"),
            ["Prop.ClassName"] = ("class", "class"),
            ["Prop.NameAttr"] = ("name", "name"),
            ["Prop.Title"] = ("title", "title"),
            ["Prop.Href"] = ("href", "href"),
            ["Prop.Type"] = ("type", "type"),
            ["Prop.Placeholder"] = ("placeholder", "placeholder"),
            ["Prop.AriaLabel"] = ("aria-label", "aria-label"),
            ["Prop.AriaChecked"] = ("aria-checked", "aria-checked"),
            ["Prop.AriaControls"] = ("aria-controls", "aria-controls"),
            ["Prop.AriaDescribedby"] = ("aria-describedby", "aria-describedby"),
            ["Prop.AriaExpanded"] = ("aria-expanded", "aria-expanded"),
            ["Prop.AriaLabelledby"] = ("aria-labelledby", "aria-labelledby"),
            ["Prop.AriaSelected"] = ("aria-selected", "aria-selected"),
            ["Prop.Autocomplete"] = ("autocomplete", "autocomplete"),
            ["Prop.DataAttrs"] = ("data-*", "data-*"),
            ["Prop.ForAttr"] = ("for", "for"),
            ["Prop.Hidden"] = ("hidden", "hidden"),
            ["Prop.HtmlId"] = ("id", "id"),
            ["Prop.Locator"] = ("locator", "locator"),
            ["Prop.Pattern"] = ("pattern", "pattern"),
            ["Prop.Readonly"] = ("readonly", "readonly"),
            ["Prop.Required"] = ("required", "required"),
            ["Prop.Value"] = ("value", "value"),
            ["Prop.Xpath"] = ("xpath", "xpath"),
            ["Prop.TabIndex"] = ("tabindex", "tabindex"),
            ["Prop.Disabled"] = ("disabled", "disabled"),
            ["Prop.ContentEditable"] = ("contenteditable", "contenteditable"),
            ["Prop.TextPreview"] = ("Text preview", "文本预览"),
            ["Prop.LocatorHint"] = ("CSS locator hint", "CSS 定位提示"),
            ["Prop.PageInstanceId"] = ("Page instance id", "页面实例"),
            ["Prop.Id"] = ("Tree node id", "树节点 id"),
            ["Prop.Tag"] = ("Tag", "标签"),
            ["Prop.Role"] = ("role", "role"),
            ["Prop.X"] = ("X (viewport)", "X (视口)"),
            ["Prop.Y"] = ("Y (viewport)", "Y (视口)"),
            ["Prop.W"] = ("Width", "宽度"),
            ["Prop.H"] = ("Height", "高度"),
        };

        public static string T(string key, string language)
        {
            var lang = (language ?? "en").Trim();
            var zh = lang.StartsWith("zh", System.StringComparison.OrdinalIgnoreCase);
            if (!Map.TryGetValue(key, out var pair))
                return key;
            return zh ? pair.Zh : pair.En;
        }
    }
}
